from dergi import *

bolumler = [
    BOLUM("editor", "edit_note", "#6C63FF", "Editor's Note", "Editörden",
        P(("Hello, and welcome to our summer issue.", "Merhaba, yaz sayımıza hoş geldin."),
          ("August 2026 starts on a Saturday and has 31 days.", "Ağustos 2026 cumartesi günü başlıyor ve 31 gün sürüyor."),
          ("Since 31 = 4 × 7 + 3, the weekdays of the 1st, 2nd and 3rd of the month appear five times.", "31 = 4 × 7 + 3 olduğu için ayın 1, 2 ve 3'üne denk gelen günler takvimde beşer kez geliyor."),
          ("So this August has five Saturdays, five Sundays and five Mondays, in other words five full weekends.", "Yani bu ağustosta beş cumartesi, beş pazar ve beş pazartesi var, bir başka deyişle tam beş hafta sonu.")),
        P(("The theme of this month is **maths in everyday life and nature**.", "Bu ayın teması **gündelik hayatta ve doğada matematik**."),
          ("On a summer night you only need to look up to see it.", "Bir yaz gecesi onu görmek için başını kaldırman yeterli."),
          ("The Moon covered the Sun over Iceland and Spain, and the Perseid meteors filled the dark sky on the same night.", "Ay, İzlanda ve İspanya üzerinde Güneş'i kapattı ve aynı gece Perseid meteorları karanlık gökyüzünü doldurdu."),
          ("Behind both events there are orbits, and behind orbits there is mathematics.", "İki olayın arkasında da yörüngeler, yörüngelerin arkasında da matematik var.")),
        P(("Our mathematician of the month once found a lost planet with nothing but a pen, paper and a new idea.", "Ayın matematikçisi bir zamanlar kaybolan bir gezegeni yalnızca kalem, kâğıt ve yeni bir fikirle buldu."),
          ("His name was Carl Friedrich Gauss, and you will meet him, his famous trick and his famous curve in this issue.", "Adı Carl Friedrich Gauss'tu ve bu sayıda onunla, meşhur hilesiyle ve meşhur eğrisiyle tanışacaksın."),
          ("Find a shady spot and enjoy your break!", "Gölgede bir köşe bul ve iyi molalar!")),
    ),

    BOLUM("haber", "newspaper", "#2E86DE", "News from the World of Maths", "Matematik Dünyasından Haberler",
        H("An AI model called Astra and ten open problems", "Astra adlı yapay zekâ modeli ve on açık problem"),
        P(("On 1 August 2026, OpenAI announced that an unreleased internal model called **Astra** had produced new results on 10 problems.", "1 Ağustos 2026'da OpenAI, henüz yayımlanmamış **Astra** adlı şirket içi bir modelin 10 problemde yeni sonuçlar ürettiğini duyurdu."),
          ("According to the company, all of them came from mathematics and theoretical computer science, and each had been open for at least ten years.", "Şirkete göre hepsi matematik ve teorik bilgisayar biliminden geliyordu ve her biri en az on yıldır açıktı."),
          ("Three of them were problems from the famous list of Paul Erdős.", "Bunlardan üçü Paul Erdős'ün ünlü listesindeki problemlerdi."),
          ("Another one answered a question about so-called **sofic groups** that Mikhail Gromov had asked in 1999.", "Bir diğeri, Mikhail Gromov'un 1999'da sorduğu, **sofik gruplar** denen yapılarla ilgili bir soruyu cevapladı.")),
        P(("The company published the proofs together with **Lean** certificates.", "Şirket ispatları **Lean** sertifikalarıyla birlikte yayımladı."),
          ("Lean is a computer language that checks a proof step by step and gives a simple verdict: correct or not.", "Lean, bir ispatı adım adım kontrol eden ve basit bir karar veren bir bilgisayar dili: doğru ya da değil."),
          ("However, a computer cannot decide whether the formal statement really matches the original problem.", "Ancak bir bilgisayar, biçimsel ifadenin gerçekten orijinal problemle örtüşüp örtüşmediğine karar veremez."),
          ("That job still belongs to human mathematicians, and none of the ten results had been **peer reviewed** at the time of the announcement.", "Bu iş hâlâ insan matematikçilere ait ve duyuru sırasında on sonucun hiçbiri **hakem değerlendirmesinden** geçmemişti.")),
        P(("Thomas Bloom, who runs the website erdosproblems.com, called the results \"big news\".", "erdosproblems.com sitesini yöneten Thomas Bloom sonuçları \"büyük haber\" olarak nitelendirdi."),
          ("Two days later, Quanta Magazine reported that the site listed 565 solved and 652 open Erdős problems.", "İki gün sonra Quanta Magazine, sitede 565 çözülmüş ve 652 açık Erdős problemi bulunduğunu yazdı."),
          ("The article also reminded readers that most Erdős problems come from number theory, combinatorics and graph theory, so these successes may not carry over to every area of mathematics.", "Makale ayrıca Erdős problemlerinin çoğunun sayılar teorisi, kombinatorik ve graf teorisinden geldiğini, bu yüzden bu başarıların matematiğin her alanına taşınamayabileceğini hatırlattı.")),
        H("The total solar eclipse of 12 August", "12 Ağustos tam güneş tutulması"),
        P(("On 12 August 2026, the Moon's shadow crossed Greenland, Iceland and northern Spain.", "12 Ağustos 2026'da Ay'ın gölgesi Grönland, İzlanda ve kuzey İspanya'dan geçti."),
          ("The greatest eclipse took place at 17:47 UTC, and the longest **totality** lasted 2 minutes and 18 seconds.", "Tutulmanın en büyük anı 17:47 UTC'de yaşandı ve en uzun **tam evre** 2 dakika 18 saniye sürdü."),
          ("Cities such as A Coruña, Bilbao, Zaragoza, Valencia and Palma were inside the path, while Madrid and Barcelona were just outside it.", "A Coruña, Bilbao, Zaragoza, Valencia ve Palma gibi şehirler yolun içindeydi, Madrid ve Barselona ise hemen dışında kaldı.")),
        LISTE(("It was the first total solar eclipse seen from mainland Spain since 30 August 1905.", "Bu, 30 Ağustos 1905'ten beri İspanya anakarasından görülen ilk tam güneş tutulmasıydı."),
              ("For Iceland, it was the first one since 30 June 1954.", "İzlanda için ise 30 Haziran 1954'ten beri ilk tam tutulmaydı."),
              ("Spain chose 660 official viewing sites for the event.", "İspanya bu olay için 660 resmî gözlem noktası belirledi."),
              ("Spain will not wait long for the next one: on 2 August 2027 another total eclipse will cross the south of the country and North Africa.", "İspanya bir sonrakini uzun süre beklemeyecek: 2 Ağustos 2027'de başka bir tam tutulma ülkenin güneyinden ve Kuzey Afrika'dan geçecek.")),
        KUTU("bilgi", "Where is the maths?", "Matematik nerede?",
             ("Astronomers can predict the time of an eclipse to the second, centuries in advance.", "Astronomlar bir tutulmanın zamanını yüzyıllar öncesinden saniyesine kadar hesaplayabiliyor."),
             ("Eclipses also repeat in families called **Saros series**, with a period of about 18 years and 11 days.", "Tutulmalar ayrıca yaklaşık 18 yıl 11 günlük bir periyotla, **Saros serileri** denen ailelerde tekrar ediyor."),
             ("This eclipse belongs to Saros 126.", "Bu tutulma Saros 126 serisine ait.")),
        H("A new telescope on its way", "Yola çıkan yeni bir teleskop"),
        P(("On 30 August 2026, NASA's **Nancy Grace Roman Space Telescope** was launched from Florida on a Falcon Heavy rocket.", "30 Ağustos 2026'da NASA'nın **Nancy Grace Roman Uzay Teleskobu** Florida'dan bir Falcon Heavy roketiyle fırlatıldı."),
          ("Its view of the sky is about 100 times wider than Hubble's.", "Gökyüzünü gören alanı Hubble'ınkinden yaklaşık 100 kat daha geniş."),
          ("It will study dark matter, dark energy and planets around other stars, and it is expected to catalogue about 20 billion stars.", "Karanlık maddeyi, karanlık enerjiyi ve başka yıldızların etrafındaki gezegenleri inceleyecek ve yaklaşık 20 milyar yıldızı kataloglaması bekleniyor."),
          ("Mathematicians will be busy too, because handling so much data needs serious statistics.", "Matematikçilerin de işi çok, çünkü bu kadar veriyle başa çıkmak ciddi bir istatistik gerektiriyor.")),
        KUTU("sinif", "For the classroom", "Sınıf için",
             ("Ask students: if an AI writes a proof that a computer has checked, do we still need a human to read it?", "Öğrencilere sor: Yapay zekâ bir ispat yazsa ve bir bilgisayar onu kontrol etse, yine de bir insanın okumasına ihtiyaç var mı?"),
             ("The Astra story shows that the answer is yes, because someone must check that the right question was proved.", "Astra hikâyesi cevabın evet olduğunu gösteriyor, çünkü birinin doğru sorunun ispatlandığını kontrol etmesi gerekiyor.")),
        TERIMLER(("internal model", "şirket içi model"), ("peer review", "hakem değerlendirmesi"),
                 ("certificate", "sertifika"), ("total solar eclipse", "tam güneş tutulması"),
                 ("totality", "tam evre"), ("Saros cycle", "Saros döngüsü")),
    ),

    BOLUM("makale", "article", "#8E44AD", "Paper of the Month: The Method of Least Squares", "Ayın Makalesi: En Küçük Kareler Yöntemi",
        KUTU("bilgi", "Source", "Kaynak",
             ("C. F. Gauss, Theoria Motus Corporum Coelestium in Sectionibus Conicis Solem Ambientium (Theory of the Motion of Heavenly Bodies Moving about the Sun in Conic Sections), Hamburg, 1809.", "C. F. Gauss, Theoria Motus Corporum Coelestium in Sectionibus Conicis Solem Ambientium (Güneş Etrafında Konik Kesitler Üzerinde Hareket Eden Gök Cisimlerinin Hareket Teorisi), Hamburg, 1809."),
             ("Adrien-Marie Legendre had published the same method a few years earlier, in 1805.", "Adrien-Marie Legendre aynı yöntemi birkaç yıl önce, 1805'te yayımlamıştı.")),
        H("The problem", "Problem"),
        P(("Every measurement contains a small **error**.", "Her ölçüm küçük bir **hata** içerir."),
          ("If you measure the length of your desk three times, you may get 120.2 cm, 119.9 cm and 120.0 cm.", "Masanın uzunluğunu üç kez ölçersen 120,2 cm, 119,9 cm ve 120,0 cm bulabilirsin."),
          ("Around 1800, astronomers had the same problem, only with planets.", "1800 civarında astronomlar da aynı problemi yaşıyordu, sadece gezegenlerle."),
          ("They had many observations that did not agree exactly, and they wanted the single orbit that fitted them best.", "Birbirini tam olarak tutmayan çok sayıda gözlemleri vardı ve onlara en iyi uyan tek bir yörüngeyi istiyorlardı.")),
        H("The idea", "Fikir"),
        P(("For each observation, look at the difference between the measured value and the value your model predicts.", "Her gözlem için ölçülen değer ile modelinin öngördüğü değer arasındaki farka bak."),
          ("This difference is called a **residual**.", "Bu farka **artık** denir."),
          ("Some residuals are positive and some are negative, so simply adding them is not useful.", "Artıkların bazıları pozitif, bazıları negatif, bu yüzden onları doğrudan toplamak işe yaramaz."),
          ("Gauss's answer was to square them first and then choose the model that makes the sum of squares as small as possible.", "Gauss'un cevabı, önce onların karesini almak ve sonra kareler toplamını olabildiğince küçük yapan modeli seçmekti.")),
        FORMUL("minimise  S = Σ (yᵢ − f(xᵢ))²"),
        H("The simplest case: the mean", "En basit durum: ortalama"),
        P(("Suppose the model is just one number c, the \"true\" length of the desk.", "Modelin tek bir c sayısı, yani masanın \"gerçek\" uzunluğu olduğunu varsayalım."),
          ("We want to minimise S(c) = Σ (xᵢ − c)².", "S(c) = Σ (xᵢ − c)² ifadesini en küçük yapmak istiyoruz."),
          ("Take the **derivative** and set it equal to zero.", "**Türevini** alıp sıfıra eşitleyelim.")),
        FORMUL("S′(c) = −2 · Σ (xᵢ − c) = 0   ⟹   c = (x₁ + x₂ + … + xₙ) / n"),
        P(("The best value is exactly the **arithmetic mean**.", "En iyi değer tam olarak **aritmetik ortalamadır**."),
          ("For our desk, it is (120.2 + 119.9 + 120.0) / 3 = 120.03 cm.", "Masamız için bu (120,2 + 119,9 + 120,0) / 3 = 120,03 cm."),
          ("So the average we learn in primary school is secretly a least squares answer.", "Yani ilkokulda öğrendiğimiz ortalama, aslında gizli bir en küçük kareler cevabıdır.")),
        H("Fitting a line", "Doğru uydurmak"),
        P(("Now let the model be a straight line, y = a + bx.", "Şimdi model bir doğru olsun, y = a + bx."),
          ("We set the **partial derivatives** with respect to a and b equal to zero.", "a'ya ve b'ye göre **kısmi türevleri** sıfıra eşitliyoruz."),
          ("This gives two linear equations, which are called the **normal equations**.", "Bu bize **normal denklemler** denen iki doğrusal denklem verir.")),
        FORMUL("n · a + (Σxᵢ) · b = Σyᵢ"),
        FORMUL("(Σxᵢ) · a + (Σxᵢ²) · b = Σxᵢyᵢ"),
        P(("Two unknowns and two equations: a student in grade 9 can already solve this.", "İki bilinmeyen ve iki denklem: Bunu 9. sınıf öğrencisi bile çözebilir."),
          ("Every \"trend line\" in a spreadsheet is calculated in exactly this way.", "Hesap tablosundaki her \"eğilim çizgisi\" tam olarak bu şekilde hesaplanır.")),
        H("Where does the bell curve come from?", "Çan eğrisi nereden geliyor?"),
        P(("In the same book Gauss asked a deeper question: why should we square the errors at all?", "Gauss aynı kitapta daha derin bir soru sordu: Hataların karesini neden alalım ki?"),
          ("He assumed that the arithmetic mean of several measurements is always the most probable value.", "Birkaç ölçümün aritmetik ortalamasının her zaman en olası değer olduğunu varsaydı."),
          ("From this single assumption he found the only error law that fits it.", "Bu tek varsayımdan, ona uyan tek hata yasasını buldu."),
          ("Today we call it the **normal distribution**, or simply the **bell curve**.", "Bugün ona **normal dağılım** ya da kısaca **çan eğrisi** diyoruz.")),
        FORMUL("f(x) = 1 / (σ√(2π)) · e^(−(x − μ)² / (2σ²))"),
        P(("Here μ is the mean and σ is the **standard deviation**, which measures how spread out the errors are.", "Burada μ ortalama, σ ise hataların ne kadar yayıldığını ölçen **standart sapmadır**."),
          ("When errors follow this curve, least squares is the most natural method of all.", "Hatalar bu eğriyi izlediğinde en küçük kareler, yöntemlerin en doğalı olur."),
          ("Small errors are common, large errors are rare, and the curve is symmetric around the mean.", "Küçük hatalar sık, büyük hatalar nadirdir ve eğri ortalamanın etrafında simetriktir.")),
        KUTU("bilgi", "Graduate corner", "Yüksek lisans köşesi",
             ("In matrix form the normal equations become AᵀA x = Aᵀb, and this is the starting point of **linear regression**.", "Matris biçiminde normal denklemler AᵀA x = Aᵀb olur ve bu, **doğrusal regresyonun** başlangıç noktasıdır."),
             ("Geometrically, Ax is the **orthogonal projection** of b onto the column space of A.", "Geometrik olarak Ax, b'nin A'nın sütun uzayı üzerine **dik izdüşümüdür**."),
             ("A later result, the Gauss–Markov theorem, shows that least squares is the best linear unbiased estimator even without assuming normal errors.", "Daha sonraki bir sonuç olan Gauss–Markov teoremi, hataların normal olduğu varsayılmasa bile en küçük karelerin en iyi doğrusal yansız tahmin edici olduğunu gösterir.")),
        TERIMLER(("least squares", "en küçük kareler"), ("residual", "artık"), ("normal equations", "normal denklemler"),
                 ("normal distribution", "normal dağılım"), ("standard deviation", "standart sapma"),
                 ("linear regression", "doğrusal regresyon")),
    ),

    BOLUM("bilim", "science", "#0E7490", "Science Corner: Orbits, a Lost Planet and Shooting Stars", "Bilim Köşesi: Yörüngeler, Kayıp Bir Gezegen ve Yıldız Kaymaları",
        H("Lost on the other side of the Sun", "Güneş'in öbür yanında kaybolan"),
        P(("On 1 January 1801, the Italian astronomer **Giuseppe Piazzi** saw a small moving point of light from Palermo.", "1 Ocak 1801'de İtalyan astronom **Giuseppe Piazzi**, Palermo'dan küçük, hareket eden bir ışık noktası gördü."),
          ("It was between the orbits of Mars and Jupiter, exactly where many astronomers expected a missing planet.", "Mars ile Jüpiter'in yörüngeleri arasındaydı, tam da birçok astronomun kayıp bir gezegen beklediği yerde."),
          ("Piazzi followed it for about six weeks, but then it moved too close to the Sun in the sky and disappeared in its glare.", "Piazzi onu yaklaşık altı hafta takip etti, ama sonra gökyüzünde Güneş'e fazla yaklaştı ve onun parıltısında kayboldu."),
          ("He had only a short arc of observations, and nobody knew where to look when it came back.", "Elinde sadece kısa bir gözlem yayı vardı ve geri döndüğünde nereye bakılacağını kimse bilmiyordu.")),
        P(("The 24-year-old Gauss took up the challenge.", "24 yaşındaki Gauss bu meydan okumayı kabul etti."),
          ("He developed a new method to calculate a whole **orbit** from just three observations.", "Yalnızca üç gözlemden bütün bir **yörüngeyi** hesaplayan yeni bir yöntem geliştirdi."),
          ("On 31 December 1801, Franz Xaver von Zach found the object again, very close to the position Gauss had predicted.", "31 Aralık 1801'de Franz Xaver von Zach cismi, Gauss'un öngördüğü konuma çok yakın bir yerde yeniden buldu."),
          ("Its name is **Ceres**, and since 2006 it has been called a **dwarf planet**.", "Adı **Ceres** ve 2006'dan beri **cüce gezegen** olarak adlandırılıyor.")),
        H("Kepler's third law", "Kepler'in üçüncü yasası"),
        P(("Planets move on ellipses with the Sun at one **focus**.", "Gezegenler, Güneş'in bir **odakta** bulunduğu elipsler üzerinde hareket eder."),
          ("Johannes Kepler also discovered a simple rule that links the size of an orbit to the time it takes.", "Johannes Kepler ayrıca bir yörüngenin büyüklüğünü onu tamamlama süresine bağlayan basit bir kural keşfetti."),
          ("If T is measured in years and the semi-major axis a in **astronomical units** (the Earth–Sun distance), then:", "T yıl cinsinden ve büyük yarı eksen a **astronomik birim** (Dünya-Güneş uzaklığı) cinsinden ölçülürse:")),
        FORMUL("T² = a³"),
        P(("For Ceres, a ≈ 2.77, so T ≈ √(2.77³) ≈ 4.6 years.", "Ceres için a ≈ 2,77, yani T ≈ √(2,77³) ≈ 4,6 yıl."),
          ("For Jupiter, a ≈ 5.2, so T ≈ 11.9 years.", "Jüpiter için a ≈ 5,2, yani T ≈ 11,9 yıl."),
          ("A planet that is farther away does not only travel a longer path, it also moves more slowly.", "Daha uzaktaki bir gezegen yalnızca daha uzun bir yol gitmez, aynı zamanda daha yavaş hareket eder.")),
        H("The Perseids: crossing a comet's path", "Perseidler: Bir kuyrukluyıldızın yolundan geçmek"),
        P(("Every August, the Earth passes through a stream of dust left behind by **comet** 109P/Swift–Tuttle.", "Her ağustos Dünya, 109P/Swift–Tuttle **kuyrukluyıldızının** arkasında bıraktığı bir toz akıntısının içinden geçer."),
          ("The tiny grains hit our atmosphere at about 59 km per second and burn up as **meteors**.", "Küçük taneler atmosferimize saniyede yaklaşık 59 km hızla çarpar ve **meteor** olarak yanar."),
          ("Because the Earth's orbit meets the dust stream at the same point every year, the shower always comes in the same weeks.", "Dünya'nın yörüngesi toz akıntısıyla her yıl aynı noktada kesiştiği için yağmur hep aynı haftalarda gelir.")),
        P(("In 2026, the peak was on the night of 12 to 13 August.", "2026'da en yoğun zaman 12'yi 13 Ağustos'a bağlayan geceydi."),
          ("It was also a **new Moon**, so there was no moonlight to hide the faint meteors.", "Aynı zamanda **yeni ay** vardı, bu yüzden sönük meteorları gizleyecek ay ışığı yoktu."),
          ("This is not a coincidence with the eclipse: a solar eclipse can only happen at new Moon, when the Moon is between the Earth and the Sun.", "Bunun tutulmayla aynı güne denk gelmesi tesadüf değil: Güneş tutulması yalnızca Ay'ın Dünya ile Güneş arasında olduğu yeni ay evresinde olabilir.")),
        KUTU("bilgi", "The 400 coincidence", "400 tesadüfü",
             ("The Sun is about 400 times wider than the Moon, but it is also about 400 times farther away.", "Güneş, Ay'dan yaklaşık 400 kat daha geniş, ama aynı zamanda yaklaşık 400 kat daha uzakta."),
             ("That is why both look almost the same size in our sky, and why the Moon can cover the Sun so perfectly.", "Bu yüzden ikisi gökyüzümüzde neredeyse aynı büyüklükte görünür ve Ay, Güneş'i bu kadar kusursuz kapatabilir."),
             ("Readers in Türkiye may remember the total eclipse of 29 March 2006, seen from Antalya.", "Türkiye'deki okurlar Antalya'dan izlenen 29 Mart 2006 tam tutulmasını hatırlayabilir.")),
        TERIMLER(("orbit", "yörünge"), ("dwarf planet", "cüce gezegen"), ("focus (of an ellipse)", "elipsin odağı"),
                 ("astronomical unit", "astronomik birim"), ("comet", "kuyrukluyıldız"), ("meteor shower", "meteor yağmuru")),
    ),

    BOLUM("matematikci", "person", "#E67E22", "Mathematician of the Month: Carl Friedrich Gauss", "Ayın Matematikçisi: Carl Friedrich Gauss",
        PORTRE("https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Carl_Friedrich_Gauss_1840_by_Jensen.jpg/500px-Carl_Friedrich_Gauss_1840_by_Jensen.jpg",
               "Carl Friedrich Gauss", "1777 – 1855",
               "German mathematician, astronomer and physicist, often called the \"Prince of Mathematicians\".",
               "Sıklıkla \"Matematikçilerin Prensi\" olarak anılan Alman matematikçi, astronom ve fizikçi.",
               "Portrait by Christian Albrecht Jensen, 1840 · Public domain, Wikimedia Commons"),
        P(("Some mathematicians are famous for one great idea.", "Bazı matematikçiler tek bir büyük fikirle ünlüdür."),
          ("Gauss left his mark on almost every part of mathematics and on a good part of physics, too.", "Gauss ise matematiğin neredeyse her alanında, fiziğin de büyük bir kısmında iz bıraktı.")),
        H("His life", "Hayatı"),
        LISTE(("He was born on 30 April 1777 in Braunschweig, Germany, into a poor family.", "30 Nisan 1777'de Almanya'nın Braunschweig şehrinde yoksul bir ailede doğdu."),
              ("His talent was noticed early, and the Duke of Braunschweig paid for his education.", "Yeteneği erken fark edildi ve Braunschweig Dükü eğitim masraflarını üstlendi."),
              ("In 1796, at the age of 18, he showed that a regular 17-sided polygon can be constructed with only a **compass** and a **straightedge**.", "1796'da, 18 yaşındayken, düzgün 17 kenarlı bir çokgenin yalnızca **pergel** ve **cetvel** ile çizilebileceğini gösterdi."),
              ("Nobody had found a new constructible regular polygon with a prime number of sides since the ancient Greeks.", "Antik Yunanlılardan beri kimse kenar sayısı asal olan yeni bir çizilebilir düzgün çokgen bulamamıştı."),
              ("In 1801 he published Disquisitiones Arithmeticae, the book that turned **number theory** into a modern subject.", "1801'de **sayılar teorisini** modern bir alana dönüştüren kitap olan Disquisitiones Arithmeticae'yı yayımladı."),
              ("In the same year he found the lost Ceres, and from 1807 he directed the observatory in Göttingen for the rest of his life.", "Aynı yıl kayıp Ceres'i buldu ve 1807'den hayatının sonuna kadar Göttingen'deki gözlemevini yönetti."),
              ("He died in Göttingen on 23 February 1855.", "23 Şubat 1855'te Göttingen'de hayatını kaybetti.")),
        H("His contributions", "Katkıları"),
        P(("**Modular arithmetic**: the symbol ≡ that we use for congruences, as in 17 ≡ 2 (mod 5), comes from Gauss.", "**Modüler aritmetik**: 17 ≡ 2 (mod 5) örneğindeki gibi denklikler için kullandığımız ≡ sembolü Gauss'tan gelir."),
          ("He also proved the **law of quadratic reciprocity**, which he called the \"golden theorem\".", "Ayrıca \"altın teorem\" adını verdiği **ikinci dereceden karşılıklılık yasasını** ispatladı.")),
        P(("**The fundamental theorem of algebra**: in his doctoral thesis of 1799 he gave a proof that every polynomial equation has a root among the complex numbers.", "**Cebirin temel teoremi**: 1799'daki doktora tezinde her polinom denkleminin karmaşık sayılar arasında bir kökü olduğuna dair bir ispat verdi."),
          ("He returned to this theorem several times in his life and gave four different proofs.", "Hayatı boyunca bu teoreme birkaç kez geri döndü ve dört farklı ispat verdi.")),
        P(("**Geometry of surfaces**: while he was measuring the land of the Kingdom of Hanover, he thought deeply about curved surfaces.", "**Yüzeylerin geometrisi**: Hannover Krallığı'nın arazisini ölçerken eğri yüzeyler üzerine derinlemesine düşündü."),
          ("His Theorema Egregium, the \"remarkable theorem\" of 1827, says that the **curvature** of a surface can be measured from inside the surface.", "1827 tarihli Theorema Egregium, yani \"dikkate değer teorem\", bir yüzeyin **eğriliğinin** yüzeyin içinden ölçülebileceğini söyler."),
          ("This is why you cannot flatten an orange peel without tearing it, and why every flat map of the Earth is distorted.", "Bu yüzden bir portakal kabuğunu yırtmadan düzleştiremezsin ve Dünya'nın her düz haritası bozulmalıdır.")),
        P(("**Physics**: with Wilhelm Weber he studied the Earth's magnetism, and in 1833 they built an electromagnetic telegraph in Göttingen.", "**Fizik**: Wilhelm Weber ile birlikte Dünya'nın manyetizmasını inceledi ve 1833'te Göttingen'de elektromanyetik bir telgraf kurdular."),
          ("A unit of magnetic field, the gauss, is named after him.", "Bir manyetik alan birimi olan gauss, onun adını taşır.")),
        H("Few, but ripe", "Az ama olgun"),
        P(("Gauss's motto was \"Pauca sed matura\", which means \"few, but ripe\".", "Gauss'un düsturu \"Pauca sed matura\" idi, yani \"az ama olgun\"."),
          ("He published only the results he considered complete and perfect.", "Yalnızca tamamlanmış ve kusursuz bulduğu sonuçları yayımladı."),
          ("After his death, his notebooks showed that he had found some important ideas years before others published them.", "Ölümünden sonra defterleri, bazı önemli fikirleri başkaları yayımlamadan yıllar önce bulduğunu gösterdi."),
          ("His face and the bell curve once appeared together on the German 10-Deutsche-Mark banknote.", "Yüzü ve çan eğrisi bir zamanlar 10 Alman Markı'lık banknotta birlikte yer aldı.")),
        KUTU("sinif", "For the classroom", "Sınıf için",
             ("Show students Gauss's notation with a clock: 17 o'clock is 5 o'clock on a 12-hour clock, so 17 ≡ 5 (mod 12).", "Öğrencilere Gauss'un gösterimini bir saatle anlat: Saat 17, 12 saatlik kadranda saat 5'tir, yani 17 ≡ 5 (mod 12)."),
             ("Then ask: what day of the week will it be 100 days from today?", "Sonra sor: Bugünden 100 gün sonra haftanın hangi günü olacak?"),
             ("Since 100 ≡ 2 (mod 7), it will be two days later in the week than today.", "100 ≡ 2 (mod 7) olduğu için haftanın bugünden iki gün sonraki günü olacak.")),
        TERIMLER(("constructible polygon", "çizilebilir çokgen"), ("number theory", "sayılar teorisi"),
                 ("congruence", "denklik"), ("fundamental theorem of algebra", "cebirin temel teoremi"),
                 ("curvature", "eğrilik"), ("ripe", "olgun")),
    ),

    BOLUM("odul", "emoji_events", "#D4A017", "Prize Corner", "Ödüller Köşesi",
        H("Future Science Prize 2026: Xinyi Yuan", "Future Science Prize 2026: Xinyi Yuan"),
        P(("On 13 August 2026, the laureates of the Future Science Prize were announced in Beijing and Hong Kong.", "13 Ağustos 2026'da Future Science Prize sahipleri Pekin ve Hong Kong'da açıklandı."),
          ("This prize is often called \"China's Nobel Prize\", and each category is worth 1 million dollars.", "Bu ödül sıklıkla \"Çin'in Nobel'i\" olarak anılıyor ve her kategori 1 milyon dolar değerinde."),
          ("The Mathematics and Computer Science Prize went to **Xinyi Yuan** of Peking University.", "Matematik ve Bilgisayar Bilimi Ödülü, Pekin Üniversitesi'nden **Xinyi Yuan**'a verildi."),
          ("The prize recognises his fundamental contributions to **arithmetic geometry**.", "Ödül, onun **aritmetik geometriye** yaptığı temel katkıları onurlandırıyor."),
          ("In particular, it mentions his theory of \"arithmetic bigness\" in Arakelov geometry and its applications to the uniform Bogomolov and uniform Mordell conjectures.", "Özellikle Arakelov geometrisindeki \"aritmetik büyüklük\" teorisini ve bunun tek biçimli Bogomolov ve tek biçimli Mordell sanılarına uygulamalarını anıyor.")),
        KUTU("bilgi", "What is the Mordell conjecture?", "Mordell sanısı nedir?",
             ("Take an equation with two unknowns, such as y² = x⁵ + 1, and look for solutions where x and y are **rational numbers**.", "y² = x⁵ + 1 gibi iki bilinmeyenli bir denklem al ve x ile y'nin **rasyonel sayı** olduğu çözümleri ara."),
             ("In 1922 Louis Mordell guessed that \"complicated\" curves of this kind, those of **genus** at least 2, have only finitely many rational points.", "Louis Mordell 1922'de bu türden \"karmaşık\" eğrilerin, yani **cinsi** en az 2 olanların, yalnızca sonlu sayıda rasyonel noktası olduğunu tahmin etti."),
             ("Gerd Faltings proved this in 1983 and later won the Fields Medal.", "Gerd Faltings bunu 1983'te ispatladı ve sonra Fields Madalyası kazandı."),
             ("The \"uniform\" versions ask for more: an upper bound on the number of points.", "\"Tek biçimli\" versiyonlar daha fazlasını istiyor: Nokta sayısı için bir üst sınır."),
             ("This bound should not depend on each curve separately, but mainly on simple data such as its genus.", "Bu sınır her eğriye ayrı ayrı değil, esas olarak cinsi gibi basit verilere bağlı olmalı.")),
        H("Sylvester Medal 2026: Wendelin Werner", "Sylvester Madalyası 2026: Wendelin Werner"),
        P(("On 27 August 2026, the Royal Society in London announced its medals and awards for the year.", "27 Ağustos 2026'da Londra'daki Royal Society bu yılın madalya ve ödüllerini açıkladı."),
          ("The **Sylvester Medal**, given for the encouragement of mathematical research, went to **Wendelin Werner**.", "Matematik araştırmalarını teşvik için verilen **Sylvester Madalyası**, **Wendelin Werner**'e verildi."),
          ("The Royal Society recognised his instrumental role in developing the **Schramm–Loewner evolution** (SLE).", "Royal Society, onun **Schramm–Loewner evrimi** (SLE) teorisinin gelişimindeki belirleyici rolünü onurlandırdı."),
          ("Werner had already received the Fields Medal in 2006.", "Werner 2006'da Fields Madalyası'nı da almıştı.")),
        P(("SLE describes random curves in the plane.", "SLE, düzlemdeki rastgele eğrileri tanımlar."),
          ("Imagine water slowly soaking through a porous stone, or the border of a random cluster on a grid.", "Gözenekli bir taşın içinden yavaşça sızan suyu ya da bir ızgara üzerindeki rastgele bir kümenin sınırını düşün."),
          ("When the grid becomes very fine, these borders look like fractal curves, and SLE gives their exact laws.", "Izgara çok incelince bu sınırlar fraktal eğrilere benzer ve SLE onların tam yasalarını verir."),
          ("In 2001, Werner, Gregory Lawler and Oded Schramm used these ideas to study a random path in the plane called Brownian motion.", "2001'de Werner, Gregory Lawler ve Oded Schramm bu fikirleri kullanarak düzlemde Brown hareketi denen rastgele bir yolu incelediler."),
          ("They proved that its outer border has **fractal dimension** 4/3, as Benoit Mandelbrot had predicted.", "Bu yolun dış sınırının **fraktal boyutunun**, Benoit Mandelbrot'un tahmin ettiği gibi 4/3 olduğunu ispatladılar.")),
        KUTU("sinif", "High school link", "Lise bağlantısı",
             ("You can build a random cluster in class with **percolation**.", "Sınıfta **perkolasyon** ile rastgele bir küme kurabilirsiniz."),
             ("Draw a 10 × 10 grid and toss a coin for every square: colour it blue for heads and leave it white for tails.", "10 × 10'luk bir ızgara çizin ve her kare için yazı tura atın: Yazı gelirse kareyi maviye boyayın, tura gelirse beyaz bırakın."),
             ("Is there a path of blue squares, joined by their sides, from the top row to the bottom row?", "Kenarlarıyla birleşen mavi karelerden üst sıradan alt sıraya giden bir yol var mı?"),
             ("Compare the grids of the whole class and estimate the probability of such a path.", "Bütün sınıfın ızgaralarını karşılaştırın ve böyle bir yolun olasılığını tahmin edin."),
             ("The border of a blue cluster is exactly the kind of random curve that SLE describes.", "Mavi bir kümenin sınırı, tam da SLE'nin tanımladığı türden rastgele bir eğridir.")),
        TERIMLER(("upper bound", "üst sınır"), ("uniform", "tek biçimli"),
                 ("porous", "gözenekli"), ("percolation", "perkolasyon, süzülme"), ("random curve", "rastgele eğri")),
    ),

    BOLUM("dusun", "psychology", "#16A085", "Think Like a Mathematician: Pair It Up", "Matematikçi Gibi Düşünmek: Eşleştir",
        P(("According to a famous story, which may be partly legend, a teacher once wanted a quiet hour in class.", "Kısmen efsane olabilecek ünlü bir hikâyeye göre bir öğretmen bir gün sınıfta sessiz bir saat geçirmek istemiş."),
          ("He asked the pupils to add up all the whole numbers from 1 to 100, but young Gauss had the answer in a few moments.", "Öğrencilerden 1'den 100'e kadar bütün tam sayıları toplamalarını istemiş, ama küçük Gauss cevabı birkaç dakikada bulmuş."),
          ("As we saw in our May issue, he paired 1 with 100, 2 with 99 and so on, and every pair gave 101.", "Mayıs sayımızda gördüğümüz gibi 1'i 100'le, 2'yi 99'la eşleştirmiş ve her çift 101 etmiş."),
          ("This month we turn his trick into a strategy: **pair things up** so that every pair looks the same.", "Bu ay onun hilesini bir stratejiye dönüştürüyoruz: **Şeyleri eşleştir**, öyle ki her çift aynı görünsün.")),
        KUTU("soru", "The problem: a thousand numbers", "Problem: Bin sayı",
             ("Write down all the whole numbers from 0 to 999.", "0'dan 999'a kadar bütün tam sayıları yaz."),
             ("What is the sum of all the **digits** you wrote?", "Yazdığın bütün **rakamların** toplamı kaçtır?")),
        H("The solution", "Çözüm"),
        LISTE(("Adding about 2,900 digits one by one would take hours, so we pair the numbers instead.", "Yaklaşık 2.900 rakamı tek tek toplamak saatler sürer, bu yüzden onun yerine sayıları eşleştiriyoruz."),
              ("Pair each number n with 999 − n: 0 with 999, 1 with 998, 123 with 876, and so on.", "Her n sayısını 999 − n ile eşleştir: 0'ı 999'la, 1'i 998'le, 123'ü 876'yla ve bu şekilde devam et."),
              ("In every pair, the digits in each place add up to 9, because subtracting from 999 never needs borrowing.", "Her çiftte her basamaktaki rakamların toplamı 9'dur, çünkü 999'dan çıkarma yaparken hiç onluk bozmak gerekmez."),
              ("So the digits of each pair add up to 9 + 9 + 9 = 27.", "Yani her çiftin rakamları toplamı 9 + 9 + 9 = 27 eder."),
              ("There are 1000 numbers, so there are 500 pairs, and the total is 500 × 27 = 13,500.", "1000 sayı var, yani 500 çift var ve toplam 500 × 27 = 13.500.")),
        P(("The same idea gives Gauss's formula for any n.", "Aynı fikir her n için Gauss'un formülünü verir."),
          ("The first and the last term, the second and the second-to-last term, and so on, always have the same sum n + 1.", "İlk ve son terim, ikinci ve sondan ikinci terim ve diğerleri her zaman aynı n + 1 toplamını verir.")),
        FORMUL("1 + 2 + … + n = n(n + 1) / 2"),
        P(("For example, 1 + 2 + … + 2026 = 2026 × 2027 / 2 = 2,053,351.", "Örneğin 1 + 2 + … + 2026 = 2026 × 2027 / 2 = 2.053.351."),
          ("The trick works for every **arithmetic series**, where the difference between neighbouring terms is constant.", "Hile, ardışık terimler arasındaki farkın sabit olduğu her **aritmetik seri** için geçerlidir."),
          ("The sum is always the number of terms times the average of the first and the last term.", "Toplam her zaman terim sayısı çarpı ilk ve son terimin ortalamasıdır.")),
        KUTU("ipucu", "The lesson", "Ders",
             ("When a calculation looks long, look for **symmetry**.", "Bir hesap uzun göründüğünde **simetri** ara."),
             ("If you can group the pieces so that every group is the same, a long sum becomes a single multiplication.", "Parçaları her grup aynı olacak şekilde gruplayabiliyorsan uzun bir toplam tek bir çarpmaya dönüşür."),
             ("Pairing also works when you want to count things, not only when you want to add them, as the next problem shows.", "Bir sonraki problemin gösterdiği gibi eşleştirme yalnızca toplarken değil, sayarken de işe yarar.")),
        KUTU("soru", "Your turn", "Senin sıran",
             ("Show that 40 has an even number of **divisors** but 36 has an odd number.", "40'ın çift sayıda, 36'nın ise tek sayıda **böleni** olduğunu göster."),
             ("Which whole numbers have an odd number of divisors?", "Hangi tam sayıların tek sayıda böleni vardır?")),
        KUTU("ipucu", "Answer", "Cevap",
             ("Pair each divisor d of a number n with n/d.", "n sayısının her d bölenini n/d ile eşleştir."),
             ("For 40, the pairs are 1 and 40, 2 and 20, 4 and 10, 5 and 8, so there are 8 divisors.", "40 için çiftler 1 ile 40, 2 ile 20, 4 ile 10, 5 ile 8, yani 8 bölen var."),
             ("For 36, we get 1 and 36, 2 and 18, 3 and 12, 4 and 9, but 6 is paired with itself, so there are 9 divisors.", "36 için 1 ile 36, 2 ile 18, 3 ile 12, 4 ile 9 çiftleri çıkar, ama 6 kendisiyle eşleşir, yani 9 bölen var."),
             ("A divisor can be its own partner only when d · d = n, so exactly the **perfect squares** have an odd number of divisors.", "Bir bölen ancak d · d = n olduğunda kendi eşi olabilir, yani tek sayıda böleni olanlar tam olarak **tam karelerdir**.")),
        TERIMLER(("to pair up", "eşleştirmek"), ("arithmetic series", "aritmetik seri"), ("partner", "eş"),
                 ("borrowing (in subtraction)", "onluk bozma"), ("number of terms", "terim sayısı")),
    ),

    BOLUM("eglence", "lightbulb", "#E84393", "Fun Facts: August, 8 and Summer", "Eğlenceli Bilgiler: Ağustos, 8 ve Yaz",
        LISTE(("**A month named after an emperor**: the Romans called this month Sextilis, the sixth month, and in 8 BC it was renamed in honour of Emperor Augustus.", "**Adını bir imparatordan alan ay**: Romalılar bu aya altıncı ay anlamında Sextilis diyordu ve MÖ 8'de İmparator Augustus'un onuruna adı değiştirildi."),
              ("A popular story says that Augustus took a day from February so that his month would be as long as July.", "Popüler bir hikâyeye göre Augustus, kendi ayı temmuz kadar uzun olsun diye şubattan bir gün almış."),
              ("Historians think this is a **myth**, which appears for the first time in the Middle Ages.", "Tarihçiler bunun ilk kez Orta Çağ'da ortaya çıkan bir **efsane** olduğunu düşünüyor."),
              ("**The number 8**: it is a **cube**, 8 = 2³, and it is also a Fibonacci number.", "**8 sayısı**: Bir **küptür**, 8 = 2³, ve aynı zamanda bir Fibonacci sayısıdır."),
              ("In 2006 mathematicians proved that the only perfect powers in the Fibonacci sequence are 0, 1, 8 and 144.", "2006'da matematikçiler Fibonacci dizisindeki tam kuvvetlerin yalnızca 0, 1, 8 ve 144 olduğunu ispatladı."),
              ("**Infinity on its side**: the symbol ∞ looks like a lying 8, and John Wallis introduced it in 1655.", "**Yan yatmış sonsuz**: ∞ sembolü yan yatmış bir 8'e benzer ve onu 1655'te John Wallis kullanmaya başladı."),
              ("**Sunflowers**: the seeds of a sunflower form two families of spirals, and the numbers of spirals are usually neighbouring Fibonacci numbers, such as 34 and 55.", "**Ayçiçekleri**: Ayçiçeğinin tohumları iki spiral ailesi oluşturur ve spiral sayıları genellikle 34 ve 55 gibi ardışık Fibonacci sayılarıdır."),
              ("**Rainbows**: a rainbow always appears about 42° away from the point directly opposite the Sun, an angle that René Descartes calculated in 1637.", "**Gökkuşakları**: Gökkuşağı her zaman Güneş'in tam karşısındaki noktadan yaklaşık 42° uzakta görünür ve bu açıyı René Descartes 1637'de hesapladı."),
              ("So from the ground you can only see a rainbow when the Sun is lower than 42° in the sky, which in summer means the morning or the late afternoon.", "Bu yüzden yerden gökkuşağını yalnızca Güneş gökyüzünde 42°'den alçaktayken görebilirsin, bu da yazın sabah ya da öğleden sonra geç saatler demektir."),
              ("**Prime cicadas**: some cicadas in North America come out of the ground only every 13 or 17 years, and both numbers are **prime**.", "**Asal ağustosböcekleri**: Kuzey Amerika'daki bazı ağustosböcekleri topraktan yalnızca 13 ya da 17 yılda bir çıkar ve iki sayı da **asaldır**."),
              ("One popular explanation is that a prime cycle rarely lines up with the cycles of their enemies.", "Popüler bir açıklamaya göre asal bir döngü, düşmanlarının döngüleriyle nadiren çakışır.")),
        TERIMLER(("myth", "efsane, yanlış inanış"), ("perfect power", "tam kuvvet"), ("spiral", "sarmal, spiral"),
                 ("rainbow", "gökkuşağı"), ("cicada", "ağustosböceği")),
    ),

    BOLUM("sinif", "school", "#27AE60", "In the Classroom", "Sınıfta Matematik",
        H("Grades 6–8: A pocket-sized Solar System", "6-8. sınıflar: Cep boyu Güneş Sistemi"),
        P(("Goal: ratio and proportion, scale, and working with large numbers.", "Hedef: Oran-orantı, ölçek ve büyük sayılarla çalışma."),
          ("Give students these rounded values.", "Öğrencilere şu yuvarlanmış değerleri verin.")),
        TABLO(["Object / Cisim", "Diameter / Çap", "Distance from Earth / Dünya'ya uzaklık"],
              ["Moon / Ay", "3,500 km", "384,000 km"],
              ["Sun / Güneş", "1,400,000 km", "150,000,000 km"]),
        LISTE(("First, find how many times wider the Sun is than the Moon, and how many times farther away it is.", "Önce Güneş'in Ay'dan kaç kat geniş ve kaç kat uzak olduğunu bulun."),
              ("Both answers are close to 400, so they look the same size in the sky.", "İki cevap da 400'e yakın, bu yüzden gökyüzünde aynı büyüklükte görünürler."),
              ("Now build a model: if the Moon is a 1 cm bead, the Sun must be a ball about 4 m wide.", "Şimdi bir model kurun: Ay 1 cm'lik bir boncuksa, Güneş yaklaşık 4 m genişliğinde bir top olmalı."),
              ("In the same **scale**, the Moon is about 1.1 m from the Earth, and the Sun is more than 400 m away.", "Aynı **ölçekte** Ay, Dünya'dan yaklaşık 1,1 m, Güneş ise 400 m'den fazla uzakta olur."),
              ("Go to the school yard and measure these distances with steps.", "Okul bahçesine çıkın ve bu uzaklıkları adımlarla ölçün.")),
        KUTU("sinif", "Bonus question", "Bonus soru",
             ("Hold a 1 cm bead with your arm straight out: can it cover the full Moon?", "Kolunu düz uzatıp 1 cm'lik bir boncuk tut: Dolunayı kapatabilir mi?"),
             ("Yes, easily, because at that distance the Moon looks only about half a centimetre wide.", "Evet, kolayca, çünkü o uzaklıkta Ay yalnızca yaklaşık yarım santimetre genişliğinde görünür."),
             ("This activity practises proportional reasoning and estimation, two skills that the Maarif model puts in the centre.", "Bu etkinlik, Maarif modelinin merkeze koyduğu iki beceri olan orantısal akıl yürütmeyi ve tahmin etmeyi çalıştırıyor.")),
        H("High school: Fit a line like Gauss", "Lise: Gauss gibi doğru uydur"),
        P(("A lemonade stand sells cups on five summer days.", "Bir limonata standı beş yaz gününde bardak satıyor."),
          ("Let x be the day number and y the number of cups in tens: (1, 2), (2, 3), (3, 5), (4, 4) and (5, 6).", "x gün numarası, y de onlar cinsinden bardak sayısı olsun: (1, 2), (2, 3), (3, 5), (4, 4) ve (5, 6)."),
          ("Students fill in a table with the columns x, y, x² and xy, and add each column.", "Öğrenciler x, y, x² ve xy sütunlarından oluşan bir tablo doldurup her sütunu toplasın.")),
        FORMUL("Σx = 15,  Σy = 20,  Σx² = 55,  Σxy = 69"),
        P(("Put these sums into the normal equations from our paper of the month.", "Bu toplamları ayın makalesindeki normal denklemlere yerleştirin."),),
        FORMUL("5a + 15b = 20   and   15a + 55b = 69"),
        P(("The solution is b = 0.9 and a = 1.3, so the best line is y = 1.3 + 0.9x.", "Çözüm b = 0,9 ve a = 1,3, yani en iyi doğru y = 1,3 + 0,9x."),
          ("Check: the line passes through the point of means, (3, 4).", "Kontrol: Doğru, ortalamalar noktası olan (3, 4)'ten geçer."),
          ("Finally, students enter the same data into a spreadsheet and compare their line with the program's trend line.", "Son olarak öğrenciler aynı verileri bir hesap tablosuna girip kendi doğrularını programın eğilim çizgisiyle karşılaştırsın.")),
        KUTU("soru", "Discussion questions", "Tartışma soruları",
             ("What does the line predict for day 6, and how much should we trust it?", "Doğru 6. gün için ne öngörüyor ve ona ne kadar güvenmeliyiz?"),
             ("Calculate the five residuals: what is their sum?", "Beş artığı hesaplayın: Toplamları kaç?"),
             ("Hint: for a least squares line with a constant term, the residuals always add up to zero.", "İpucu: Sabit terimi olan bir en küçük kareler doğrusunda artıkların toplamı her zaman sıfırdır.")),
        TERIMLER(("scale model", "ölçekli model"), ("ratio", "oran"), ("estimation", "tahmin"),
                 ("trend line", "eğilim çizgisi"), ("point of means", "ortalamalar noktası")),
    ),

    BOLUM("gundem", "campaign", "#C0392B", "Education in Türkiye", "Eğitim Gündemi",
        H("LGS placement results", "LGS yerleştirme sonuçları"),
        P(("The Ministry of National Education announced the 2026 LGS placement results on 5 August.", "Millî Eğitim Bakanlığı 2026 LGS yerleştirme sonuçlarını 5 Ağustos'ta açıkladı."),
          ("Exam-based schools offered 198,905 places, and 190,473 of them were filled, a **placement rate** of 95.76%.", "Sınavla öğrenci alan okullar 198.905 kontenjan sundu ve bunların 190.473'ü doldu, yani **yerleşme oranı** %95,76 oldu."),
          ("89.84% of students in central placement got one of their first five choices.", "Merkezî yerleştirmedeki öğrencilerin %89,84'ü ilk beş tercihinden birine yerleşti."),
          ("Two rounds of **transfers** followed, with results on 10 and 14 August.", "Ardından iki **nakil** dönemi yapıldı, sonuçlar 10 ve 14 Ağustos'ta açıklandı.")),
        KUTU("sinif", "A percentage question for grade 8", "8. sınıf için yüzde sorusu",
             ("Ask your students to check the rate themselves: 190,473 ÷ 198,905 ≈ 0.9576.", "Öğrencilerinizden oranı kendilerinin kontrol etmesini isteyin: 190.473 ÷ 198.905 ≈ 0,9576."),
             ("Then ask: how many places were left empty?", "Sonra sorun: Kaç kontenjan boş kaldı?"),
             ("The answer is 8,432.", "Cevap 8.432.")),
        H("YKS placement results", "YKS yerleştirme sonuçları"),
        LISTE(("ÖSYM announced the 2026 YKS placement results on 18 August.", "ÖSYM 2026 YKS yerleştirme sonuçlarını 18 Ağustos'ta açıkladı."),
              ("Placement scores were calculated for 2,187,747 candidates, and 1,279,439 candidates applied for placement.", "2.187.747 adayın yerleştirme puanı hesaplandı ve 1.279.439 aday yerleştirmeye başvurdu."),
              ("In total, 730,854 candidates were placed in a programme.", "Toplam 730.854 aday bir programa yerleşti."),
              ("In state universities' formal programmes, 479,392 of the 481,684 places were filled, an **occupancy rate** of 99.52%.", "Devlet üniversitelerinin örgün programlarında 481.684 kontenjanın 479.392'si doldu, yani **doluluk oranı** %99,52 oldu."),
              ("University **registration** took place from 24 to 28 August.", "Üniversite **kayıtları** 24-28 Ağustos tarihlerinde yapıldı.")),
        H("Getting ready for the new school year", "Yeni eğitim yılına hazırlık"),
        P(("According to the ministry's 2026–2027 calendar, teachers start their professional work on 1 September.", "Bakanlığın 2026-2027 çalışma takvimine göre öğretmenler mesleki çalışmalarına 1 Eylül'de başlıyor."),
          ("The adjustment week for preschool and grade 1 pupils is 7–11 September, and lessons start on Monday, 14 September 2026.", "Okul öncesi ve 1. sınıf öğrencileri için uyum haftası 7-11 Eylül'de, dersler ise 14 Eylül 2026 Pazartesi günü başlıyor."),
          ("The first mid-term break is on 16–20 November.", "Birinci ara tatil 16-20 Kasım'da.")),
        KUTU("ipucu", "A tip for the first week", "İlk hafta için bir öneri",
             ("Start the year with a short \"summer maths\" lesson: the eclipse, the Perseids or the lemonade line in this issue.", "Yıla kısa bir \"yaz matematiği\" dersiyle başlayın: Bu sayıdaki tutulma, Perseidler ya da limonata doğrusu."),
             ("A story from real life is the best way to wake up minds after a long holiday.", "Uzun bir tatilden sonra zihinleri uyandırmanın en iyi yolu gerçek hayattan bir hikâyedir.")),
        TERIMLER(("placement rate", "yerleşme oranı"), ("percentage", "yüzde"), ("occupancy rate", "doluluk oranı"),
                 ("state university", "devlet üniversitesi"), ("mid-term break", "ara tatil")),
    ),

    BOLUM("oku", "menu_book", "#34495E", "Read Like a Mathematician", "Matematikçi Gibi Oku",
        P(("This month we look at the language of **estimates** and **approximations**.", "Bu ay **tahminlerin** ve **yaklaşık değerlerin** diline bakıyoruz."),
          ("Real data is never perfect, so mathematicians need words that say \"almost\" in a precise way.", "Gerçek veri hiçbir zaman kusursuz değildir, bu yüzden matematikçilerin \"neredeyse\" demenin kesin yollarına ihtiyacı var.")),
        TABLO(["English", "Türkçe", "Note / Not"],
              ["approximately equal to (≈)", "yaklaşık olarak eşittir", "T ≈ 4.6 years / T ≈ 4,6 yıl"],
              ["is proportional to (∝)", "… ile orantılıdır", "T² ∝ a³"],
              ["to minimise / to maximise", "en küçük / en büyük yapmak", "minimise the sum of squares / kareler toplamını en küçük yap"],
              ["the best fit", "en iyi uyum", "the line that fits the data best / veriye en iyi uyan doğru"],
              ["on average", "ortalamada", "used with means / ortalamalarla kullanılır"],
              ["up to an error of …", "… hata payıyla", "states how accurate a value is / değerin ne kadar doğru olduğunu söyler"],
              ["is never negative", "hiçbir zaman negatif değildir", "typical for squares / kareler için tipiktir"],
              ["term by term", "terim terim", "adding or comparing two sums / iki toplamı toplarken ya da karşılaştırırken"]),
        KUTU("soru", "Mini reading: why the mean is the best fit", "Mini okuma: Ortalama neden en iyi uyumdur?",
             ("Theorem: Let x̄ be the mean of x₁, …, xₙ. Then for every number c, Σ (xᵢ − c)² ≥ Σ (xᵢ − x̄)².", "Teorem: x̄, x₁, …, xₙ sayılarının ortalaması olsun. O zaman her c sayısı için Σ (xᵢ − c)² ≥ Σ (xᵢ − x̄)²."),
             ("Proof: Write xᵢ − c = (xᵢ − x̄) + (x̄ − c), square both sides and add term by term.", "İspat: xᵢ − c = (xᵢ − x̄) + (x̄ − c) yaz, iki tarafın karesini al ve terim terim topla."),
             ("The middle sum is 2(x̄ − c) · Σ (xᵢ − x̄), which equals zero, because the residuals from the mean add up to zero.", "Ortadaki toplam 2(x̄ − c) · Σ (xᵢ − x̄) olur ve bu sıfıra eşittir, çünkü ortalamaya göre artıkların toplamı sıfırdır."),
             ("Hence Σ (xᵢ − c)² = Σ (xᵢ − x̄)² + n(x̄ − c)².", "Dolayısıyla Σ (xᵢ − c)² = Σ (xᵢ − x̄)² + n(x̄ − c)²."),
             ("The last term is never negative, and it is zero only when c = x̄. ∎", "Son terim hiçbir zaman negatif değildir ve yalnızca c = x̄ olduğunda sıfırdır. ∎")),
        KUTU("ipucu", "A small note", "Küçük not",
             ("Notice the difference between \"≈\" and \"=\".", "\"≈\" ile \"=\" arasındaki farka dikkat et."),
             ("The proof above gives an exact result without any derivatives, but the orbit of Ceres in the Science Corner is only approximate.", "Yukarıdaki ispat hiç türev kullanmadan kesin bir sonuç veriyor, ama Bilim Köşesi'ndeki Ceres yörüngesi yalnızca yaklaşık."),
             ("Good mathematical writing always tells the reader which one it means.", "İyi matematik yazımı okura hangisini kastettiğini her zaman söyler.")),
        TERIMLER(("to minimise", "en küçük yapmak"), ("approximation", "yaklaşık değer"), ("proportional", "orantılı"),
                 ("best fit", "en iyi uyum"), ("term by term", "terim terim")),
    ),
]

quiz = [
    SORU("What did OpenAI announce about its Astra model on 1 August 2026?", "OpenAI 1 Ağustos 2026'da Astra modeli hakkında ne duyurdu?",
         ["It produced new results on 10 long-open problems", "It won the Fields Medal", "It solved every Erdős problem", "It replaced peer review"], 0,
         "OpenAI said that Astra produced new results on 10 problems that had been open for at least a decade, and the proofs came with Lean certificates.", "OpenAI, Astra'nın en az on yıldır açık olan 10 problemde yeni sonuçlar ürettiğini söyledi ve ispatlar Lean sertifikalarıyla birlikte geldi."),
    SORU("Who first spotted Ceres on 1 January 1801?", "Ceres'i 1 Ocak 1801'de ilk kim gördü?",
         ["Gauss", "Giuseppe Piazzi", "Kepler", "Franz Xaver von Zach"], 1,
         "Piazzi discovered it in Palermo, Gauss calculated its orbit, and von Zach found it again on 31 December 1801.", "Piazzi onu Palermo'da keşfetti, Gauss yörüngesini hesapladı, von Zach ise 31 Aralık 1801'de yeniden buldu."),
    SORU("Which value minimises the sum of squares Σ (xᵢ − c)²?", "Σ (xᵢ − c)² kareler toplamını hangi değer en küçük yapar?",
         ["The median", "The largest value", "Zero", "The arithmetic mean"], 3,
         "Setting the derivative −2 · Σ (xᵢ − c) equal to zero gives c = the arithmetic mean.", "−2 · Σ (xᵢ − c) türevini sıfıra eşitlemek c = aritmetik ortalama sonucunu verir."),
    SORU("Which of these numbers has an odd number of divisors?", "Bu sayılardan hangisinin tek sayıda böleni vardır?",
         ["40", "30", "36", "50"], 2,
         "Divisors come in pairs d and n/d, and only a perfect square like 36 = 6 × 6 has a divisor that is paired with itself.", "Bölenler d ve n/d çiftleri hâlinde gelir ve yalnızca 36 = 6 × 6 gibi bir tam karenin kendisiyle eşleşen bir böleni vardır."),
    SORU("Why do the Perseids appear every August?", "Perseidler neden her ağustos görülür?",
         ["The Earth crosses a comet's dust stream at the same point of its orbit", "The Moon is closest to the Earth", "Jupiter pulls meteors towards us", "The Sun is most active in summer"], 0,
         "The Earth meets the dust of comet 109P/Swift–Tuttle at the same place in its orbit every year.", "Dünya, 109P/Swift–Tuttle kuyrukluyıldızının tozuyla her yıl yörüngesinin aynı yerinde karşılaşır."),
    SORU("Which prize did Wendelin Werner receive in August 2026?", "Wendelin Werner Ağustos 2026'da hangi ödülü aldı?",
         ["The Future Science Prize", "The Royal Society's Sylvester Medal", "The Abel Prize", "The Nobel Prize in Physics"], 1,
         "The Royal Society announced on 27 August 2026 that Werner received the Sylvester Medal for his work on the Schramm–Loewner evolution.", "Royal Society 27 Ağustos 2026'da Werner'in Schramm–Loewner evrimi üzerine çalışmaları için Sylvester Madalyası'nı aldığını açıkladı."),
]

bulmacalar = [
    ANAGRAM("TOMEC", "COMET", "109P/Swift–Tuttle is one, and its dust gives us the Perseids.", "109P/Swift–Tuttle bunlardan biridir ve tozu bize Perseidleri getirir."),
    ANAGRAM("SPILECE", "ECLIPSE", "When the Moon hides the Sun.", "Ay'ın Güneş'i gizlemesi."),
    ANAGRAM("TOREME", "METEOR", "A shooting star in the night sky.", "Gece gökyüzünde kayan bir yıldız."),
    ANAGRAM("RORRE", "ERROR", "Every measurement has a small one.", "Her ölçümde küçük bir tane vardır."),
    ESLESTIR("Match the terms", "Terimleri eşleştir",
             ("least squares", "en küçük kareler"), ("dwarf planet", "cüce gezegen"), ("meteor shower", "meteor yağmuru"),
             ("arithmetic series", "aritmetik seri"), ("standard deviation", "standart sapma")),
    MANTIK("The knockout tournament", "Eleme turnuvası",
           "100 players enter a knockout table tennis tournament. In each match one player is knocked out, and when a round has an odd number of players, one of them goes to the next round without playing. How many matches are played in total?",
           "Bir masa tenisi eleme turnuvasına 100 oyuncu katılıyor. Her maçta bir oyuncu eleniyor ve bir turda tek sayıda oyuncu varsa biri oynamadan bir sonraki tura geçiyor. Toplam kaç maç oynanır?",
           "99 matches. Do not follow the rounds. Instead, pair every match with the player who loses it. Each match has exactly one loser, and every player except the champion loses exactly once. So there are as many matches as losers: 100 − 1 = 99.",
           "99 maç. Turları takip etme. Onun yerine her maçı, o maçı kaybeden oyuncuyla eşleştir. Her maçın tam bir kaybedeni var ve şampiyon dışındaki her oyuncu tam bir kez kaybediyor. Yani maç sayısı kaybeden sayısına eşit: 100 − 1 = 99."),
    MANTIK("The wandering eclipse", "Gezgin tutulma",
           "Eclipses in the same Saros series repeat after about 6585 days and 8 hours. The eclipse of 12 August 2026 belongs to Saros 126. Why will the next eclipse of this series not be seen from the same places?",
           "Aynı Saros serisindeki tutulmalar yaklaşık 6585 gün 8 saat sonra tekrar eder. 12 Ağustos 2026 tutulması Saros 126 serisine ait. Bu serinin bir sonraki tutulması neden aynı yerlerden görülmeyecek?",
           "The extra 8 hours are one third of a day. During those 8 hours the Earth turns one third of a full turn, which is 120°. So the shadow falls about 120° of longitude farther west. The next eclipse of Saros 126, on 23 August 2044, will be seen from North America instead of Europe.",
           "Fazladan 8 saat bir günün üçte biridir. Bu 8 saatte Dünya tam bir turun üçte biri, yani 120° döner. Bu yüzden gölge yaklaşık 120° boylam daha batıya düşer. Saros 126'nın bir sonraki tutulması, 23 Ağustos 2044'te, Avrupa yerine Kuzey Amerika'dan görülecek."),
]

SAYI_VERI = SAYI(
    8, "Ağustos 2026", "August 2026", "Gündelik hayatta ve doğada matematik", "Maths in everyday life and nature",
    {"renkler": ["#2F6690", "#1D4560"], "desen": 3},
    bolumler, quiz, bulmacalar,
    ad="The Lost Planet", ad_tr="Kayıp Gezegen",
)
