from dergi import *

bolumler = [
    BOLUM("editor", "edit_note", "#6C63FF", "Editor's Note", "Editörden",
        P(("Hello, and welcome to our October issue.", "Merhaba, ekim sayımıza hoş geldin."),
          ("Autumn has arrived, the first term is in full swing and the first exams are already on the calendar.", "Sonbahar geldi, birinci dönem tüm hızıyla sürüyor ve ilk sınavlar şimdiden takvimde yerini aldı."),
          ("On 29 October we will celebrate the 103rd anniversary of our Republic.", "29 Ekim'de Cumhuriyetimizin 103. yılını kutlayacağız."),
          ("Happy Republic Day to all our readers in advance!", "Tüm okurlarımızın Cumhuriyet Bayramı şimdiden kutlu olsun!")),
        P(("The theme of this month is **hidden symmetries**.", "Bu ayın teması **gizli simetriler**."),
          ("Our mathematician of the month, Évariste Galois, was born on 25 October 1811.", "Ayın matematikçisi Évariste Galois 25 Ekim 1811'de doğdu."),
          ("He discovered that the roots of an equation have hidden symmetries, and that these symmetries decide whether a formula for the roots can exist.", "Bir denklemin köklerinin gizli simetrileri olduğunu ve bu simetrilerin kökler için bir formülün var olup olamayacağına karar verdiğini keşfetti."),
          ("He did all this before he was 21.", "Bütün bunları 21 yaşına gelmeden yaptı.")),
        P(("Symmetry was in the news this month, too.", "Simetri bu ay haberlerde de vardı."),
          ("The 2026 Nobel Prize in Chemistry went to two chemists who studied molecules that are **mirror images** of each other.", "2026 Nobel Kimya Ödülü, birbirinin **ayna görüntüsü** olan molekülleri inceleyen iki kimyacıya verildi."),
          ("And in the world of AI, mathematicians had a very busy month.", "Yapay zekâ dünyasında ise matematikçiler çok yoğun bir ay geçirdi."),
          ("Enjoy your break!", "İyi molalar!")),
    ),

    BOLUM("haber", "newspaper", "#2E86DE", "News from the World of Maths", "Matematik Dünyasından Haberler",
        H("OpenAI shares 722 maths papers that it says an unreleased AI model wrote", "OpenAI, henüz yayımlanmamış bir yapay zekâ modelinin yazdığını söylediği 722 matematik makalesini paylaştı"),
        P(("On 6 October 2026, OpenAI put 722 mathematical **manuscripts** in a public GitHub repository.", "6 Ekim 2026'da OpenAI, 722 matematik **makale taslağını** herkese açık bir GitHub deposuna koydu."),
          ("According to the company, they were all produced by an internal model that the public cannot use yet.", "Şirkete göre bunların hepsi, kamuoyunun henüz kullanamadığı şirket içi bir model tarafından üretildi."),
          ("The manuscripts are grouped into 372 families of results and cover many areas of mathematics.", "Taslaklar 372 sonuç ailesine ayrılmış durumda ve matematiğin birçok alanını kapsıyor."),
          ("Among them are results on the zeros of the **Riemann zeta function**, on how well π can be approximated by fractions and on equations from physics.", "Aralarında **Riemann zeta fonksiyonunun** sıfırları, π'ye kesirlerle ne kadar iyi yaklaşılabileceği ve fizikten gelen denklemler üzerine sonuçlar var.")),
        P(("A month earlier, on 8 September, OpenAI had made an even bigger claim.", "Bir ay önce, 8 Eylül'de, OpenAI çok daha büyük bir iddiada bulunmuştu."),
          ("It said that one of its internal models had settled the **Navier–Stokes problem**, one of the seven Millennium Prize Problems of the Clay Mathematics Institute.", "Şirket içi modellerinden birinin, Clay Matematik Enstitüsü'nün yedi Milenyum Ödülü Probleminden biri olan **Navier–Stokes problemini** çözdüğünü söyledi."),
          ("According to OpenAI, a fluid that starts out smooth can develop a **singularity**, a point where the solution breaks down.", "OpenAI'a göre başlangıçta düzgün olan bir akışkanda bir **tekillik**, yani çözümün bozulduğu bir nokta oluşabiliyor."),
          ("In the claimed example, a carefully chosen outside force keeps pushing the fluid, which the official problem statement allows.", "İddia edilen örnekte özenle seçilmiş bir dış kuvvet akışkanı itmeye devam ediyor ve resmî problem metni buna izin veriyor."),
          ("The company said that about 10,000 AI agents worked on it for about 88 hours, and that it does not intend to claim the one-million-dollar prize.", "Şirket, yaklaşık 10.000 yapay zekâ ajanının bunun üzerinde yaklaşık 88 saat çalıştığını ve bir milyon dolarlık ödülü talep etmeyi düşünmediğini söyledi.")),
        H("Is it all true?", "Hepsi doğru mu?"),
        LISTE(("Many of the proofs come with **Lean** files, so a computer can check every step.", "İspatların çoğu **Lean** dosyalarıyla geliyor, yani bir bilgisayar her adımı kontrol edebiliyor."),
              ("But Lean only checks that the steps follow from the formal statement.", "Ama Lean yalnızca adımların biçimsel ifadeden çıktığını kontrol ediyor."),
              ("Whether the formal statement really says the same thing as the original problem is human work, and for Navier–Stokes this check is still going on.", "Biçimsel ifadenin gerçekten orijinal problemle aynı şeyi söyleyip söylemediği ise insan işi ve Navier–Stokes için bu kontrol hâlâ sürüyor."),
              ("None of the results has been peer reviewed yet, and some manuscripts have no Lean files at all.", "Sonuçların hiçbiri henüz hakem değerlendirmesinden geçmedi ve bazı taslakların hiç Lean dosyası yok."),
              ("Until other mathematicians have checked them in detail, they should be treated as **unverified** claims.", "Diğer matematikçiler onları ayrıntılı biçimde kontrol edene kadar **doğrulanmamış** iddialar olarak görülmeliler.")),
        H("An advisory group of mathematicians", "Matematikçilerden bir danışma grubu"),
        P(("On 21 September, OpenAI announced an independent **Advisory Group on Mathematics and Artificial Intelligence** (AGMAI) with nine leading mathematicians.", "21 Eylül'de OpenAI, dokuz önde gelen matematikçiden oluşan bağımsız bir **Matematik ve Yapay Zekâ Danışma Grubu** (AGMAI) kurulduğunu duyurdu."),
          ("The group is hosted by the Institute for Advanced Study in Princeton, and its members include Timothy Gowers, Martin Hairer and Edward Witten.", "Grubun ev sahibi Princeton'daki İleri Araştırmalar Enstitüsü ve üyeleri arasında Timothy Gowers, Martin Hairer ve Edward Witten var."),
          ("Its members are not paid, and the institute says that the group has no power to make decisions at any AI company.", "Üyeler ücret almıyor ve enstitü, grubun hiçbir yapay zekâ şirketinde karar verme yetkisi olmadığını söylüyor."),
          ("In its guidelines of 29 September, it asked AI labs to publish the prompts, the time taken and the estimated computing cost for every result.", "29 Eylül tarihli yönergelerinde yapay zekâ laboratuvarlarından her sonuç için istemleri, harcanan zamanı ve tahmini hesaplama maliyetini yayımlamalarını istedi."),
          ("It also asked them to share results in places that no AI lab controls, and not to use them for marketing.", "Ayrıca sonuçları hiçbir yapay zekâ laboratuvarının kontrol etmediği yerlerde paylaşmalarını ve onları reklam için kullanmamalarını istedi.")),
        KUTU("sinif", "For the classroom", "Sınıf için",
             ("This story is a good way to talk about what a proof really is.", "Bu hikâye, ispatın gerçekte ne olduğu hakkında konuşmak için iyi bir fırsat."),
             ("Ask your students: if a machine checks every step, but the first sentence of the problem is copied wrongly, is the proof correct?", "Öğrencilerine sor: Bir makine her adımı kontrol ediyor, ama problemin ilk cümlesi yanlış kopyalanmışsa ispat doğru mudur?")),
        TERIMLER(("manuscript", "makale taslağı"), ("outside force", "dış kuvvet"), ("repository", "depo"),
                 ("formal statement", "biçimsel ifade"), ("unverified", "doğrulanmamış"), ("advisory group", "danışma grubu")),
    ),

    BOLUM("makale", "article", "#8E44AD", "Paper of the Month: Why There Is No Formula for the Quintic", "Ayın Makalesi: Beşinci Dereceden Denklemin Neden Formülü Yok?",
        KUTU("bilgi", "Source", "Kaynak",
             ("É. Galois, Mémoire sur les conditions de résolubilité des équations par radicaux, written in 1830–1831, published by Joseph Liouville in the Journal de Mathématiques Pures et Appliquées, 1846.", "É. Galois, Denklemlerin Kökler Yardımıyla Çözülebilmesinin Koşulları Üzerine Bir İnceleme, 1830-1831'de yazıldı, Joseph Liouville tarafından Journal de Mathématiques Pures et Appliquées dergisinde 1846'da yayımlandı.")),
        H("A 300-year-old race", "300 yıllık bir yarış"),
        P(("Every student knows the formula for the roots of a **quadratic equation**.", "Her öğrenci **ikinci dereceden denklemin** kök formülünü bilir."),),
        FORMUL("x = (−b ± √(b² − 4ac)) / 2a"),
        P(("In the 16th century, Italian mathematicians found similar formulas for degree 3 and degree 4.", "16. yüzyılda İtalyan matematikçiler 3. ve 4. dereceden denklemler için benzer formüller buldu."),
          ("Cardano published both of them in his book Ars Magna in 1545.", "Cardano ikisini de 1545'te Ars Magna adlı kitabında yayımladı."),
          ("These formulas use only the four operations and **radicals** such as square roots and cube roots.", "Bu formüller yalnızca dört işlemi ve karekök, küpkök gibi **kökleri** kullanır."),
          ("Then mathematicians tried degree 5, the **quintic**, for almost three hundred years and failed.", "Sonra matematikçiler neredeyse üç yüz yıl boyunca 5. dereceyi, yani **beşinci dereceden denklemi** denedi ve başaramadı.")),
        P(("In 1824, the young Norwegian mathematician Niels Henrik Abel proved that no general formula of this kind exists for degree 5.", "1824'te genç Norveçli matematikçi Niels Henrik Abel, 5. derece için bu türden genel bir formülün olmadığını kanıtladı."),
          ("But a new question remained.", "Ama yeni bir soru kaldı."),
          ("Some quintics, like x⁵ − 2 = 0, can clearly be solved with radicals.", "x⁵ − 2 = 0 gibi bazı beşinci dereceden denklemler açıkça köklerle çözülebiliyor."),
          ("So which equations can be solved and which cannot?", "Peki hangi denklemler çözülebilir, hangileri çözülemez?"),
          ("Galois answered exactly this question.", "Galois tam olarak bu soruyu cevapladı.")),
        H("The key idea: symmetries of the roots", "Anahtar fikir: Köklerin simetrileri"),
        P(("Take the equation x² − 2 = 0, whose roots are √2 and −√2.", "x² − 2 = 0 denklemini alalım, kökleri √2 ve −√2."),
          ("Swap the two roots.", "İki kökün yerini değiştirelim."),
          ("Every true statement about them with rational coefficients stays true, for example their sum is 0 and their product is −2.", "Rasyonel katsayılı her doğru ifade doğru kalır, örneğin toplamları 0, çarpımları −2."),
          ("Galois looked at all such **permutations** of the roots that keep every rational relation between them.", "Galois, kökler arasındaki her rasyonel bağıntıyı koruyan bu tür bütün **permütasyonlara** baktı."),
          ("Together they form what we now call the **Galois group** of the equation.", "Bunlar birlikte bugün denklemin **Galois grubu** dediğimiz yapıyı oluşturur.")),
        P(("For a \"typical\" equation of degree n, every permutation of the n roots is allowed.", "n. dereceden \"tipik\" bir denklemde n kökün her permütasyonuna izin verilir."),
          ("This group is called the **symmetric group** Sₙ and it has n! elements.", "Bu gruba **simetrik grup** Sₙ denir ve n! elemanı vardır.")),
        FORMUL("|S₅| = 5! = 120"),
        H("The theorem", "Teorem"),
        KUTU("bilgi", "Galois' criterion", "Galois ölçütü",
             ("An equation can be solved by radicals if and only if its Galois group is **solvable**.", "Bir denklem ancak ve ancak Galois grubu **çözülebilir** ise köklerle çözülebilir."),
             ("Roughly, a group is solvable if you can break it down step by step into simple commutative pieces.", "Kabaca söylersek, bir grubu adım adım basit ve değişmeli parçalara ayırabiliyorsan o grup çözülebilirdir."),
             ("Each step of the breakdown matches taking one more radical in the formula.", "Bu ayrıştırmanın her adımı, formülde bir kök daha almaya karşılık gelir.")),
        P(("The groups S₂, S₃ and S₄ are solvable, and this is why the formulas for degrees 2, 3 and 4 exist.", "S₂, S₃ ve S₄ grupları çözülebilir ve 2., 3. ve 4. derece formüllerinin var olmasının nedeni bu."),
          ("But S₅ is not solvable.", "Ama S₅ çözülebilir değil."),
          ("Inside it there is a group of 60 elements, A₅, which cannot be broken down any further.", "İçinde 60 elemanlı, daha fazla ayrıştırılamayan bir grup var: A₅."),
          ("That single fact closes the door on a general formula for degree 5 and higher.", "Bu tek gerçek, 5. ve daha yüksek dereceler için genel bir formülün kapısını kapatıyor.")),
        H("A concrete example", "Somut bir örnek"),
        FORMUL("x⁵ − 4x + 2 = 0"),
        P(("This equation cannot be factored over the rationals, and its graph crosses the x-axis exactly three times.", "Bu denklem rasyonel sayılarda çarpanlarına ayrılamaz ve grafiği x eksenini tam üç kez keser."),
          ("So it has three real roots and two complex roots.", "Yani üç reel ve iki karmaşık kökü var."),
          ("With these two facts, one can show that its Galois group is the whole of S₅.", "Bu iki bilgiyle Galois grubunun S₅'in tamamı olduğu gösterilebilir."),
          ("Therefore its roots can never be written using only numbers, the four operations and radicals.", "Dolayısıyla kökleri hiçbir zaman yalnızca sayılar, dört işlem ve köklerle yazılamaz."),
          ("The roots exist, and a computer can find them to any accuracy, but no radical formula can express them.", "Kökler var ve bir bilgisayar onları istenen doğrulukta bulabilir, ama hiçbir kök formülü onları ifade edemez.")),
        KUTU("bilgi", "Graduate corner", "Yüksek lisans köşesi",
             ("This paper is the birth of **group theory** and of what we now call **Galois theory**.", "Bu makale **grup teorisinin** ve bugün **Galois teorisi** dediğimiz alanın doğuşudur."),
             ("In modern language, there is a one-to-one correspondence between the subgroups of the Galois group and the intermediate fields of a field extension.", "Modern dilde, Galois grubunun alt grupları ile bir cisim genişlemesinin ara cisimleri arasında birebir bir eşleme vardır."),
             ("Proving that A₅ is simple and checking the example above step by step are classic exercises before a thesis in algebra.", "A₅'in basit olduğunu kanıtlamak ve yukarıdaki örneği adım adım kontrol etmek, cebirde tez öncesi klasik alıştırmalardır.")),
        TERIMLER(("quintic", "beşinci dereceden denklem"), ("solvable by radicals", "köklerle çözülebilir"), ("permutation", "permütasyon"),
                 ("symmetric group", "simetrik grup"), ("solvable group", "çözülebilir grup"), ("radical", "kök (radikal)")),
    ),

    BOLUM("bilim", "science", "#0E7490", "Science Corner: Left-Handed and Right-Handed Molecules", "Bilim Köşesi: Solak ve Sağlak Moleküller",
        P(("Hold your hands in front of a mirror.", "Ellerini bir aynanın önüne tut."),
          ("Your left hand looks exactly like the mirror image of your right hand.", "Sol elin, sağ elinin ayna görüntüsüne tıpatıp benziyor."),
          ("Yet you can never put a left glove on your right hand.", "Yine de sol eldiveni asla sağ eline geçiremezsin."),
          ("An object that is different from its mirror image is called **chiral**, from the Greek word for hand.", "Ayna görüntüsünden farklı olan bir nesneye, Yunanca \"el\" kelimesinden gelen **kiral** adı verilir.")),
        P(("Many molecules are chiral, too.", "Birçok molekül de kiraldir."),
          ("The two mirror forms of a molecule are called **enantiomers**.", "Bir molekülün iki ayna biçimine **enantiyomer** denir."),
          ("They contain the same atoms joined in the same way, but they can behave very differently in the body.", "Aynı atomları aynı şekilde birbirine bağlı olarak içerirler, ama vücutta çok farklı davranabilirler."),
          ("For example, one form of the molecule carvone smells of spearmint, and its mirror image smells of caraway seeds.", "Örneğin karvon molekülünün bir biçimi nane gibi, ayna görüntüsü ise karaman kimyonu gibi kokar.")),
        P(("In 1848, the young Louis Pasteur separated left-handed and right-handed crystals of a salt with tweezers under a microscope.", "1848'de genç Louis Pasteur bir tuzun solak ve sağlak kristallerini mikroskop altında cımbızla birbirinden ayırdı."),
          ("Since then, one mystery has remained.", "O zamandan beri bir gizem sürüyor."),
          ("Living things use almost only one form of each building block, for example the amino acids in our proteins are almost all of one hand.", "Canlılar her yapı taşının neredeyse yalnızca tek bir biçimini kullanır, örneğin proteinlerimizdeki amino asitlerin neredeyse hepsi aynı \"el\"dendir."),
          ("This is called **homochirality**.", "Buna **homokiralite** denir."),
          ("But a normal chemical reaction produces equal amounts of both forms.", "Ama sıradan bir kimyasal tepkime iki biçimden eşit miktarda üretir.")),
        H("The 2026 Nobel Prize in Chemistry", "2026 Nobel Kimya Ödülü"),
        P(("On 7 October 2026, the prize went to the French chemist **Henri B. Kagan** and the Japanese chemist **Kenso Soai**.", "7 Ekim 2026'da ödül Fransız kimyacı **Henri B. Kagan** ile Japon kimyacı **Kenso Soai**'ye verildi."),
          ("The citation reads \"for the discovery of non-linear effects and autocatalysis in asymmetric organic synthesis\".", "Ödül gerekçesi şöyle: \"asimetrik organik sentezde doğrusal olmayan etkilerin ve otokatalizin keşfi için\"."),
          ("Kagan was born in 1930 and Soai in 1950.", "Kagan 1930'da, Soai 1950'de doğdu.")),
        LISTE(("**Kagan (1986)**: chemists expected that a catalyst which is only partly of one hand would give a product that is only partly of one hand, in a straight-line relationship.", "**Kagan (1986)**: Kimyacılar, kısmen tek elli bir katalizörün kısmen tek elli bir ürün vereceğini, yani aradaki ilişkinin bir doğru olacağını bekliyordu."),
              ("Kagan showed that this relationship can be a curve, so the product can be much more one-handed than the catalyst.", "Kagan bu ilişkinin bir eğri olabileceğini, yani ürünün katalizörden çok daha fazla tek elli olabileceğini gösterdi."),
              ("**Soai (1995)**: he found a reaction whose product is the catalyst of its own formation and prefers to copy its own hand.", "**Soai (1995)**: Ürünü kendi oluşumunun katalizörü olan ve kendi \"elini\" kopyalamayı tercih eden bir tepkime buldu."),
              ("This is called **autocatalysis**, and it turns a tiny excess of one hand into an almost pure product.", "Buna **otokataliz** denir ve tek bir elin küçücük bir fazlalığını neredeyse saf bir ürüne dönüştürür."),
              ("In 2003, Soai reported a reaction that formed only one of the two mirror images.", "Soai 2003'te iki ayna görüntüsünden yalnızca birini oluşturan bir tepkime bildirdi.")),
        P(("The Nobel Committee says that their work shows how homochirality can appear by itself.", "Nobel Komitesi, çalışmalarının homokiralitenin kendiliğinden nasıl ortaya çıkabileceğini gösterdiğini söylüyor."),
          ("It also guides chemists who design reactions to make medicines.", "Ayrıca ilaç üretimi için tepkime tasarlayan kimyacılara yol gösteriyor.")),
        KUTU("bilgi", "Where is the maths?", "Matematik nerede?",
             ("Chemists measure how one-sided a mixture is with the **enantiomeric excess**.", "Kimyacılar bir karışımın ne kadar tek taraflı olduğunu **enantiyomer fazlalığı** ile ölçer."),
             ("If R and S are the amounts of the two forms, then ee = (R − S) / (R + S).", "R ve S iki biçimin miktarı ise ee = (R − S) / (R + S)."),
             ("A 50–50 mixture has ee = 0, and a pure sample has ee = 1.", "Yarı yarıya bir karışımda ee = 0, saf bir örnekte ee = 1."),
             ("Mathematically, a mirror is a **reflection**, and a chiral object is one that no rotation can turn into its reflection.", "Matematiksel olarak ayna bir **yansımadır** ve kiral nesne, hiçbir dönmenin onu yansımasına dönüştüremediği nesnedir."),
             ("The group of the two \"hands\" has only two elements, exactly like the Galois group of x² − 2, which swaps √2 and −√2.", "İki \"el\"in grubu yalnızca iki elemanlıdır, tıpkı √2 ile −√2'nin yerini değiştiren x² − 2'nin Galois grubu gibi.")),
        TERIMLER(("chiral", "kiral"), ("enantiomer", "enantiyomer, ayna izomeri"), ("homochirality", "homokiralite, tek ellilik"),
                 ("autocatalysis", "otokataliz"), ("enantiomeric excess", "enantiyomer fazlalığı"), ("catalyst", "katalizör")),
    ),

    BOLUM("matematikci", "person", "#E67E22", "Mathematician of the Month: Évariste Galois", "Ayın Matematikçisi: Évariste Galois",
        PORTRE("https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Evariste_galois.jpg/500px-Evariste_galois.jpg",
               "Évariste Galois", "1811 – 1832",
               "French mathematician who founded group theory and died at the age of 20.",
               "Grup teorisini kuran ve 20 yaşında hayatını kaybeden Fransız matematikçi.",
               "Drawing by his brother Alfred, 1848 · Public domain, Wikimedia Commons"),
        P(("Galois lived only twenty years.", "Galois yalnızca yirmi yıl yaşadı."),
          ("In that short time he changed the way we think about algebra forever.", "Bu kısa sürede cebir hakkındaki düşünme biçimimizi sonsuza dek değiştirdi.")),
        H("His life", "Hayatı"),
        LISTE(("He was born on 25 October 1811 in Bourg-la-Reine, a small town near Paris.", "25 Ekim 1811'de Paris yakınlarındaki küçük bir kasaba olan Bourg-la-Reine'de doğdu."),
              ("His father was the mayor of the town, and his mother taught him at home until he was twelve.", "Babası kasabanın belediye başkanıydı, annesi ise onu on iki yaşına kadar evde eğitti."),
              ("At school he became bored with ordinary lessons and read the works of great mathematicians on his own.", "Okulda sıradan derslerden sıkıldı ve büyük matematikçilerin eserlerini kendi başına okudu."),
              ("He failed the entrance exam of the famous École Polytechnique **twice**.", "Ünlü École Polytechnique'in giriş sınavında **iki kez** başarısız oldu."),
              ("In 1829 his father took his own life after a political scandal, and this was a terrible blow for him.", "1829'da babası siyasi bir skandalın ardından intihar etti ve bu onun için korkunç bir darbe oldu."),
              ("He sent his work to the Academy of Sciences several times, but one manuscript was lost and another was rejected as not clear enough.", "Çalışmalarını birkaç kez Bilimler Akademisi'ne gönderdi, ama bir taslak kayboldu, bir diğeri yeterince açık olmadığı gerekçesiyle reddedildi."),
              ("He was a passionate **republican**, and in 1831 he spent months in prison for his political activities.", "Tutkulu bir **cumhuriyetçiydi** ve 1831'de siyasi faaliyetleri yüzünden aylarca hapiste kaldı."),
              ("On 30 May 1832 he was badly wounded in a **duel**, and he died the next day.", "30 Mayıs 1832'de bir **düelloda** ağır yaralandı ve ertesi gün hayatını kaybetti.")),
        H("The last letter", "Son mektup"),
        P(("The night before the duel, Galois wrote a long letter to his friend Auguste Chevalier.", "Düellodan önceki gece Galois, arkadaşı Auguste Chevalier'ye uzun bir mektup yazdı."),
          ("In it he summarised his ideas and asked that they be sent to great mathematicians of his time.", "Mektupta fikirlerini özetledi ve bunların döneminin büyük matematikçilerine gönderilmesini istedi."),
          ("He hoped that someone would one day find it useful to \"decipher all this mess\".", "Bir gün birinin \"bütün bu karmaşayı çözmeyi\" faydalı bulacağını umuyordu."),
          ("Fourteen years later, Joseph Liouville studied his papers carefully, understood them and published them in 1846.", "On dört yıl sonra Joseph Liouville yazılarını dikkatle inceledi, anladı ve 1846'da yayımladı.")),
        H("His contributions", "Katkıları"),
        P(("**Groups**: Galois was the first to use the word \"group\" in its modern mathematical sense.", "**Gruplar**: \"Grup\" kelimesini bugünkü matematiksel anlamıyla ilk kullanan Galois'ydı."),
          ("A group is a set of operations, such as the symmetries of a shape, that can be combined and undone.", "Grup, bir şeklin simetrileri gibi, birleştirilebilen ve geri alınabilen işlemlerin kümesidir."),
          ("Today groups are used everywhere, from crystals and molecules to particle physics and cryptography.", "Bugün gruplar kristallerden ve moleküllerden parçacık fiziğine ve kriptografiye kadar her yerde kullanılıyor.")),
        P(("**Normal subgroups**: he noticed that some subgroups are special, because the group can be \"divided\" by them.", "**Normal alt gruplar**: Bazı alt grupların özel olduğunu fark etti, çünkü grup onlara \"bölünebiliyordu\"."),
          ("This idea is the heart of his criterion for solving equations.", "Bu fikir, denklem çözme ölçütünün kalbidir.")),
        P(("**Finite fields**: he also studied number systems with only finitely many elements.", "**Sonlu cisimler**: Yalnızca sonlu sayıda elemanı olan sayı sistemlerini de inceledi."),
          ("They are called **Galois fields** in his honour.", "Onun onuruna bunlara **Galois cisimleri** denir."),
          ("The QR codes on your phone and the error-correcting codes in satellites are built on them.", "Telefonundaki QR kodlar ve uydulardaki hata düzelten kodlar bunların üzerine kurulu.")),
        KUTU("sinif", "For the classroom", "Sınıf için",
             ("Galois' story shows that failing an exam does not mean failing in mathematics.", "Galois'nın hikâyesi, bir sınavda başarısız olmanın matematikte başarısız olmak anlamına gelmediğini gösteriyor."),
             ("It also shows how important it is to write your ideas clearly, so that others can understand them.", "Ayrıca başkalarının anlayabilmesi için fikirlerini açıkça yazmanın ne kadar önemli olduğunu da gösteriyor.")),
        TERIMLER(("group", "grup"), ("normal subgroup", "normal alt grup"), ("finite field", "sonlu cisim"),
                 ("duel", "düello"), ("to decipher", "deşifre etmek, çözmek"), ("to reject", "reddetmek")),
    ),

    BOLUM("odul", "emoji_events", "#D4A017", "Prize Corner", "Ödüller Köşesi",
        H("Nobel Prize in Physics 2026: a telescope made of ice", "Nobel Fizik 2026: Buzdan bir teleskop"),
        P(("On 6 October 2026, the prize went to **Francis Halzen** of the University of Wisconsin–Madison.", "6 Ekim 2026'da ödül Wisconsin–Madison Üniversitesi'nden **Francis Halzen**'e verildi."),
          ("Halzen is 82 years old and was born in Tienen, Belgium.", "Halzen 82 yaşında ve Belçika'nın Tienen kentinde doğdu."),
          ("He was honoured for decisive contributions to the **IceCube Neutrino Observatory** and the discovery of high-energy **neutrinos** from space.", "**IceCube Nötrino Gözlemevi**'ne yaptığı belirleyici katkılar ve uzaydan gelen yüksek enerjili **nötrinoların** keşfi için ödüllendirildi.")),
        P(("Neutrinos are tiny particles that almost never interact with matter.", "Nötrinolar madde ile neredeyse hiç etkileşmeyen minicik parçacıklardır."),
          ("They travel from distant galaxies to us without changing direction or losing energy.", "Uzak galaksilerden bize yön değiştirmeden ve enerji kaybetmeden ulaşırlar."),
          ("In 1988 Halzen suggested using the ice under the South Pole to catch them.", "Halzen 1988'de onları yakalamak için Güney Kutbu'nun altındaki buzu kullanmayı önerdi."),
          ("The detector, completed in 2010, is about one **cubic kilometre** of ice with 5,160 light sensors inside.", "2010'da tamamlanan dedektör, içinde 5.160 ışık sensörü bulunan yaklaşık bir **kilometreküp** buzdan oluşuyor."),
          ("In 2013 the team announced the first high-energy neutrinos from outside our solar system, and in 2023 they made the first image of the Milky Way in neutrinos.", "Ekip 2013'te Güneş Sistemi'nin dışından gelen ilk yüksek enerjili nötrinoları duyurdu, 2023'te ise Samanyolu'nun nötrinolarla çekilmiş ilk görüntüsünü oluşturdu.")),
        P(("Where is the maths?", "Peki matematik nerede?"),
          ("When a neutrino hits the ice, it makes a faint flash of blue light.", "Bir nötrino buza çarptığında soluk mavi bir ışık parlaması oluşturur."),
          ("The sensors record when the light reaches each of them.", "Sensörler ışığın her birine ne zaman ulaştığını kaydeder."),
          ("From these arrival times, computers calculate the **direction** of the particle, a little like finding an earthquake's centre from the times at different stations.", "Bu varış zamanlarından bilgisayarlar parçacığın **yönünü** hesaplar, biraz farklı istasyonlardaki zamanlardan bir depremin merkezini bulmak gibi.")),
        H("Why is there no Nobel Prize in mathematics?", "Matematikte neden Nobel Ödülü yok?"),
        P(("Every October, when the Nobel Prizes are announced, many people ask the same question: why is there no Nobel Prize in mathematics?", "Her ekim Nobel Ödülleri açıklanırken pek çok kişi aynı soruyu soruyor: Matematikte neden Nobel Ödülü yok?"),
          ("A popular story blames a quarrel between Alfred Nobel and the Swedish mathematician Gösta Mittag-Leffler.", "Popüler bir hikâye bunu Alfred Nobel ile İsveçli matematikçi Gösta Mittag-Leffler arasındaki bir kavgaya bağlar."),
          ("However, historians have found no **evidence** for this story.", "Ancak tarihçiler bu hikâyeyi destekleyen hiçbir **kanıt** bulamadı."),
          ("A simpler explanation is that Nobel, an inventor and businessman, chose fields close to his own interests when he wrote his **will** in 1895.", "Daha basit bir açıklamaya göre bir mucit ve iş insanı olan Nobel, 1895'te **vasiyetnamesini** yazarken kendi ilgi alanlarına yakın dalları seçti."),
          ("Today the Fields Medal and the Abel Prize, first given in 2003, fill this gap.", "Bugün bu boşluğu Fields Madalyası ve ilk kez 2003'te verilen Abel Ödülü dolduruyor."),
          ("Mathematicians still win Nobel Prizes in other fields, for example John Nash in economics in 1994 and Roger Penrose in physics in 2020.", "Matematikçiler yine de başka alanlarda Nobel kazanıyor, örneğin 1994'te ekonomide John Nash ve 2020'de fizikte Roger Penrose.")),
        KUTU("bilgi", "Coming soon", "Yakında",
             ("The Nobel Prize in Economic Sciences will be announced on Monday, 12 October.", "Nobel Ekonomi Ödülü 12 Ekim Pazartesi günü açıklanacak."),
             ("We will write about it in our next issue if it has a maths link.", "Matematikle bir bağlantısı olursa bir sonraki sayımızda yazacağız.")),
        TERIMLER(("neutrino", "nötrino"), ("light sensor", "ışık sensörü"), ("cubic kilometre", "kilometreküp"),
                 ("will (legal document)", "vasiyetname"), ("evidence", "kanıt")),
    ),

    BOLUM("dusun", "psychology", "#16A085", "Think Like a Mathematician: Build on the Smaller Case", "Matematikçi Gibi Düşünmek: Bir Küçüğünden Kur",
        P(("In January we learned that a pattern from small cases is only a hint.", "Ocak sayımızda küçük durumlardan gelen bir örüntünün yalnızca bir ipucu olduğunu öğrenmiştik."),
          ("This month we go one step further: we use the answer for n to build the answer for n + 1.", "Bu ay bir adım daha ileri gidiyoruz: n için bulduğumuz cevabı n + 1'in cevabını kurmak için kullanıyoruz."),
          ("A rule that gives each answer from the one before is called a **recurrence relation**, and this way of thinking is called **recursion**.", "Her cevabı bir öncekinden veren kurala **indirgeme bağıntısı**, bu düşünme biçimine de **özyineleme** denir."),
          ("Galois also learned from the smaller degrees, because degrees 2, 3 and 4 showed him what was special about degree 5.", "Galois da küçük derecelerden öğrendi, çünkü 2, 3 ve 4. dereceler ona 5. derecenin neden özel olduğunu gösterdi.")),
        KUTU("soru", "The problem: the Tower of Hanoi", "Problem: Hanoi Kulesi",
             ("There are three pegs, and n discs of different sizes sit on the first peg, the largest at the bottom.", "Üç çubuk var ve farklı büyüklükteki n disk, en büyüğü altta olacak şekilde ilk çubukta duruyor."),
             ("You may move one disc at a time, and you may never put a larger disc on a smaller one.", "Her seferinde bir disk taşıyabilirsin ve büyük bir diski asla küçük bir diskin üstüne koyamazsın."),
             ("What is the smallest number of moves needed to carry the whole tower to the third peg?", "Bütün kuleyi üçüncü çubuğa taşımak için gereken en az hamle sayısı kaçtır?")),
        H("Step 1: a table of small cases", "1. adım: Küçük durumların tablosu"),
        TABLO(["n", "moves", "result"],
              ["1", "move the disc", "1"],
              ["2", "small, big, small", "3"],
              ["3", "3 + 1 + 3", "7"],
              ["4", "7 + 1 + 7", "15"]),
        H("Step 2: find the recurrence", "2. adım: İndirgeme bağıntısını bul"),
        P(("Look at the middle column: each line uses the line above it twice.", "Ortadaki sütuna bak: Her satır, üstündeki satırı iki kez kullanıyor."),
          ("Before the largest disc can move, the n smaller discs above it must all be on the middle peg.", "En büyük disk hareket edebilmeden önce üstündeki n küçük diskin hepsi ortadaki çubukta olmalı."),
          ("So to move n + 1 discs, you move n discs out of the way, then the largest disc, and then the n discs back on top of it.", "Yani n + 1 diski taşımak için önce n diski kenara çekersin, sonra en büyük diski taşırsın, sonra n diski yeniden onun üstüne koyarsın.")),
        FORMUL("h(n + 1) = 2 · h(n) + 1,   h(1) = 1"),
        H("Step 3: solve it", "3. adım: Çöz"),
        P(("The results 1, 3, 7 and 15 are all one less than a **power of two**, so we guess that h(n) = 2ⁿ − 1.", "1, 3, 7 ve 15 sonuçlarının hepsi **ikinin bir kuvvetinden** bir eksik, bu yüzden h(n) = 2ⁿ − 1 olduğunu tahmin ediyoruz."),
          ("The recurrence turns this guess into a proof.", "İndirgeme bağıntısı bu tahmini bir ispata dönüştürüyor.")),
        FORMUL("2 · (2ⁿ − 1) + 1 = 2ⁿ⁺¹ − 1"),
        P(("So if the formula is true for n discs, it is also true for n + 1 discs, and our guess is true for all n.", "Yani formül n disk için doğruysa n + 1 disk için de doğrudur ve tahminimiz her n için geçerlidir."),
          ("This step-by-step argument is called **proof by induction**.", "Bu adım adım ilerleyen akıl yürütmeye **tümevarımla ispat** denir.")),
        KUTU("ipucu", "The lesson", "Ders",
             ("Do not only ask \"What is the answer for n?\", but also ask \"How does the answer for n help with n + 1?\"", "Yalnızca \"n için cevap ne?\" diye sorma, \"n'nin cevabı n + 1 için nasıl yardım eder?\" diye de sor."),
             ("A recurrence explains why the pattern continues, so it often leads straight to an induction proof.", "İndirgeme bağıntısı örüntünün neden devam ettiğini açıklar, bu yüzden çoğu zaman doğrudan bir tümevarım ispatına götürür."),
             ("Computer scientists use the same idea every day, because many programs call themselves on a smaller input.", "Bilgisayar bilimciler aynı fikri her gün kullanır, çünkü birçok program kendini daha küçük bir girdiyle çağırır.")),
        KUTU("soru", "Your turn", "Senin sıran",
             ("How many **diagonals** does a polygon with n sides have?", "n kenarlı bir çokgenin kaç **köşegeni** vardır?"),
             ("Find a recurrence: what changes when you add one more corner to the polygon?", "Bir indirgeme bağıntısı bul: Çokgene bir köşe daha eklediğinde ne değişir?")),
        KUTU("ipucu", "Answer", "Cevap",
             ("Put a new corner between two neighbouring corners of an n-gon.", "n kenarlı bir çokgenin iki komşu köşesinin arasına yeni bir köşe koy."),
             ("The new corner gets a diagonal to every old corner except its two neighbours, which is n − 2 new diagonals.", "Yeni köşe, iki komşusu dışındaki her eski köşeye bir köşegen alır, bu da n − 2 yeni köşegen eder."),
             ("The old side between the two neighbours also becomes a diagonal, so d(n + 1) = d(n) + n − 1.", "İki komşu arasındaki eski kenar da köşegen olur, yani d(n + 1) = d(n) + n − 1."),
             ("Starting from d(3) = 0, we get 2, 5 and 9 for n = 4, 5 and 6, and in general d(n) = n(n − 3) / 2.", "d(3) = 0'dan başlayınca n = 4, 5 ve 6 için 2, 5 ve 9 buluruz ve genel olarak d(n) = n(n − 3) / 2.")),
        TERIMLER(("recursion", "özyineleme"), ("recurrence relation", "indirgeme bağıntısı"), ("power of two", "ikinin kuvveti"),
                 ("peg", "çubuk"), ("neighbouring", "komşu")),
    ),

    BOLUM("eglence", "lightbulb", "#E84393", "Fun Facts: October and the Number 10", "Eğlenceli Bilgiler: Ekim ve 10 Sayısı",
        LISTE(("**Ten and ten**: October is the tenth month of the year, and this is our tenth issue.", "**On ve on**: Ekim yılın onuncu ayı ve bu da onuncu sayımız."),
              ("**Two prime pairs**: 10 = 3 + 7 = 5 + 5, and 10 is the smallest number that is a sum of two primes in two different ways.", "**İki asal çift**: 10 = 3 + 7 = 5 + 5 ve 10, iki asalın toplamı olarak iki farklı biçimde yazılabilen en küçük sayıdır."),
              ("Goldbach guessed in 1742 that every even number greater than 2 is a sum of two primes, and nobody has proved it yet.", "Goldbach 1742'de 2'den büyük her çift sayının iki asalın toplamı olduğunu tahmin etti ve bunu henüz kimse kanıtlayamadı."),
              ("**Ten fingers**: most historians think we count in **base ten** simply because we have ten fingers.", "**On parmak**: Tarihçilerin çoğu **onluk tabanda** saymamızın nedeninin basitçe on parmağımızın olması olduğunu düşünüyor."),
              ("The Babylonians used base 60, and that is why an hour still has 60 minutes.", "Babilliler 60 tabanını kullanıyordu ve bir saatin hâlâ 60 dakika olmasının nedeni bu."),
              ("**A triangle of ten**: 10 = 1 + 2 + 3 + 4, so ten dots can form a perfect triangle.", "**Onun üçgeni**: 10 = 1 + 2 + 3 + 4, yani on nokta mükemmel bir üçgen oluşturabilir."),
              ("The Pythagoreans called this shape the tetractys and saw it as a holy number.", "Pisagorcular bu şekle tetraktis diyor ve onu kutsal bir sayı olarak görüyordu."),
              ("**Six weeks in a factorial**: 10! = 3,628,800, which is exactly the number of seconds in six weeks.", "**Bir faktöriyelde altı hafta**: 10! = 3.628.800 ve bu tam olarak altı haftadaki saniye sayısı."),
              ("Check it: 6 × 7 × 24 × 60 × 60 = 3,628,800.", "Kontrol et: 6 × 7 × 24 × 60 × 60 = 3.628.800."),
              ("**An old joke**: \"There are 10 kinds of people in the world: those who understand **binary** and those who do not.\"", "**Eski bir şaka**: \"Dünyada 10 tür insan vardır: **ikili sistemi** anlayanlar ve anlamayanlar.\""),
              ("In base two, 10 means two.", "İkilik tabanda 10, iki demektir.")),
        TERIMLER(("base ten", "onluk taban"), ("base two", "ikilik taban"),
                 ("triangular number", "üçgensel sayı"), ("factorial", "faktöriyel")),
    ),

    BOLUM("sinif", "school", "#27AE60", "In the Classroom", "Sınıfta Matematik",
        H("Grades 6–8: Left-handed and right-handed shapes", "6-8. sınıflar: Solak ve sağlak şekiller"),
        P(("Goal: recognising **mirror images** and linking them to the Nobel story of left and right hands.", "Hedef: **Ayna görüntülerini** tanımak ve onları sağ ve sol ellerin Nobel hikâyesine bağlamak."),),
        LISTE(("A **pentomino** is a shape made of five equal squares joined edge to edge.", "**Pentomino**, kenar kenara birleşmiş beş eş kareden oluşan bir şekildir."),
              ("Groups cut squares from squared paper and try to find all the different pentominoes.", "Gruplar kareli kâğıttan kareler kesip bütün farklı pentominoları bulmaya çalışsın."),
              ("Shapes that can be turned or flipped onto each other count as the same, and there are exactly 12 of them.", "Döndürülerek ya da ters çevrilerek birbirinin üstüne gelen şekiller aynı sayılır ve tam 12 tane vardır."),
              ("Now give each group a small mirror and ask: which pentominoes have a line of symmetry?", "Şimdi her gruba küçük bir ayna verin ve sorun: Hangi pentominoların simetri ekseni var?"),
              ("Six of them (I, T, U, V, W, X) have one, and the other six (F, L, N, P, Y, Z) have none.", "Altısının (I, T, U, V, W, X) simetri ekseni var, diğer altısının (F, L, N, P, Y, Z) ise yok."),
              ("If you may not flip the pieces over, each of these six comes in a left-handed and a right-handed version, just like chiral molecules.", "Parçaları ters çevirmek yasaksa bu altı şeklin her birinin, tıpkı kiral moleküller gibi, solak ve sağlak bir versiyonu olur.")),
        KUTU("sinif", "Bonus question", "Bonus soru",
             ("How many different pieces are there if flipping is not allowed?", "Ters çevirmeye izin verilmezse kaç farklı parça vardır?"),
             ("The answer is 6 + 2 × 6 = 18.", "Cevap 6 + 2 × 6 = 18."),
             ("This activity practises classification, careful observation and explaining a rule in your own words.", "Bu etkinlik sınıflandırma, dikkatli gözlem ve bir kuralı kendi cümleleriyle açıklama becerilerini çalıştırıyor.")),
        H("High school: The six symmetries of a triangle", "Lise: Bir üçgenin altı simetrisi"),
        P(("You need a paper equilateral triangle with its corners numbered 1, 2 and 3 on both sides.", "Köşeleri iki yüzünde de 1, 2 ve 3 diye numaralandırılmış kâğıttan bir eşkenar üçgene ihtiyacınız var."),
          ("Draw its outline on the desk.", "Üçgenin dış çizgisini sıraya çizin."),
          ("Students find every way to pick it up and put it back into the outline.", "Öğrenciler üçgeni kaldırıp yeniden bu çizginin içine yerleştirmenin tüm yollarını bulsun.")),
        LISTE(("There are three **rotations**: 0°, 120° and 240°.", "Üç **dönme** var: 0°, 120° ve 240°."),
              ("There are three reflections, one in each line through a corner and the midpoint of the opposite side.", "Üç yansıma var, her biri bir köşeden ve karşı kenarın orta noktasından geçen bir doğruya göre."),
              ("Each symmetry is a permutation of the corners, so there are 3! = 6 of them.", "Her simetri köşelerin bir permütasyonu, bu yüzden toplam 3! = 6 tane var.")),
        P(("Now let students do two symmetries one after the other and record the result in a 6 × 6 **composition table**.", "Şimdi öğrenciler iki simetriyi art arda uygulasın ve sonucu 6 × 6'lık bir **bileşke tablosuna** yazsın."),),
        KUTU("soru", "Discussion questions", "Tartışma soruları",
             ("Is \"rotate, then reflect\" the same as \"reflect, then rotate\"?", "\"Önce döndür, sonra yansıt\" ile \"önce yansıt, sonra döndür\" aynı mı?"),
             ("Hint: it is not, so the order matters, and the group is not **commutative**.", "İpucu: Değil, yani sıra önemli ve grup **değişmeli** değil."),
             ("Which symmetry undoes the 120° rotation?", "120°'lik dönmeyi hangi simetri geri alır?"),
             ("This group is S₃, the same group as the Galois group of x³ − 2 = 0.", "Bu grup S₃ ve x³ − 2 = 0 denkleminin Galois grubuyla aynı.")),
        P(("This activity brings transformations, permutations and the idea of a function composition together in one hands-on task.", "Bu etkinlik dönüşümleri, permütasyonları ve fonksiyon bileşkesi fikrini tek bir uygulamalı görevde birleştiriyor."),),
        TERIMLER(("to flip", "ters çevirmek"), ("pentomino", "pentomino"), ("rotation", "dönme"), ("equilateral triangle", "eşkenar üçgen"),
                 ("composition", "bileşke"), ("commutative", "değişmeli")),
    ),

    BOLUM("gundem", "campaign", "#C0392B", "Education in Türkiye", "Eğitim Gündemi",
        H("The 2026–2027 school year is under way", "2026-2027 eğitim yılı başladı"),
        P(("Schools opened on Monday, 14 September 2026.", "Okullar 14 Eylül 2026 Pazartesi günü açıldı."),
          ("The first mid-term break is from 16 to 20 November, and lessons start again on 23 November.", "Birinci ara tatil 16-20 Kasım arasında ve dersler 23 Kasım'da yeniden başlıyor."),
          ("The first term ends on Friday, 22 January 2027.", "Birinci dönem 22 Ocak 2027 Cuma günü sona eriyor.")),
        H("The common written exams", "Ortak yazılı sınavlar"),
        P(("In September, the Ministry of National Education announced the dates of the **common written exams** for grades 6, 7, 9 and 10.", "Eylülde Millî Eğitim Bakanlığı 6, 7, 9 ve 10. sınıflar için **ortak yazılı sınavların** tarihlerini açıkladı."),
          ("There will be eight common exams in the whole year.", "Yıl boyunca toplam sekiz ortak sınav yapılacak."),
          ("All of them will use **open-ended questions**, where students write their own answers.", "Hepsinde öğrencilerin cevaplarını kendilerinin yazdığı **açık uçlu sorular** kullanılacak.")),
        LISTE(("First term, first exams: 11–12 November 2026.", "Birinci dönem birinci yazılılar: 11-12 Kasım 2026."),
              ("First term, second exams: 5–6 January 2027.", "Birinci dönem ikinci yazılılar: 5-6 Ocak 2027."),
              ("In the first term, the maths exams are for grade 6 and grade 9.", "Birinci dönemde matematik sınavları 6. ve 9. sınıflar için."),
              ("In the second term, they are for grade 7 and grade 10.", "İkinci dönemde ise 7. ve 10. sınıflar için.")),
        KUTU("sinif", "For maths teachers of grades 6 and 9", "6. ve 9. sınıf matematik öğretmenlerine",
             ("Students who are used to multiple-choice tests often leave open-ended questions half-finished.", "Çoktan seçmeli testlere alışkın öğrenciler açık uçlu soruları çoğu zaman yarım bırakıyor."),
             ("Before November, practise writing full solutions in class: what is given, what is asked, each step and a final sentence.", "Kasımdan önce sınıfta tam çözüm yazmayı çalışın: Verilen, istenen, her adım ve bir sonuç cümlesi."),
             ("The \"Your turn\" diagonal question in this issue is a good short exercise for explaining a reason in words.", "Bu sayıdaki \"Senin sıran\" köşegen sorusu, bir gerekçeyi kelimelerle açıklamak için iyi bir kısa alıştırma.")),
        H("29 October: a maths moment for Republic Day", "29 Ekim: Cumhuriyet Bayramı için bir matematik anı"),
        P(("This year, 29 October falls on a Thursday.", "Bu yıl 29 Ekim perşembe gününe denk geliyor."),
          ("A nice question for the class: if the Republic was founded in 1923, which anniversary is it, and in which year will we celebrate the 125th?", "Sınıf için güzel bir soru: Cumhuriyet 1923'te kurulduysa bu kaçıncı yıl dönümü ve 125. yılı hangi yıl kutlayacağız?"),
          ("The answers are 103 and 2048.", "Cevaplar 103 ve 2048."),
          ("And 2048 = 2¹¹ is a power of two, which makes it a lovely number to wait for!", "Üstelik 2048 = 2¹¹ ikinin bir kuvveti, bu da onu beklemeye değer güzel bir sayı yapıyor!")),
        TERIMLER(("common exam", "ortak sınav"), ("open-ended question", "açık uçlu soru"),
                 ("Republic Day", "Cumhuriyet Bayramı"), ("anniversary", "yıl dönümü")),
    ),

    BOLUM("oku", "menu_book", "#34495E", "Read Like a Mathematician", "Matematikçi Gibi Oku",
        P(("Algebra books have their own favourite phrases.", "Cebir kitaplarının kendine has gözde kalıpları vardır."),
          ("This month we look at phrases you will meet in every text on groups and Galois theory.", "Bu ay gruplar ve Galois teorisi üzerine her metinde karşılaşacağın kalıplara bakıyoruz.")),
        TABLO(["English", "Türkçe", "Note"],
              ["is called", "… denir", "used in definitions"],
              ["is closed under", "… altında kapalıdır", "the result stays inside the set"],
              ["up to isomorphism", "izomorfizm farkıyla", "the same structure with different names"],
              ["the following are equivalent (TFAE)", "aşağıdakiler denktir", "a list of conditions that are all the same"],
              ["is uniquely determined", "tek türlü belirlidir", "there is exactly one such object"],
              ["namely", "yani, şöyle ki", "gives the exact object"],
              ["is generated by", "… tarafından üretilir", "every element is built from a few"],
              ["vice versa", "ve tersi", "the same is true the other way round"]),
        KUTU("soru", "Mini reading: the identity is unique", "Mini okuma: Birim eleman tektir",
             ("Definition: A group is a set G with an operation · that has four properties.", "Tanım: Grup, dört özelliği olan bir · işlemiyle donatılmış bir G kümesidir."),
             ("G is closed under ·, the operation is associative, there exists an identity element and every element has an inverse.", "G, · işlemi altında kapalıdır, işlem birleşmelidir, bir birim eleman vardır ve her elemanın tersi vardır."),
             ("An element e is called an identity if e · g = g · e = g for all g in G.", "Her g ∈ G için e · g = g · e = g ise e elemanına birim eleman denir."),
             ("Proposition: The identity of a group is uniquely determined.", "Önerme: Bir grubun birim elemanı tek türlü belirlidir."),
             ("Proof: Let e and f be identities of G. We show that they are the same element, namely that e = f.", "İspat: e ve f, G'nin birim elemanları olsun. Bunların aynı eleman olduğunu, yani e = f olduğunu gösteriyoruz."),
             ("Since f is an identity, e · f = e, and since e is an identity, e · f = f.", "f birim eleman olduğu için e · f = e, e birim eleman olduğu için de e · f = f."),
             ("Hence e = e · f = f. ∎", "Dolayısıyla e = e · f = f. ∎")),
        KUTU("ipucu", "A small note", "Küçük not",
             ("The proof uses the same product e · f in two different ways.", "İspat aynı e · f çarpımını iki farklı şekilde kullanıyor."),
             ("This trick of looking at one object from two sides appears again and again in algebra.", "Tek bir nesneye iki taraftan bakma hilesi cebirde tekrar tekrar karşımıza çıkar."),
             ("Notice also that we never used inverses, so the same proof works for any structure with an identity.", "Ayrıca terslerini hiç kullanmadığımıza dikkat et, yani aynı ispat birim elemanı olan her yapı için geçerli.")),
        TERIMLER(("closed under", "… altında kapalı"), ("up to isomorphism", "izomorfizm farkıyla"), ("identity element", "birim eleman"),
                 ("inverse", "ters eleman"), ("uniquely determined", "tek türlü belirli"), ("associative", "birleşmeli")),
    ),
]

quiz = [
    SORU("What did OpenAI release on 6 October 2026?", "OpenAI 6 Ekim 2026'da ne yayımladı?",
         ["722 maths manuscripts from an unreleased model", "A new calculator app", "The answers to the LGS", "A proof of Fermat's Last Theorem"], 0,
         "The manuscripts were put on GitHub and many came with Lean files, but mathematicians say they still need checking.", "Taslaklar GitHub'a kondu ve çoğu Lean dosyalarıyla geldi, ama matematikçiler hâlâ kontrol edilmeleri gerektiğini söylüyor."),
    SORU("According to Galois, when can an equation be solved by radicals?", "Galois'ya göre bir denklem ne zaman köklerle çözülebilir?",
         ["When its degree is odd", "When its Galois group is solvable", "When all its roots are real", "When its coefficients are integers"], 1,
         "An equation is solvable by radicals if and only if its Galois group is solvable, and S₅ is not.", "Bir denklem ancak ve ancak Galois grubu çözülebilirse köklerle çözülebilir ve S₅ çözülebilir değildir."),
    SORU("How many elements does the symmetric group S₅ have?", "S₅ simetrik grubunun kaç elemanı vardır?",
         ["5", "25", "60", "120"], 3,
         "S₅ contains every permutation of 5 roots, and 5! = 120.", "S₅, 5 kökün tüm permütasyonlarını içerir ve 5! = 120."),
    SORU("What does the word \"chiral\" describe?", "\"Kiral\" kelimesi neyi anlatır?",
         ["A circle with no centre", "A very small particle", "An object that is different from its mirror image", "A molecule with no atoms"], 2,
         "Like our hands, a chiral object cannot be turned into its mirror image by rotation.", "Ellerimiz gibi, kiral bir nesne döndürülerek ayna görüntüsüne dönüştürülemez."),
    SORU("Where is the IceCube Neutrino Observatory?", "IceCube Nötrino Gözlemevi nerededir?",
         ["On the Moon", "In a mine in Belgium", "Under the sea near Japan", "In the ice at the South Pole"], 3,
         "It uses about one cubic kilometre of Antarctic ice with thousands of light sensors.", "Binlerce ışık sensörü yerleştirilmiş yaklaşık bir kilometreküplük Antarktika buzunu kullanır."),
    SORU("What is the smallest number of moves for a Tower of Hanoi with 5 discs?", "5 diskli bir Hanoi Kulesi için en az hamle sayısı kaçtır?",
         ["25", "31", "32", "63"], 1,
         "n discs need 2ⁿ − 1 moves, so 5 discs need 2⁵ − 1 = 31 moves.", "n disk için 2ⁿ − 1 hamle gerekir, yani 5 disk için 2⁵ − 1 = 31 hamle."),
]

bulmacalar = [
    ANAGRAM("UPGOR", "GROUP", "Galois was the first to use this word in its modern mathematical sense.", "Galois bu kelimeyi bugünkü matematiksel anlamıyla ilk kullanan kişiydi."),
    ANAGRAM("DILEF", "FIELD", "A number system where you can add, subtract, multiply and divide.", "Toplama, çıkarma, çarpma ve bölme yapabildiğin bir sayı sistemi."),
    ANAGRAM("CTIUNIQ", "QUINTIC", "An equation of degree five.", "Beşinci dereceden bir denklem."),
    ANAGRAM("CIRALDA", "RADICAL", "A square root or a cube root in a formula.", "Bir formüldeki karekök ya da küpkök."),
    ESLESTIR("Match the terms", "Terimleri eşleştir",
             ("permutation", "permütasyon"), ("chiral", "kiral"), ("finite field", "sonlu cisim"),
             ("conjecture", "sanı"), ("identity element", "birim eleman")),
    MANTIK("The mirror clock", "Aynadaki saat",
           "You see a clock with hands in a mirror, and it seems to show 3:40. What is the real time?",
           "Akrep ve yelkovanlı bir saati aynada görüyorsun ve 3:40'ı gösteriyor gibi duruyor. Gerçek saat kaç?",
           "The real time is 8:20. A mirror reflects the clock face across the line from 12 to 6, so the real time and the mirror time always add up to 12 hours. 12:00 − 3:40 = 8:20.",
           "Gerçek saat 8:20. Ayna saat kadranını 12 ile 6'yı birleştiren doğruya göre yansıtır, bu yüzden gerçek saat ile aynadaki saatin toplamı her zaman 12 saattir. 12:00 − 3:40 = 8:20."),
    MANTIK("The shuffling cups", "Karışan bardaklar",
           "A magician repeats the same shuffle with three cups: the left cup goes to the middle, the middle cup goes to the right, and the right cup goes to the left. After how many shuffles are the cups back in their starting places for the first time? Where is the cup that started on the left after 2026 shuffles?",
           "Bir sihirbaz üç bardakla aynı karıştırmayı tekrar tekrar yapıyor: Soldaki bardak ortaya, ortadaki sağa, sağdaki de sola gidiyor. Kaç karıştırmadan sonra bardaklar ilk kez başlangıçtaki yerlerine döner? 2026 karıştırmadan sonra başta solda olan bardak nerededir?",
           "After 3 shuffles. The left cup goes left > middle > right > left, so every cup is home again after 3 moves. This shuffle is a permutation of order 3, an element of the group S₃. Since 2026 = 3 × 675 + 1, 2026 shuffles do the same as a single shuffle, so the cup that started on the left is in the middle.",
           "3 karıştırmadan sonra. Soldaki bardak sol > orta > sağ > sol yolunu izler, yani 3 hamleden sonra her bardak yerine döner. Bu karıştırma, S₃ grubunun 3. mertebeden bir elemanı olan bir permütasyondur. 2026 = 3 × 675 + 1 olduğu için 2026 karıştırma tek bir karıştırmayla aynı işi yapar, yani başta solda olan bardak ortadadır."),
]

SAYI_VERI = SAYI(
    10, "Ekim 2026", "October 2026", "Gizli simetriler", "Hidden symmetries",
    {"renkler": ["#2E5E4E", "#1C3D32"], "desen": 0},
    bolumler, quiz, bulmacalar,
    ad="The Unsolvable Equation", ad_tr="Çözülemeyen Denklem",
)
