from dergi import *

bolumler = [
    BOLUM("editor", "edit_note", "#6C63FF", "Editor's Note", "Editörden",
        P(("Hello and welcome to the very first issue of Formül.", "Merhaba, Formül'ün ilk sayısına hoş geldin."),
          ("This is a break-time magazine: short pieces you can finish before your tea gets cold.", "Bu bir teneffüs dergisi: Çayın soğumadan bitirebileceğin kısa yazılar."),
          ("Every sentence is in English, but you are never alone with it.", "Her cümle İngilizce, ama onunla hiçbir zaman yalnız değilsin."),
          ("Tap any sentence and its Turkish translation will appear right below the paragraph.", "Herhangi bir cümleye dokun, Türkçesi paragrafın hemen altında belirecek.")),
        P(("Each month you will find the same skeleton.", "Her ay aynı iskeleti bulacaksın."),
          ("There is news from the world of mathematics, a research paper explained simply, a mathematician of the month and a corner for prizes.", "Matematik dünyasından haberler, sadeleştirilmiş bir araştırma makalesi, ayın matematikçisi ve ödüller köşesi var."),
          ("You will also find thinking strategies, ideas for the classroom and, at the end, a quiz and a puzzle zone.", "Ayrıca düşünme stratejileri, sınıf için fikirler ve en sonda bir quiz ile bulmaca bölümü bulacaksın.")),
        P(("The theme of our first issue is simple: **a new year, new questions**.", "İlk sayımızın teması basit: **yeni bir yıl, yeni sorular**."),
          ("We started 2026 with an artificial intelligence solving a fifty-year-old problem.", "2026'ya, yapay zekânın elli yıllık bir problemi çözmesiyle başladık."),
          ("Let us see what else the year will bring.", "Bakalım yıl bize başka neler getirecek."),
          ("Enjoy your break!", "İyi molalar!")),
    ),

    BOLUM("haber", "newspaper", "#2E86DE", "News from the World of Maths", "Matematik Dünyasından Haberler",
        H("An AI almost solved an Erdős problem on its own", "Yapay zekâ bir Erdős problemini neredeyse kendi başına çözdü"),
        P(("Paul Erdős left hundreds of **open problems** behind him, and he even offered cash prizes for some of them.", "Paul Erdős arkasında yüzlerce **açık problem** bıraktı ve bazılarına para ödülü bile koydu."),
          ("Today these problems are collected and numbered on a website called erdosproblems.com.", "Bugün bu problemler erdosproblems.com adlı bir sitede toplanıp numaralandırılıyor.")),
        P(("In the first days of January 2026, problem number 728 suddenly became famous.", "Ocak 2026'nın ilk günlerinde 728 numaralı problem birden ünlü oldu."),
          ("It is a question from 1975 about the **divisibility** of factorials.", "Faktöriyellerin **bölünebilirliği** hakkında 1975 tarihli bir soru bu."),
          ("A user produced a **proof** with OpenAI's GPT-5.2 Pro model.", "Bir kullanıcı OpenAI'ın GPT-5.2 Pro modeliyle bir **ispat** üretti."),
          ("Then another AI system, called Aristotle, translated the proof into Lean, a language that checks proofs line by line.", "Sonra Aristotle adlı başka bir yapay zekâ sistemi ispatı, ispatları satır satır kontrol eden Lean diline çevirdi.")),
        P(("The famous mathematician Terence Tao described it as a near-autonomous solution that had not appeared in the literature before.", "Ünlü matematikçi Terence Tao bunu, literatürde daha önce görülmemiş, neredeyse otonom bir çözüm olarak tanımladı."),
          ("This matters because in some earlier cases the \"new\" AI solution turned out to be hidden in an old paper.", "Bu önemli, çünkü daha önceki bazı durumlarda \"yeni\" yapay zekâ çözümünün eski bir makalede saklı olduğu ortaya çıkmıştı."),
          ("This time the proof was new, and a machine checked every single step.", "Bu sefer ispat yeniydi ve bir makine her bir adımı kontrol etti.")),
        KUTU("sinif", "For the classroom", "Sınıf için",
             ("Students may ask: \"If AI can solve everything, why should we learn maths?\"", "Öğrenciler sorabilir: \"Yapay zekâ her şeyi çözüyorsa neden matematik öğrenelim?\""),
             ("A good answer: even here, it was mathematicians who asked the right question and judged the result.", "Güzel bir cevap: Burada bile doğru soruyu soran ve sonucu değerlendiren yine matematikçilerdi.")),
        H("2026 is a Fields year", "2026 bir Fields yılı"),
        P(("The **Fields Medal**, one of the most prestigious awards in mathematics, is given every four years.", "Matematiğin en prestijli ödüllerinden biri olan **Fields Madalyası** dört yılda bir verilir."),
          ("The 2026 International Congress of Mathematicians will take place in Philadelphia in July.", "2026 Uluslararası Matematikçiler Kongresi temmuz ayında Philadelphia'da yapılacak."),
          ("Only mathematicians under the age of 40 can receive the medal.", "Madalyayı yalnızca 40 yaşın altındaki matematikçiler alabilir.")),
        TERIMLER(("open problem", "açık problem"), ("proof", "ispat"), ("divisibility", "bölünebilirlik"),
                 ("formal verification", "biçimsel doğrulama"), ("conjecture", "sanı")),
    ),

    BOLUM("makale", "article", "#8E44AD", "Paper of the Month: The Eigenvector Behind Google", "Ayın Makalesi: Google'ı Kuran Özvektör",
        KUTU("bilgi", "Source", "Kaynak",
             ("Sergey Brin and Lawrence Page, The Anatomy of a Large-Scale Hypertextual Web Search Engine, 1998.", "Sergey Brin ve Lawrence Page, Büyük Ölçekli Hipermetin Web Arama Motorunun Anatomisi, 1998."),
             ("They wrote it as PhD students at Stanford.", "Bu makaleyi Stanford'da doktora öğrencisiyken yazdılar.")),
        H("The problem", "Problem"),
        P(("There are billions of web pages.", "Milyarlarca web sayfası var."),
          ("When you search for something, which page should appear first?", "Bir şey aradığında hangi sayfa en üstte çıkmalı?"),
          ("Brin and Page had a simple idea: an important page is a page that important pages link to.", "Brin ve Page'in basit bir fikri vardı: Önemli bir sayfa, önemli sayfaların bağlantı verdiği sayfadır."),
          ("The sentence sounds circular, but in mathematics this kind of definition has a name: an **eigenvalue** problem.", "Cümle döngüsel görünüyor, ama matematikte bu tür bir tanımın adı var: **özdeğer** problemi.")),
        H("Building the model", "Modeli kuralım"),
        P(("Give every page a score r.", "Her sayfaya bir r puanı verelim."),
          ("Each page shares its score equally among the pages it links to.", "Her sayfa puanını, bağlantı verdiği sayfalar arasında eşit olarak paylaştırır."),
          ("If we write this rule with a matrix M, we get a very short equation:", "Bu kuralı bir M matrisiyle yazarsak çok kısa bir denklem elde ederiz:")),
        FORMUL("r = M · r"),
        P(("So the score vector is an **eigenvector** of M with eigenvalue 1.", "Yani puan vektörü, M'nin 1 özdeğerine karşılık gelen bir **özvektörüdür**."),),
        KUTU("ipucu", "A tiny internet", "Minik bir internet",
             ("Imagine three pages: A links to B and C, B links to C, and C links to A.", "Üç sayfa düşün: A, B ve C'ye bağlantı veriyor, B C'ye veriyor, C de A'ya veriyor."),
             ("Solving the equations gives A = 0.4, B = 0.2 and C = 0.4.", "Denklemleri çözünce A = 0,4, B = 0,2 ve C = 0,4 çıkıyor."),
             ("C is strong because two pages point to it, and A is strong because a strong page points to it.", "C güçlü çünkü iki sayfa onu gösteriyor, A güçlü çünkü güçlü bir sayfa onu gösteriyor.")),
        H("The analysis part", "İşin analiz kısmı"),
        P(("On the real internet, some pages link nowhere and some groups of pages only link to each other.", "Gerçek internette bazı sayfalar hiçbir yere bağlantı vermez, bazı sayfa grupları da sadece birbirine bağlantı verir."),
          ("Then the eigenvector may not be unique.", "O zaman özvektör tek olmayabilir."),
          ("Brin and Page added a **damping factor** d, usually about 0.85:", "Brin ve Page genelde 0,85 civarında olan bir **sönümleme katsayısı** d eklediler:")),
        FORMUL("r = d · M · r + (1 − d) / n"),
        P(("Think of a random surfer who clicks a link 85% of the time and jumps to a random page 15% of the time.", "%85 ihtimalle bir bağlantıya tıklayan, %15 ihtimalle rastgele bir sayfaya ışınlanan rastgele bir gezgin düşün."),
          ("With this small change, the Perron–Frobenius theorem guarantees a single positive solution.", "Bu küçük değişiklikle Perron–Frobenius teoremi tek ve pozitif bir çözümü garanti eder."),
          ("In practice the vector is found by **power iteration**: start anywhere and multiply by M again and again.", "Pratikte vektör **kuvvet yöntemiyle** bulunur: Herhangi bir yerden başla ve M ile tekrar tekrar çarp.")),
        KUTU("bilgi", "Graduate corner", "Yüksek lisans köşesi",
             ("This paper connects three courses: linear algebra, probability and numerical analysis.", "Bu makale üç dersi birleştiriyor: lineer cebir, olasılık ve sayısal analiz."),
             ("Markov chains, convergence speed and network centrality are all great thesis topics.", "Markov zincirleri, yakınsama hızı ve ağ merkeziliği harika tez konuları.")),
        TERIMLER(("eigenvector", "özvektör"), ("eigenvalue", "özdeğer"), ("damping factor", "sönümleme katsayısı"),
                 ("power iteration", "kuvvet yöntemi"), ("convergence", "yakınsama"), ("stationary distribution", "durağan dağılım")),
    ),

    BOLUM("bilim", "science", "#0E7490", "Science Corner: The Random Walk of a Pollen Grain", "Bilim Köşesi: Bir Polen Tanesinin Rastgele Yürüyüşü",
        P(("Google's random surfer jumps from page to page without a plan.", "Google'ın rastgele gezgini plansızca sayfadan sayfaya atlar."),
          ("Physicists met the same idea almost a hundred years earlier, inside a drop of water.", "Fizikçiler aynı fikirle neredeyse yüz yıl önce, bir damla suyun içinde karşılaştı.")),
        P(("In 1827 the botanist **Robert Brown** looked at pollen in water under a microscope.", "1827'de botanikçi **Robert Brown** sudaki polenlere mikroskopla baktı."),
          ("Tiny particles from the pollen were moving all the time, in short and nervous zigzags.", "Polenden çıkan minik parçacıklar sürekli, kısa ve huzursuz zikzaklarla hareket ediyordu."),
          ("Today we call this **Brownian motion**.", "Bugün buna **Brown hareketi** diyoruz.")),
        P(("In 1905 Albert Einstein explained it.", "1905'te Albert Einstein bunu açıkladı."),
          ("Water **molecules** hit the particle from every side, millions of times each second.", "Su **molekülleri** parçacığa her yönden, saniyede milyonlarca kez çarpar."),
          ("The hits do not cancel perfectly, so the particle makes a **random walk**.", "Çarpmalar birbirini tam olarak götürmez, bu yüzden parçacık bir **rastgele yürüyüş** yapar."),
          ("A few years later Jean Perrin measured this motion and used it as strong evidence that atoms are real.", "Birkaç yıl sonra Jean Perrin bu hareketi ölçtü ve atomların gerçek olduğuna dair güçlü bir kanıt olarak kullandı.")),
        P(("The surprising part is how far a random walker gets.", "İşin şaşırtıcı yanı, rastgele yürüyen birinin ne kadar uzağa gittiği."),
          ("After n random steps of length 1, the typical distance from the start is not n but about the **square root** of n.", "1 uzunluğunda n rastgele adımdan sonra başlangıca tipik uzaklık n değil, yaklaşık n'nin **karekökü**dür.")),
        FORMUL("typical distance ≈ √n"),
        KUTU("ipucu", "Try it with a coin", "Bir madeni parayla dene",
             ("Stand on a number line at 0 and toss a coin: heads means one step right, tails one step left.", "Sayı doğrusunda 0'da dur ve para at: yazı bir adım sağ, tura bir adım sol demek."),
             ("After 100 tosses you are usually only about 10 steps away from 0.", "100 atıştan sonra genellikle 0'dan yalnızca 10 adım kadar uzaktasın."),
             ("This is why a drop of ink spreads slowly in still water.", "Durgun suda bir damla mürekkebin yavaş yayılmasının nedeni budur.")),
        TERIMLER(("Brownian motion", "Brown hareketi"), ("molecule", "molekül"), ("random walk", "rastgele yürüyüş"),
                 ("square root", "karekök"), ("diffusion", "difüzyon, yayılma")),
    ),

    BOLUM("matematikci", "person", "#E67E22", "Mathematician of the Month: Cahit Arf", "Ayın Matematikçisi: Cahit Arf",
        PORTRE("https://upload.wikimedia.org/wikipedia/commons/f/f7/Cahit_Arf_10_lira.jpg",
               "Cahit Arf", "1910 – 1997",
               "Number theorist, algebraist and one of the founders of modern mathematics in Türkiye.",
               "Sayılar teorisyeni, cebirci ve Türkiye'de modern matematiğin kurucularından biri.",
               "Portrait from the 2009 10-lira banknote · Public domain, Wikimedia Commons"),
        P(("Our first mathematician is a name many of us once carried in our pockets.", "İlk matematikçimiz, birçoğumuzun bir zamanlar cebinde taşıdığı bir isim."),
          ("His portrait and one of his formulas were printed on the back of the 10 lira banknote from 2009.", "Portresi ve formüllerinden biri 2009 serisi 10 liralık banknotun arka yüzüne basılmıştı.")),
        H("His life", "Hayatı"),
        LISTE(("He was born in Thessaloniki in 1910.", "1910'da Selanik'te doğdu."),
              ("He studied mathematics in Paris, at the École Normale Supérieure.", "Matematik eğitimini Paris'te, École Normale Supérieure'de aldı."),
              ("He completed his doctorate in Göttingen in 1938, under Helmut Hasse.", "Doktorasını 1938'de Göttingen'de, Helmut Hasse'nin yanında tamamladı."),
              ("Back in Türkiye, he taught at Istanbul University and played an important role in the early years of TÜBİTAK.", "Türkiye'ye dönünce İstanbul Üniversitesi'nde ders verdi ve TÜBİTAK'ın ilk yıllarında önemli rol oynadı."),
              ("He died in Istanbul in 1997.", "1997'de İstanbul'da hayatını kaybetti.")),
        H("His contributions", "Katkıları"),
        P(("The **Hasse–Arf theorem** describes how prime numbers behave in field extensions, and it is now a standard part of class field theory.", "**Hasse–Arf teoremi** asal sayıların cisim genişlemelerinde nasıl davrandığını anlatır ve bugün sınıf cisim teorisinin standart bir parçasıdır."),
          ("In 1941 he defined the **Arf invariant** to classify quadratic forms over fields of characteristic 2.", "1941'de karakteristiği 2 olan cisimler üzerindeki kuadratik formları sınıflandırmak için **Arf değişmezini** tanımladı."),
          ("Decades later, this algebraic idea found an unexpected home in topology, in knot theory and the classification of manifolds.", "Onlarca yıl sonra bu cebirsel fikir beklenmedik bir yerde, topolojide, düğüm teorisinde ve manifoldların sınıflandırılmasında karşılık buldu.")),
        KUTU("sinif", "For the classroom", "Sınıf için",
             ("Ask your students whose face was on the old 10 lira note.", "Öğrencilerine eski 10 liralıkta kimin yüzü olduğunu sor."),
             ("It is a great way to start talking about a Turkish mathematician who changed world mathematics.", "Dünya matematiğini değiştirmiş bir Türk matematikçi hakkında konuşmaya başlamanın harika bir yolu.")),
        TERIMLER(("quadratic form", "kuadratik form"), ("field extension", "cisim genişlemesi"),
                 ("invariant", "değişmez"), ("ring", "halka"), ("characteristic", "karakteristik")),
    ),

    BOLUM("odul", "emoji_events", "#D4A017", "Prize Corner", "Ödüller Köşesi",
        H("Abel Prize 2025: Masaki Kashiwara", "Abel Ödülü 2025: Masaki Kashiwara"),
        P(("The Abel Prize is often called the closest thing to a Nobel Prize in mathematics.", "Abel Ödülü genellikle matematiğin Nobel'e en yakın ödülü olarak anılır."),
          ("In 2025 it went to Masaki Kashiwara, the first Japanese mathematician to receive it.", "2025'te ödül, onu alan ilk Japon matematikçi olan Masaki Kashiwara'ya verildi."),
          ("He was honoured for his work in algebraic analysis and **representation theory**.", "Cebirsel analiz ve **temsil teorisi** alanındaki çalışmaları için onurlandırıldı."),
          ("His D-module theory lets mathematicians study systems of **differential equations** with the tools of algebra.", "D-modül teorisi, matematikçilerin **diferansiyel denklem** sistemlerini cebirin araçlarıyla incelemesini sağlıyor.")),
        H("Nobel Prize in Physics 2025: quantum in a circuit", "Nobel Fizik 2025: Devredeki kuantum"),
        P(("John Clarke, Michel Devoret and John Martinis showed in the 1980s that an electric circuit you can hold in your hand can behave like a quantum particle.", "John Clarke, Michel Devoret ve John Martinis 1980'lerde, elde tutulabilecek bir elektrik devresinin kuantum parçacığı gibi davranabileceğini gösterdiler."),
          ("In classical physics, a ball cannot cross a hill without enough energy.", "Klasik fizikte bir top, yeterli enerjisi yoksa bir tepeyi aşamaz."),
          ("In quantum mechanics it can \"tunnel\" through, and the chance of this decreases **exponentially** with the width of the barrier.", "Kuantum mekaniğinde ise engelin içinden \"tünelleyebilir\" ve bunun olasılığı engelin genişliğiyle **üstel** olarak azalır."),
          ("Today's superconducting quantum computers are built on these experiments.", "Bugünün süperiletken kuantum bilgisayarları bu deneylerin üzerine kurulu.")),
        KUTU("sinif", "High school link", "Lise bağlantısı",
             ("When you teach exponential functions, ask how the tunnelling probability changes if the barrier gets thicker.", "Üstel fonksiyonları işlerken, engel kalınlaşırsa tünelleme olasılığının nasıl değiştiğini sor.")),
        TERIMLER(("representation theory", "temsil teorisi"), ("differential equation", "diferansiyel denklem"),
                 ("exponential decay", "üstel azalma"), ("laureate", "ödül sahibi")),
    ),

    BOLUM("dusun", "psychology", "#16A085", "Think Like a Mathematician: A Pattern Is Not a Proof", "Matematikçi Gibi Düşünmek: Örüntü Kanıt Değildir",
        P(("Every month we will learn one thinking strategy.", "Her ay bir düşünme stratejisi öğreneceğiz."),
          ("This month's strategy: try small cases and look for a **pattern**.", "Bu ayın stratejisi: Küçük durumları dene ve bir **örüntü** ara."),
          ("But be careful, because a pattern is a hint, not a proof.", "Ama dikkat et, çünkü örüntü bir ipucudur, kanıt değil.")),
        KUTU("soru", "The problem", "Problem",
             ("Put n points on a circle and join every pair with a **chord**.", "Bir çemberin üzerine n nokta koy ve her iki noktayı bir **kirişle** birleştir."),
             ("Into how many regions can the inside of the circle be divided?", "Çemberin içi en fazla kaç bölgeye ayrılabilir?")),
        TABLO(["Points", "1", "2", "3", "4", "5", "6"], ["Regions", "1", "2", "4", "8", "16", "?"]),
        P(("The pattern looks obvious: the number doubles every time, so the next answer should be 32.", "Örüntü apaçık görünüyor: Sayı her seferinde ikiye katlanıyor, o hâlde sonraki cevap 32 olmalı."),
          ("Surprisingly, the correct answer for 6 points is **31**.", "Şaşırtıcı şekilde 6 nokta için doğru cevap **31**.")),
        FORMUL("regions = C(n, 4) + C(n, 2) + 1"),
        P(("Every crossing point inside the circle comes from a group of 4 points, and every chord adds one more region.", "Çemberin içindeki her kesişim noktası 4 noktalık bir gruptan gelir ve her kiriş bir bölge daha ekler."),
          ("For n = 6 we get 15 + 15 + 1 = 31.", "n = 6 için 15 + 15 + 1 = 31 buluruz.")),
        KUTU("ipucu", "The lesson", "Ders",
             ("Mathematicians love patterns but never trust them.", "Matematikçiler örüntüleri sever ama onlara asla güvenmez."),
             ("Drawing 6 points on the board and counting 31 regions is an unforgettable moment in class.", "Tahtaya 6 nokta çizip 31 bölgeyi saydırmak sınıfta unutulmaz bir an.")),
        TERIMLER(("pattern", "örüntü"), ("chord", "kiriş"), ("region", "bölge"), ("counterexample", "karşı örnek"),
                 ("binomial coefficient", "binom katsayısı")),
    ),

    BOLUM("eglence", "lightbulb", "#E84393", "Fun Facts: The Secrets of 2026", "Eğlenceli Bilgiler: 2026 Sayısının Sırları",
        LISTE(("2025 was a **perfect square**: 2025 = 45², and also 2025 = (1 + 2 + … + 9)².", "2025 bir **tam kareydi**: 2025 = 45², ayrıca 2025 = (1 + 2 + … + 9)²."),
              ("2026 = 45² + 1², so it is a sum of two squares.", "2026 = 45² + 1², yani iki kare toplamı."),
              ("2026 = 2 × 1013, and 1013 is a **prime number**.", "2026 = 2 × 1013 ve 1013 bir **asal sayı**."),
              ("If you could fold a 0.1 mm sheet of paper 42 times, it would be thicker than the distance to the Moon.", "0,1 mm'lik bir kâğıdı 42 kez katlayabilseydin, kalınlığı Ay'a olan uzaklıktan fazla olurdu."),
              ("A year has 31,536,000 seconds, which is surprisingly close to π × 10⁷.", "Bir yıl 31.536.000 saniye ve bu şaşırtıcı derecede π × 10⁷'ye yakın.")),
        TERIMLER(("perfect square", "tam kare"), ("prime number", "asal sayı"),
                 ("sum of two squares", "iki kare toplamı"), ("exponential growth", "üstel büyüme")),
    ),

    BOLUM("sinif", "school", "#27AE60", "In the Classroom", "Sınıfta Matematik",
        H("Grades 6–8: The 2026 Game", "6-8. sınıflar: 2026 Oyunu"),
        P(("Use the digits 2, 0, 2 and 6 exactly once each to make the numbers from 1 to 30.", "2, 0, 2 ve 6 rakamlarını her birini tam bir kez kullanarak 1'den 30'a kadar sayıları elde edin."),
          ("The four operations, brackets, powers and square roots are all allowed, and you may also join digits, as in 20 or 26.", "Dört işlem, parantez, üs ve karekök serbest, rakamları 20 ya da 26 gibi yan yana da yazabilirsiniz."),
          ("For example, 1 = (6 − 2 − 2)⁰ and 28 = 26 + 2 + 0.", "Örneğin 1 = (6 − 2 − 2)⁰ ve 28 = 26 + 2 + 0.")),
        KUTU("sinif", "Variation", "Varyasyon",
             ("Play in groups for 15 minutes, and put the numbers nobody could find on the wall as \"open problems\".", "15 dakika gruplar hâlinde oynayın ve kimsenin bulamadığı sayıları \"açık problem\" olarak panoya asın."),
             ("Just like Erdős did!", "Tıpkı Erdős'ün yaptığı gibi!")),
        H("High school: Fold the paper to the Moon", "Lise: Kâğıdı Ay'a katla"),
        P(("Give each student a sheet of A4 paper and let them see how many times they can fold it.", "Her öğrenciye bir A4 kâğıt verin ve kaç kez katlayabildiklerini görsünler."),
          ("If the paper is 0.1 mm thick, after n folds it is 0.1 × 2ⁿ mm thick.", "Kâğıt 0,1 mm kalınlığındaysa n katlamadan sonra kalınlığı 0,1 × 2ⁿ mm olur."),
          ("Using logarithms, students can find that 42 folds are enough to reach the Moon.", "Öğrenciler logaritma kullanarak Ay'a ulaşmak için 42 katlamanın yettiğini bulabilir.")),
        FORMUL("2ⁿ ≥ 3.84 × 10¹²  ⟹  n ≥ 41.8"),
        TERIMLER(("order of operations", "işlem önceliği"), ("exponent", "üs"), ("logarithm", "logaritma"), ("estimate", "tahmin etmek")),
    ),

    BOLUM("gundem", "campaign", "#C0392B", "Education in Türkiye", "Eğitim Gündemi",
        H("Where is the new curriculum?", "Yeni müfredat hangi sınıflarda?"),
        P(("In the 2025–2026 school year, the Türkiye Century Education Model is being introduced step by step.", "2025-2026 eğitim öğretim yılında Türkiye Yüzyılı Maarif Modeli kademeli olarak uygulanıyor."),
          ("In mathematics this means grades 5 and 6 in middle school and grades 9 and 10 in high school.", "Matematikte bu, ortaokulda 5 ve 6. sınıflar, lisede 9 ve 10. sınıflar demek."),
          ("So a teacher with grade 6 and grade 7 classes works with two different programmes this year.", "Yani 6. ve 7. sınıfları okutan bir öğretmen bu yıl iki farklı programla çalışıyor.")),
        H("LGS 2026", "LGS 2026"),
        P(("LGS will take place on Saturday, 13 June 2026, in two sessions.", "LGS 13 Haziran 2026 Cumartesi günü, iki oturumda yapılacak."),
          ("Mathematics is in the second session together with science: 40 questions in 80 minutes.", "Matematik, fen bilimleriyle birlikte ikinci oturumda: 80 dakikada 40 soru."),
          ("January is a good time to analyse mock exam results before the second term.", "Ocak, ikinci dönemden önce deneme sınavı sonuçlarını analiz etmek için iyi bir zaman.")),
        TERIMLER(("curriculum", "müfredat"), ("learning outcome", "kazanım"), ("mock exam", "deneme sınavı"), ("term", "dönem")),
    ),

    BOLUM("oku", "menu_book", "#34495E", "Read Like a Mathematician", "Matematikçi Gibi Oku",
        P(("Every paper and textbook uses the same small phrases.", "Her makale ve ders kitabı aynı küçük kalıpları kullanır."),
          ("Once you know them, reading a proof in English becomes much easier.", "Onları tanıdığında İngilizce bir ispatı okumak çok daha kolaylaşır.")),
        TABLO(["English", "Türkçe"],
              ["Let x be …", "x … olsun"],
              ["Suppose that …", "… olduğunu varsayalım"],
              ["if and only if (iff)", "ancak ve ancak"],
              ["It follows that …", "buradan … çıkar"],
              ["Without loss of generality", "genelliği bozmadan"],
              ["Q.E.D. / ∎", "ispat bitti"]),
        KUTU("soru", "Mini reading", "Mini okuma",
             ("Claim: If n² is even, then n is even.", "İddia: n² çiftse n de çifttir."),
             ("Proof: Suppose that n is odd, so n = 2k + 1 for some integer k.", "İspat: n'nin tek olduğunu varsayalım, yani bir k tam sayısı için n = 2k + 1."),
             ("It follows that n² = 4k² + 4k + 1, which is odd.", "Buradan n² = 4k² + 4k + 1 çıkar ve bu tektir."),
             ("This contradicts our assumption. ∎", "Bu varsayımımızla çelişir. ∎")),
        TERIMLER(("proof by contradiction", "olmayana ergi"), ("contrapositive", "karşıt ters"),
                 ("assumption", "varsayım"), ("claim", "iddia")),
    ),
]

quiz = [
    SORU("Which AI system checked the proof of Erdős problem 728 in Lean?", "Erdős 728 probleminin ispatını Lean'de hangi yapay zekâ sistemi kontrol etti?",
         ["GPT-5.2 Pro", "Aristotle", "Gemini", "AlphaGo"], 1,
         "GPT-5.2 Pro wrote the proof, and Aristotle formalised it in Lean.", "İspatı GPT-5.2 Pro yazdı, Aristotle ise Lean'de biçimselleştirdi."),
    SORU("In PageRank, the score vector r satisfies r = M · r. What is r?", "PageRank'te puan vektörü r, r = M · r eşitliğini sağlar. r nedir?",
         ["A determinant", "An eigenvector of M", "The inverse of M", "A random number"], 1,
         "r is an eigenvector of M with eigenvalue 1.", "r, M'nin 1 özdeğerine karşılık gelen özvektörüdür."),
    SORU("What is the usual value of the damping factor d?", "Sönümleme katsayısı d genelde kaçtır?",
         ["0.15", "0.5", "0.85", "1"], 2,
         "The random surfer follows a link 85% of the time.", "Rastgele gezgin %85 ihtimalle bir bağlantıyı takip eder."),
    SORU("Cahit Arf defined his invariant to classify …", "Cahit Arf, değişmezini neyi sınıflandırmak için tanımladı?",
         ["prime numbers", "quadratic forms", "triangles", "fractals"], 1,
         "The Arf invariant classifies quadratic forms in characteristic 2.", "Arf değişmezi karakteristik 2'deki kuadratik formları sınıflandırır."),
    SORU("With 6 points on a circle, how many regions do the chords make?", "Çemberdeki 6 nokta için kirişler kaç bölge oluşturur?",
         ["30", "31", "32", "36"], 1,
         "C(6,4) + C(6,2) + 1 = 15 + 15 + 1 = 31, not 32.", "C(6,4) + C(6,2) + 1 = 15 + 15 + 1 = 31, 32 değil."),
    SORU("Which phrase means \"genelliği bozmadan\"?", "Hangi kalıp \"genelliği bozmadan\" anlamına gelir?",
         ["It follows that", "If and only if", "Without loss of generality", "Suppose that"], 2,
         "WLOG = without loss of generality.", "WLOG, without loss of generality'nin kısaltmasıdır."),
]

bulmacalar = [
    ANAGRAM("TGNANTE", "TANGENT", "A line that touches a curve at one point.", "Bir eğriye tek noktada dokunan doğru."),
    ANAGRAM("RMIEP", "PRIME", "Divisible only by 1 and itself.", "Sadece 1'e ve kendisine bölünür."),
    ANAGRAM("TIRMXA", "MATRIX", "Numbers arranged in rows and columns.", "Satır ve sütunlara dizilmiş sayılar."),
    ANAGRAM("FROPO", "PROOF", "What a mathematician must write.", "Bir matematikçinin yazması gereken şey."),
    ESLESTIR("Match the terms", "Terimleri eşleştir",
             ("eigenvector", "özvektör"), ("chord", "kiriş"), ("prime number", "asal sayı"),
             ("invariant", "değişmez"), ("convergence", "yakınsama")),
    MANTIK("Who is the liar?", "Yalancı kim?",
           "Ayşe, Burak and Cem: one always tells the truth, one always lies, one sometimes lies. Ayşe: \"Burak always lies.\" Burak: \"Cem always tells the truth.\" Cem: \"I sometimes lie.\" Who is who?",
           "Ayşe, Burak ve Cem'den biri hep doğru söyler, biri hep yalan söyler, biri bazen yalan söyler. Ayşe: \"Burak hep yalan söyler.\" Burak: \"Cem hep doğru söyler.\" Cem: \"Ben bazen yalan söylerim.\" Kim hangisi?",
           "Cem cannot always tell the truth or always lie, so he sometimes lies. Then Burak's sentence is false, so Burak always lies, and Ayşe always tells the truth.",
           "Cem hep doğru da hep yalancı da olamaz, demek ki bazen yalan söyleyen o. O zaman Burak'ın sözü yanlış, yani Burak hep yalancı. Ayşe de hep doğru söyleyen."),
    MANTIK("The year puzzle", "Yılın bulmacası",
           "What is the largest number of consecutive positive integers whose sum is 2026?",
           "Toplamı 2026 olan en fazla kaç ardışık pozitif tam sayı vardır?",
           "Four: 505 + 506 + 507 + 508 = 2026.",
           "Dört: 505 + 506 + 507 + 508 = 2026."),
]

SAYI_VERI = SAYI(
    1, "Ocak 2026", "January 2026", "Yeni bir yıl, yeni sorular", "A new year, new questions",
    {"renkler": ["#2B4C7E", "#1C3354"], "desen": 1},
    bolumler, quiz, bulmacalar,
    ad="The Proof Machine", ad_tr="İspat Makinesi",
)
