from dergi import *

bolumler = [
    BOLUM("editor", "edit_note", "#6C63FF", "Editor's Note", "Editörden",
        P(("Hello again!", "Yeniden merhaba!"),
          ("March may be the favourite month of mathematicians.", "Mart, matematikçilerin en sevdiği ay olabilir."),
          ("On 14 March the whole world celebrates **Pi Day**, which UNESCO has also declared the **International Day of Mathematics**.", "14 Mart'ta bütün dünya **Pi Günü**'nü kutluyor ve UNESCO bu günü aynı zamanda **Uluslararası Matematik Günü** ilan etti."),
          ("In the middle of the month, the winner of the Abel Prize, one of the biggest prizes in mathematics, is announced.", "Ayın ortasında da matematiğin en büyük ödüllerinden biri olan Abel Ödülü'nün sahibi açıklanıyor.")),
        P(("This month's theme is **measuring the infinite**.", "Bu ayın teması **sonsuzu ölçmek**."),
          ("You will meet π, a number that never ends.", "Bitmeyen bir sayı olan π ile tanışacaksın."),
          ("You will meet Claude Shannon, who found a way to measure the information in a message.", "Bir mesajdaki bilginin nasıl ölçüleceğini bulan Claude Shannon ile tanışacaksın."),
          ("And you will meet Gerd Faltings, who answered the question \"infinitely many or finitely many?\" after 60 years.", "Ve \"sonsuz çoklukta mı, sonlu mu?\" sorusunu 60 yıl sonra cevaplayan Gerd Faltings ile tanışacaksın.")),
        P(("Because 8 March is International Women's Day, our mathematician of the month is **Emmy Noether**, often called the mother of modern algebra.", "8 Mart Dünya Kadınlar Günü olduğu için ayın matematikçisi, çoğu zaman modern cebirin annesi olarak anılan **Emmy Noether**."),
          ("Enjoy your break!", "İyi molalar!")),
    ),

    BOLUM("haber", "newspaper", "#2E86DE", "News from the World of Maths", "Matematik Dünyasından Haberler",
        H("The 2026 Abel Prize goes to Gerd Faltings", "Abel Ödülü 2026 Gerd Faltings'in"),
        P(("On 19 March 2026, the Norwegian Academy of Science and Letters gave this year's Abel Prize to the German mathematician **Gerd Faltings**.", "Norveç Bilim Akademisi 19 Mart 2026'da bu yılın Abel Ödülü'nü Alman matematikçi **Gerd Faltings**'e verdi."),
          ("He was honoured for bringing powerful tools to **arithmetic geometry**.", "Aritmetik geometriye güçlü araçlar kazandırdığı için onurlandırıldı."),
          ("He also resolved the **long-standing** conjectures of Mordell and Lang.", "Ayrıca Mordell ve Lang'ın **uzun süredir açık duran** sanılarını çözdü."),
          ("Today Faltings works at the Max Planck Institute for Mathematics in Bonn.", "Faltings bugün Bonn'daki Max Planck Matematik Enstitüsü'nde çalışıyor."),
          ("You can read the full story in this issue's Prize Corner.", "Ödülün hikâyesinin tamamını bu sayının Ödüller Köşesi'nde okuyabilirsin.")),
        H("14 March: Pi Day and the International Day of Mathematics", "14 Mart: Pi Günü ve Uluslararası Matematik Günü"),
        P(("In the American date format, 14 March is written as \"3/14\".", "Amerikan tarih yazımında 14 Mart \"3/14\" diye yazılıyor."),
          ("This reminds us of 3.14, the first digits of π.", "Bu da bize π'nin ilk basamakları olan 3,14'ü hatırlatıyor."),
          ("The celebration started as Pi Day, and in 2019 UNESCO **proclaimed** it the **International Day of Mathematics**.", "Kutlama Pi Günü olarak başladı ve 2019'da UNESCO onu **Uluslararası Matematik Günü** olarak **ilan etti**."),
          ("Since 2020 it has been celebrated all over the world.", "2020'den beri tüm dünyada kutlanıyor."),
          ("Every year there is a theme, and schools organise events.", "Her yıl bir tema belirleniyor ve okullar etkinlikler düzenliyor."),
          ("The classroom activities in this issue were designed for exactly this day.", "Bu sayıdaki sınıf etkinlikleri tam da bu gün için tasarlandı.")),
        H("Four months to the Fields Medal", "Fields'a dört ay kaldı"),
        P(("There are four months left until the International Congress of Mathematicians (ICM) in Philadelphia in July.", "Temmuz'da Philadelphia'da yapılacak Uluslararası Matematikçiler Kongresi'ne (ICM) dört ay kaldı."),
          ("People have already started talking about possible winners of the **Fields Medal**.", "İnsanlar şimdiden olası **Fields Madalyası** sahiplerini konuşmaya başladı."),
          ("Remember that the medal only goes to mathematicians who have not turned 40 by 1 January of the congress year.", "Unutma, madalya yalnızca kongre yılının 1 Ocak tarihinde 40 yaşını doldurmamış matematikçilere veriliyor.")),
        TERIMLER(("arithmetic geometry", "aritmetik geometri"), ("long-standing", "uzun süredir (açık) duran"),
                 ("to resolve a conjecture", "bir sanıyı çözmek"), ("to proclaim", "ilan etmek")),
    ),

    BOLUM("makale", "article", "#8E44AD", "Paper of the Month: The Mathematics of Information", "Ayın Makalesi: Bilginin Matematiği",
        KUTU("bilgi", "Source", "Kaynak",
             ("Claude E. Shannon, A Mathematical Theory of Communication, Bell System Technical Journal, 1948.", "Claude E. Shannon, İletişimin Matematiksel Bir Teorisi, Bell System Technical Journal, 1948.")),
        H("The problem", "Problem"),
        P(("In everyday life, \"information\" is a vague word.", "Günlük hayatta \"bilgi\" belirsiz bir kelime."),
          ("How much information is there in a message?", "Bir mesajda ne kadar bilgi var?"),
          ("Can we even measure it?", "Bunu ölçebilir miyiz?"),
          ("In 1948, Claude Shannon, a young engineer and mathematician at Bell Labs, gave such a clear answer that today's whole digital world is built on his paper.", "1948'de Bell Laboratuvarları'nda çalışan genç mühendis ve matematikçi Claude Shannon bu soruya öyle net bir cevap verdi ki, bugünkü dijital dünyanın tamamı onun makalesinin üzerine kuruldu.")),
        H("The key idea: information is surprise", "Temel fikir: Bilgi, şaşkınlıktır"),
        P(("If I tell you that the sun will rise tomorrow, I give you no information, because you already know it.", "Yarın güneşin doğacağını söylersem sana hiç bilgi vermiş olmam, çünkü bunu zaten biliyorsun."),
          ("But if I tell you that it will snow tomorrow, especially in June, I give you a lot of information.", "Ama yarın kar yağacağını söylersem, hele haziranda, sana çok bilgi vermiş olurum."),
          ("Shannon's idea was this: the information in an event is measured by how unexpected it is.", "Shannon'ın fikri şuydu: Bir olayın taşıdığı bilgi, ne kadar beklenmedik olduğuyla ölçülür."),
          ("An event with probability p carries this much information, measured in **bits**:", "Olasılığı p olan bir olay, **bit** cinsinden şu kadar bilgi taşır:")),
        FORMUL("I = log₂(1/p)"),
        LISTE(("Heads or tails: p = 1/2, so the information is log₂(2) = 1 bit.", "Yazı tura: p = 1/2, yani bilgi log₂(2) = 1 bit."),
              ("Rolling a 6 with a die: p = 1/6, so the information is log₂(6) ≈ 2.58 bits.", "Zarla 6 atmak: p = 1/6, yani bilgi log₂(6) ≈ 2,58 bit."),
              ("Guessing one number out of 1024: log₂(1024) = 10 bits.", "1024 sayıdan birini tahmin etmek: log₂(1024) = 10 bit.")),
        H("Entropy", "Entropi"),
        P(("The average information that a source produces is called its **entropy**:", "Bir kaynağın ortalama olarak ürettiği bilgiye **entropi** denir:")),
        FORMUL("H = −Σ pᵢ · log₂(pᵢ)"),
        P(("For a fair coin, H = 1 bit.", "Hilesiz bir para için H = 1 bit."),
          ("For an unfair coin that lands heads 90% of the time and tails 10% of the time, H ≈ 0.47 bits.", "%90 yazı, %10 tura gelen hileli bir para için H ≈ 0,47 bit."),
          ("The unfair coin is easier to predict, so each toss carries less information.", "Hileli para daha kolay tahmin ediliyor, bu yüzden her atış daha az bilgi taşıyor.")),
        KUTU("ipucu", "The big result", "Büyük sonuç",
             ("Shannon proved that a message cannot be compressed below its entropy **without losing any information**.", "Shannon, bir mesajın **hiçbir bilgi kaybetmeden** entropisinin altına sıkıştırılamayacağını kanıtladı."),
             ("ZIP files, JPEGs and MP3s all live with this limit.", "ZIP dosyaları, JPEG'ler ve MP3'ler bu sınırla yaşıyor.")),
        H("The noisy channel", "Gürültülü kanal"),
        P(("The second half of the paper is even more surprising.", "Makalenin ikinci yarısı daha da şaşırtıcı."),
          ("When you send a message through a noisy line, such as a telephone cable or a radio wave, errors seem impossible to avoid.", "Telefon kablosu ya da radyo dalgası gibi gürültülü bir hattan mesaj gönderdiğinde hatalar kaçınılmaz görünür."),
          ("Shannon proved that every channel has a **capacity** C.", "Shannon, her kanalın bir **kapasitesi** (C) olduğunu kanıtladı."),
          ("Below this capacity, there **exist** codes that make the chance of an error as small as we want.", "Bu kapasitenin altındaki hızlarda, hata olasılığını istediğimiz kadar küçük yapan kodlar **vardır**.")),
        P(("The interesting part is that the proof did not tell us how to find these codes.", "İşin ilginç yanı, ispat bu kodları nasıl bulacağımızı söylemiyordu."),
          ("It only showed that they exist.", "Sadece var olduklarını gösteriyordu."),
          ("Engineers found codes that really come close to this limit only in the 1990s.", "Mühendisler bu sınıra gerçekten yaklaşan kodları ancak 1990'larda bulabildi."),
          ("Today mobile phones and satellite communication use these codes.", "Bugün cep telefonları ve uydu haberleşmesi bu kodları kullanıyor.")),
        KUTU("soru", "Try it: the yes-no game", "Dene: Evet-hayır oyunu",
             ("I am thinking of a number between 1 and 1000, and you may only ask yes-no questions.", "1 ile 1000 arasında bir sayı tuttum ve sadece evet-hayır soruları sorabilirsin."),
             ("Each answer gives you at most 1 bit, and you need log₂(1000) ≈ 9.97 bits.", "Her cevap sana en fazla 1 bit verir ve senin log₂(1000) ≈ 9,97 bite ihtiyacın var."),
             ("So you need at least **10 questions**, and since 2¹⁰ = 1024 ≥ 1000, ten questions are enough.", "Yani en az **10 soru** gerekir ve 2¹⁰ = 1024 ≥ 1000 olduğu için on soru yeterlidir."),
             ("The strategy is to cut the remaining range in half each time: \"Is the number greater than 500?\"", "Strateji, kalan aralığı her seferinde ikiye bölmek: \"Sayı 500'den büyük mü?\"")),
        KUTU("bilgi", "Graduate corner", "Yüksek lisans köşesi",
             ("This paper is directly connected to **probability theory**, **combinatorics** and **analysis**.", "Bu makale **olasılık teorisi**, **kombinatorik** ve **analiz** dersleriyle doğrudan bağlantılı."),
             ("Shannon's noisy channel proof uses \"random coding\": to show that a good object exists, you pick a random one and prove that it is good on average.", "Shannon'ın gürültülü kanal ispatı \"rastgele kodlama\" kullanır: İyi bir nesnenin var olduğunu göstermek için rastgele bir nesne seçer ve ortalamada iyi olduğunu kanıtlarsın."),
             ("In combinatorics, this technique is known as the **probabilistic method**, and Erdős loved it.", "Kombinatorikte bu teknik **olasılıksal yöntem** olarak bilinir ve Erdős onu çok severdi."),
             ("Remember the Erdős news in our January issue?", "Ocak sayımızdaki Erdős haberini hatırlıyor musun?")),
        TERIMLER(("entropy", "entropi"), ("bit (binary digit)", "bit, ikili basamak"), ("channel capacity", "kanal kapasitesi"),
                 ("noise", "gürültü"), ("existence proof", "varlık ispatı"), ("probabilistic method", "olasılıksal yöntem")),
    ),

    BOLUM("bilim", "science", "#0E7490", "Science Corner: DNA, Nature's Information Code", "Bilim Köşesi: DNA, Doğanın Bilgi Kodu",
        P(("Shannon's bits are not only inside computers.", "Shannon'ın bitleri yalnızca bilgisayarların içinde değil."),
          ("Every living cell also stores and copies information, and it uses a code written in **DNA**.", "Her canlı hücre de bilgi saklar ve kopyalar ve bunun için **DNA**'ya yazılmış bir kod kullanır."),
          ("Let us look at this code with the eyes of a mathematician.", "Bu koda bir matematikçinin gözüyle bakalım.")),
        P(("DNA is a long chain made of four building blocks called **bases**: A, T, G and C.", "DNA, **baz** adı verilen dört yapı taşından oluşan uzun bir zincirdir: A, T, G ve C."),
          ("If all four bases were equally likely, each position would carry log₂(4) = 2 bits of information.", "Dört bazın hepsi eşit olasılıklı olsaydı, her konum log₂(4) = 2 bit bilgi taşırdı."),
          ("So a short piece of DNA, like a short message, can be measured in bits.", "Yani kısa bir DNA parçası, kısa bir mesaj gibi bit cinsinden ölçülebilir.")),
        P(("The cell reads DNA in groups of three bases, called **codons**.", "Hücre DNA'yı **kodon** adı verilen üçlü baz grupları hâlinde okur."),
          ("With four letters in three positions, there are 4³ = 64 different codons.", "Üç konumda dört harfle 4³ = 64 farklı kodon vardır."),
          ("But proteins are built from only 20 kinds of **amino acids**, and a few codons simply mean \"stop\".", "Ama proteinler yalnızca 20 çeşit **amino asitten** yapılır ve birkaç kodon sadece \"dur\" anlamına gelir."),
          ("This means that most amino acids have more than one codon.", "Bu da çoğu amino asidin birden fazla kodonu olduğu anlamına gelir.")),
        P(("This extra room, called **redundancy**, is useful.", "**Fazlalık** denen bu ekstra alan işe yarar."),
          ("A small copying error, especially in the third base of a codon, often gives the same amino acid.", "Özellikle bir kodonun üçüncü bazındaki küçük bir kopyalama hatası çoğu zaman aynı amino asidi verir."),
          ("Shannon would recognise the idea: extra symbols make a message more robust against noise.", "Shannon bu fikri tanırdı: Fazladan semboller bir mesajı gürültüye karşı daha dayanıklı yapar.")),
        KUTU("ipucu", "A quick calculation", "Hızlı bir hesap",
             ("The human genome has about 3 billion base pairs.", "İnsan genomunda yaklaşık 3 milyar baz çifti vardır."),
             ("At 2 bits per base, that is about 6 billion bits.", "Baz başına 2 bitten bu yaklaşık 6 milyar bit eder."),
             ("Since 8 bits make a byte, one copy of your genome fits in roughly 750 megabytes, about the size of a CD.", "8 bit bir bayt ettiği için genomunun bir kopyası kabaca 750 megabayta, yani yaklaşık bir CD boyutuna sığar.")),
        TERIMLER(("base (in DNA)", "baz (DNA'da)"), ("codon", "kodon"), ("amino acid", "amino asit"),
                 ("redundancy", "fazlalık, artıklık"), ("genome", "genom")),
    ),

    BOLUM("matematikci", "person", "#E67E22", "Mathematician of the Month: Emmy Noether", "Ayın Matematikçisi: Emmy Noether",
        PORTRE("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Noether.jpg/400px-Noether.jpg",
               "Emmy Noether", "1882 – 1935",
               "German mathematician, a founder of modern abstract algebra and the author of Noether's theorem in physics.",
               "Modern soyut cebirin kurucularından, fizikteki Noether teoreminin sahibi Alman matematikçi.",
               "Photograph, before 1910 · Public domain, Wikimedia Commons"),
        P(("Emmy Noether lived from 1882 to 1935.", "Emmy Noether 1882 ile 1935 yılları arasında yaşadı."),
          ("After her death, Albert Einstein wrote a letter about her.", "Ölümünün ardından Albert Einstein onun hakkında bir mektup yazdı."),
          ("He called her the most important creative mathematical genius since women were allowed into higher education.", "Onu, kadınlara yükseköğretimin açılmasından bu yana yetişmiş en önemli yaratıcı matematik dehası olarak andı.")),
        H("Her life", "Hayatı"),
        LISTE(("She was born in 1882 in Erlangen, Germany, as the daughter of a mathematics professor.", "1882'de Almanya'nın Erlangen şehrinde, bir matematik profesörünün kızı olarak doğdu."),
              ("In those years, it was almost impossible for women to enrol at a university.", "O yıllarda kadınların üniversiteye kaydolması neredeyse imkânsızdı."),
              ("At first she could only attend lectures as a guest listener.", "Derslere önce yalnızca misafir dinleyici olarak girebildi."),
              ("In 1915, David Hilbert and Felix Klein, two of the greatest mathematicians of the time, invited her to the University of Göttingen.", "1915'te dönemin en büyük matematikçilerinden David Hilbert ve Felix Klein onu Göttingen Üniversitesi'ne davet etti."),
              ("But the faculty refused to give a teaching position to a woman, so for years her lectures were announced **under Hilbert's name**.", "Ama fakülte bir kadına öğretim üyeliği vermeye karşı çıktı, bu yüzden dersleri yıllarca **Hilbert'in adıyla** ilan edildi."),
              ("Hilbert is said to have protested that the faculty was not a bathhouse.", "Hilbert'in fakültenin bir hamam olmadığını söyleyerek itiraz ettiği anlatılır."),
              ("In 1933 the Nazi regime removed her from the university because she was Jewish, and she moved to Bryn Mawr College in the USA.", "1933'te Nazi rejimi Yahudi olduğu için onu üniversiteden uzaklaştırdı ve o da ABD'deki Bryn Mawr Koleji'ne geçti."),
              ("She died in 1935, at the age of 53, after an operation.", "1935'te, 53 yaşındayken bir ameliyatın ardından hayatını kaybetti.")),
        H("Noether's theorem (1918)", "Noether teoremi (1918)"),
        P(("This is one of the deepest results in physics.", "Bu, fiziğin en derin sonuçlarından biri."),
          ("It says that every **symmetry** corresponds to a **conservation law**.", "Her **simetrinin** bir **korunum yasasına** karşılık geldiğini söyler.")),
        LISTE(("If the laws of physics do not change with time, **energy** is conserved.", "Fizik yasaları zamanla değişmiyorsa **enerji** korunur."),
              ("If the laws of physics are the same everywhere in space, **momentum** is conserved.", "Fizik yasaları uzayın her yerinde aynıysa **momentum** korunur."),
              ("If the laws of physics do not depend on direction, **angular momentum** is conserved.", "Fizik yasaları yönden bağımsızsa **açısal momentum** korunur.")),
        P(("Remember the \"find the invariant\" strategy from our February issue.", "Şubat sayımızdaki \"değişmezi bul\" stratejisini hatırla."),
          ("Noether's theorem tells us that nature itself also works with invariants.", "Noether teoremi, doğanın kendisinin de değişmezlerle çalıştığını söylüyor.")),
        H("Abstract algebra", "Soyut cebir"),
        P(("Noether moved algebra away from calculation techniques and turned it into a field built on **structures**.", "Noether cebiri hesaplama tekniklerinden uzaklaştırıp **yapılar** üzerine kurulu bir alana dönüştürdü."),
          ("Much of the language we learn today about rings, **ideals** and modules comes from her and her students.", "Bugün halkalar, **idealler** ve modüller hakkında öğrendiğimiz dilin büyük kısmı ondan ve öğrencilerinden geliyor."),
          ("Rings that satisfy a certain condition are now called **Noetherian rings** in her honour.", "Belirli bir koşulu sağlayan halkalara bugün onun onuruna **Noether halkaları** deniyor.")),
        KUTU("sinif", "For the classroom", "Sınıf için",
             ("On 8 March, ask your students: \"Can you name a woman mathematician?\"", "8 Mart'ta öğrencilerine sor: \"Bir kadın matematikçi sayabilir misin?\""),
             ("There are usually only a few answers.", "Cevaplar genelde azdır."),
             ("It is a great day to tell the stories of Noether, Mirzakhani and Hypatia.", "Noether, Mirzakhani ve Hypatia'nın hikâyelerini anlatmak için harika bir gün.")),
        TERIMLER(("symmetry", "simetri"), ("conservation law", "korunum yasası"), ("abstract algebra", "soyut cebir"),
                 ("ideal", "ideal"), ("momentum", "momentum")),
    ),

    BOLUM("odul", "emoji_events", "#D4A017", "Prize Corner", "Ödüller Köşesi",
        H("Abel 2026: Gerd Faltings and \"finitely many\"", "Abel 2026: Gerd Faltings ve \"sonlu çoklukta\""),
        P(("One of the oldest questions in mathematics is this: what are the fractional, or **rational**, solutions of a polynomial equation with integer coefficients?", "Matematiğin en eski sorularından biri şudur: Tam sayı katsayılı bir polinom denkleminin kesirli, yani **rasyonel** çözümleri nelerdir?"),
          ("Such equations are called **Diophantine equations**.", "Bu tür denklemlere **Diofant denklemleri** denir."),
          ("Some of them have no rational solutions, and some have infinitely many.", "Bazılarının hiç rasyonel çözümü yoktur, bazılarının sonsuz tane vardır."),
          ("For example, the circle x² + y² = 1 has infinitely many **rational points**, such as (3/5, 4/5).", "Örneğin x² + y² = 1 çemberinin (3/5, 4/5) gibi sonsuz tane **rasyonel noktası** vardır."),
          ("So which equations have only **finitely many** solutions?", "Peki hangi denklemlerin yalnızca **sonlu sayıda** çözümü olur?")),
        P(("In 1922, the British mathematician Louis Mordell guessed that the answer depends on the geometric shape of the equation.", "1922'de İngiliz matematikçi Louis Mordell, cevabın denklemin geometrik şekline bağlı olduğunu tahmin etti."),
          ("Roughly speaking, the equation draws a surface over the complex numbers.", "Kabaca söylersek, denklem karmaşık sayılar üzerinde bir yüzey çizer."),
          ("If this surface has two or more holes, which means its **genus** is at least 2, the number of rational solutions is finite.", "Bu yüzeyin iki veya daha fazla deliği varsa, yani **cinsi** en az 2 ise, rasyonel çözüm sayısı sonludur.")),
        P(("Nobody could prove this conjecture for 60 years.", "Bu sanıyı 60 yıl boyunca kimse kanıtlayamadı."),
          ("In 1983, at the age of 29, Faltings proved it with new tools that joined algebraic geometry and number theory.", "1983'te, 29 yaşındaki Faltings onu cebirsel geometri ile sayılar teorisini birleştiren yeni araçlarla kanıtladı."),
          ("This proof brought him the **Fields Medal** in 1986.", "Bu ispat ona 1986'da **Fields Madalyası**'nı getirdi."),
          ("Later he also solved a more general conjecture of Lang.", "Daha sonra Lang'ın daha genel bir sanısını da çözdü.")),
        KUTU("ipucu", "The link to Fermat", "Fermat ile bağlantısı",
             ("Faltings' theorem also says that for every n ≥ 4, the equation xⁿ + yⁿ = zⁿ has at most finitely many solutions with no common divisor.", "Faltings teoremi ayrıca her n ≥ 4 için xⁿ + yⁿ = zⁿ denkleminin ortak böleni olmayan çözümlerinin en fazla sonlu sayıda olduğunu söyler."),
             ("This did not prove Fermat's Last Theorem, but it showed that the question was about \"finitely many\", not \"infinitely many\".", "Bu Fermat'ın Son Teoremi'ni kanıtlamadı, ama sorunun \"sonsuz\" değil \"sonlu\" bir soru olduğunu gösterdi."),
             ("In 1994, Andrew Wiles showed that the number is actually **zero**.", "1994'te Andrew Wiles bu sayının aslında **sıfır** olduğunu gösterdi.")),
        H("The first woman to win the Fields Medal: Maryam Mirzakhani", "Fields'ın ilk kadını: Maryam Mirzakhani"),
        P(("Here is a small reminder for 8 March.", "8 Mart vesilesiyle küçük bir hatırlatma."),
          ("In 2014, the Iranian mathematician **Maryam Mirzakhani** became the first woman to receive the Fields Medal.", "2014'te İranlı matematikçi **Maryam Mirzakhani** Fields Madalyası'nı alan ilk kadın oldu."),
          ("She worked at Stanford on the geometry of curved surfaces and on counting the shortest paths, or **geodesics**, on them.", "Stanford'da eğri yüzeylerin geometrisi ve bu yüzeyler üzerindeki en kısa yolların, yani **jeodeziklerin** sayısı üzerine çalıştı."),
          ("She died in 2017 at the age of 40.", "2017'de 40 yaşında hayatını kaybetti."),
          ("Her birthday, **12 May**, is now celebrated around the world as the Women in Mathematics Day.", "Doğum günü olan **12 Mayıs**, bugün dünyada Matematikte Kadınlar Günü olarak kutlanıyor.")),
        TERIMLER(("rational point", "rasyonel nokta"), ("Diophantine equation", "Diofant denklemi"),
                 ("genus", "cins (bir yüzeyin delik sayısı)"), ("finitely many", "sonlu sayıda"), ("geodesic", "jeodezik, en kısa yol")),
    ),

    BOLUM("dusun", "psychology", "#16A085", "Think Like a Mathematician: Start from the End", "Matematikçi Gibi Düşünmek: Sondan Başla",
        P(("In our first two issues, we saw the strategies of patterns and invariants.", "İlk iki sayımızda örüntü ve değişmez stratejilerini gördük."),
          ("This month's strategy is **working backwards** from the goal.", "Bu ayın stratejisi hedeften **geriye doğru çalışmak**."),
          ("If a problem asks \"How do I get there?\", the easiest way is sometimes to ask \"Where was I one step before?\"", "Bir problem \"Oraya nasıl varırım?\" diye soruyorsa, bazen en kolay yol \"Bir önceki adımda neredeydim?\" diye sormaktır.")),
        KUTU("soru", "The problem: the game of 21", "Problem: 21 oyunu",
             ("Two players take turns counting up from 1.", "İki oyuncu sırayla 1'den başlayarak sayıyor."),
             ("On each turn, a player says 1, 2 or 3 numbers.", "Her oyuncu sırası geldiğinde 1, 2 ya da 3 sayı söylüyor."),
             ("For example, the first player says \"1, 2\", the second says \"3, 4, 5\", the first says \"6\", and so on.", "Örneğin ilk oyuncu \"1, 2\" der, ikinci \"3, 4, 5\" der, ilk oyuncu \"6\" der ve böyle devam eder."),
             ("The player who says 21 wins.", "21'i söyleyen kazanır."),
             ("What should you do to win?", "Kazanmak için ne yapmalısın?")),
        H("The solution", "Çözüm"),
        P(("Let us start from the end.", "Sondan başlayalım."),
          ("I want to say 21, so I can reach it if my opponent stops at 18, 19 or 20.", "21'i söylemek istiyorum, rakibim 18, 19 ya da 20'de durursa ona ulaşabilirim."),
          ("This means I must leave my opponent at **17**.", "Bu, rakibimi **17'de** bırakmam gerektiği anlamına geliyor."),
          ("Whatever my opponent says, I can then reach 21.", "Rakibim ne söylerse söylesin, ben o zaman 21'e ulaşabilirim."),
          ("With the same logic, to say 17 I must leave my opponent at **13**.", "Aynı mantıkla, 17'yi söylemek için rakibimi **13'te** bırakmalıyım.")),
        FORMUL("21 > 17 > 13 > 9 > 5 > 1"),
        P(("So the **winning strategy** is to start the game and say only \"1\".", "Yani **kazanma stratejisi**, oyuna başlayıp yalnızca \"1\" demek."),
          ("After that, whatever your opponent says, complete each round to 4: 5, 9, 13, 17 and 21.", "Ondan sonra rakibin ne derse desin, her turu 4'e tamamla: 5, 9, 13, 17 ve 21."),
          ("Your win is **guaranteed**.", "Kazanman **garanti**.")),
        P(("The number 4 is not random here.", "Buradaki 4 sayısı rastgele değil."),
          ("Each round your opponent says 1, 2 or 3 numbers, and you complete the round to 4.", "Her tur rakibin 1, 2 ya da 3 sayı söyler ve sen turu 4'e tamamlarsın."),
          ("So 4 is the **invariant** of the game, and last month's strategy joins this month's.", "Yani 4 oyunun **değişmezi** ve geçen ayın stratejisi bu ayınkiyle birleşiyor.")),
        KUTU("soru", "Your turn", "Senin sıran",
             ("I thought of a number.", "Bir sayı tuttum."),
             ("I added 3, then multiplied by 2, then subtracted 4, and I got 20.", "3 ekledim, sonra 2 ile çarptım, sonra 4 çıkardım ve 20 buldum."),
             ("What was my number?", "Tuttuğum sayı kaçtı?")),
        KUTU("ipucu", "Answer", "Cevap",
             ("Start from the end: add 4 to 20 to get 24, divide by 2 to get 12, and subtract 3 to get **9**.", "Sondan başla: 20'ye 4 ekle ve 24 bul, 2'ye böl ve 12 bul, 3 çıkar ve **9** bul."),
             ("Check: (9 + 3) × 2 − 4 = 20.", "Kontrol: (9 + 3) × 2 − 4 = 20.")),
        TERIMLER(("working backwards", "geriye doğru çalışmak"), ("winning strategy", "kazanma stratejisi"),
                 ("to guarantee", "garanti etmek"), ("move", "hamle")),
    ),

    BOLUM("eglence", "lightbulb", "#E84393", "Fun Facts: Things You Didn't Know About π", "Eğlenceli Bilgiler: π Hakkında Bilmediklerin",
        LISTE(("In the 3rd century BC, Archimedes drew 96-sided **polygons** inside and outside a circle and showed that 3 + 10/71 < π < 3 + 1/7, that is, 3.1408 < π < 3.1429.", "M.Ö. 3. yüzyılda Arşimet, bir çemberin içine ve dışına 96 kenarlı **çokgenler** çizerek 3 + 10/71 < π < 3 + 1/7, yani 3,1408 < π < 3,1429 olduğunu gösterdi."),
              ("In the 5th century, the Chinese mathematician Zu Chongzhi **approximated** π with the fraction 355/113.", "5. yüzyılda Çinli matematikçi Zu Chongzhi π'nin **yaklaşık değerini** 355/113 kesriyle buldu."),
              ("This fraction gives π correctly to 6 **decimal places** (3.1415929…), and nobody found a better one for about 900 years.", "Bu kesir π'yi 6 **ondalık basamak** doğru veriyor (3,1415929…) ve yaklaşık 900 yıl boyunca kimse daha iyisini bulamadı."),
              ("Starting at the 762nd decimal place of π, there are six 9s in a row: …999999…", "π'nin 762. ondalık basamağından itibaren art arda altı tane 9 geliyor: …999999…"),
              ("The physicist Richard Feynman once said he would like to memorise π up to that point and finish with \"nine nine nine nine nine nine and so on\".", "Fizikçi Richard Feynman bir keresinde π'yi oraya kadar ezberleyip \"dokuz dokuz dokuz dokuz dokuz dokuz ve böyle devam eder\" diyerek bitirmek istediğini söylemişti."),
              ("Two coincidences of 14 March: Albert Einstein was born on 14 March 1879, and Stephen Hawking died on 14 March 2018.", "14 Mart'ın iki tesadüfü: Albert Einstein 14 Mart 1879'da doğdu, Stephen Hawking 14 Mart 2018'de hayatını kaybetti."),
              ("20 March 2026 is the spring equinox, when the Sun is right above the equator and day and night are about 12 hours each all over the world.", "20 Mart 2026 bahar ekinoksu: Güneş tam ekvatorun üzerinde ve dünyanın her yerinde gündüz ve gece yaklaşık 12'şer saat.")),
        H("Reading: How Archimedes trapped π", "Okuma: Arşimet π'yi nasıl sıkıştırdı"),
        P(("Every circle has the same secret.", "Her çemberin aynı sırrı var."),
          ("If you divide its **circumference** by its **diameter**, you always get the same number, which we call π.", "**Çevresini** **çapına** bölersen hep aynı sayıyı elde edersin ve biz ona π deriz."),
          ("But what exactly is this number?", "Peki bu sayı tam olarak nedir?"),
          ("More than two thousand years ago, Archimedes found a clever way to answer this question.", "İki bin yıldan uzun bir süre önce Arşimet bu soruyu cevaplamanın akıllıca bir yolunu buldu.")),
        P(("He could not measure π directly, so he trapped it.", "π'yi doğrudan ölçemiyordu, bu yüzden onu sıkıştırdı."),
          ("First, he drew a **regular hexagon** inside a circle and another one outside it.", "Önce bir çemberin içine bir **düzgün altıgen**, dışına da bir tane daha çizdi."),
          ("The **perimeter** of the inner hexagon was a little shorter than the circle, and the perimeter of the outer one was a little longer.", "İçteki altıgenin **çevresi** çemberden biraz kısaydı, dıştakinin çevresi ise biraz uzundu."),
          ("So the true value of π had to lie somewhere in between.", "Yani π'nin gerçek değeri ikisinin arasında bir yerde olmalıydı.")),
        P(("Then he doubled the number of sides: 12, 24, 48 and finally 96.", "Sonra kenar sayısını ikiye katladı: 12, 24, 48 ve sonunda 96."),
          ("With each step, the two polygons came closer to the circle, and the trap became tighter.", "Her adımda iki çokgen çembere biraz daha yaklaştı ve tuzak daha da sıkılaştı."),
          ("The beauty of this method is that Archimedes never needed to know π exactly.", "Bu yöntemin güzelliği, Arşimet'in π'yi hiçbir zaman tam olarak bilmesine gerek olmamasıdır."),
          ("He only needed two numbers that he could calculate, one too small and one too large.", "Sadece hesaplayabildiği iki sayıya ihtiyacı vardı: Biri çok küçük, biri çok büyük."),
          ("Today this idea is one of the most important tools in analysis, and you will meet it again as the **squeeze theorem**.", "Bugün bu fikir analizin en önemli araçlarından biri ve onunla **sıkıştırma teoremi** olarak yeniden karşılaşacaksın.")),
        TERIMLER(("polygon", "çokgen"), ("to approximate", "yaklaşık değerini bulmak"), ("decimal place", "ondalık basamak"),
                 ("circumference / diameter", "çevre / çap"), ("regular hexagon", "düzgün altıgen"), ("squeeze theorem", "sıkıştırma teoremi")),
    ),

    BOLUM("sinif", "school", "#27AE60", "In the Classroom", "Sınıfta Matematik",
        H("Grades 6–8: Find π yourself", "6-8. sınıflar: π'yi kendin bul"),
        P(("You need string, a ruler, a tape measure and 5 or 6 round objects from home, such as lids, glasses, clocks, plates or CDs.", "İp, cetvel, şerit metre ve evden getirilen 5-6 yuvarlak nesne gerekiyor: kapak, bardak, saat, tabak ya da CD gibi.")),
        LISTE(("Groups measure the circumference of each object with string and find its length with a ruler.", "Gruplar her nesnenin çevresini iple ölçer ve uzunluğunu cetvelle bulur."),
              ("They measure the diameter with the ruler.", "Çapı cetvelle ölçerler."),
              ("For each object they calculate **circumference ÷ diameter** and write it in a shared table on the board.", "Her nesne için **çevre ÷ çap** hesaplarlar ve tahtadaki ortak tabloya yazarlar."),
              ("Finally, the class takes the **average** of all the results.", "Son olarak sınıf tüm sonuçların **ortalamasını** alır.")),
        KUTU("sinif", "Discussion", "Tartışma",
             ("Why are the results not exactly 3.14159…?", "Sonuçlar neden tam olarak 3,14159… çıkmıyor?"),
             ("Where does the **measurement error** come from?", "**Ölçüm hatası** nereden geliyor?"),
             ("Do bigger objects give a better result?", "Daha büyük nesneler daha iyi sonuç verir mi?"),
             ("Bonus: compare your average with Archimedes' range from 3.1408 to 3.1429, and see if your class beat Archimedes.", "Bonus: Ortalamanızı Arşimet'in 3,1408 ile 3,1429 aralığıyla karşılaştırın ve sınıfınızın Arşimet'i geçip geçmediğine bakın."),
             ("This activity links measurement, data collection, averages and error in a real experiment, just as the Maarif model asks.", "Bu etkinlik, tıpkı Maarif modelinin istediği gibi ölçme, veri toplama, ortalama ve hata kavramlarını gerçek bir deneyde birleştiriyor.")),
        H("High school: π with toothpicks (Buffon's needle)", "Lise: Kürdanlarla π (Buffon'un iğnesi)"),
        P(("You need a box of toothpicks and a large sheet of paper with **parallel lines** on it.", "Bir kutu kürdan ve üzerine **paralel doğrular** çizilmiş büyük bir kâğıt gerekiyor."),
          ("The distance between the lines should be equal to the length of a toothpick.", "Doğrular arasındaki mesafe bir kürdanın boyuna eşit olmalı.")),
        LISTE(("Drop the toothpicks onto the paper at random, and five groups with 100 throws each is ideal.", "Kürdanları kâğıdın üzerine rastgele atın, 100'er atış yapan beş grup idealdir."),
              ("Count the toothpicks that cross a line.", "Bir doğruyu kesen kürdanları sayın."),
              ("When the toothpick length equals the line spacing, the probability that a toothpick crosses a line is 2/π.", "Kürdan boyu doğrular arasındaki mesafeye eşit olduğunda, bir kürdanın doğru kesme olasılığı 2/π'dir.")),
        FORMUL("π ≈ 2 × (total throws) ÷ (crossings)"),
        P(("For example, if 318 out of 500 throws cross a line, then π ≈ 1000 / 318 ≈ 3.14.", "Örneğin 500 atışın 318'i bir doğruyu keserse π ≈ 1000 / 318 ≈ 3,14 olur.")),
        KUTU("soru", "Questions for discussion", "Tartışma soruları",
             ("How can a geometric constant come out of a probability experiment?", "Geometrik bir sabit nasıl olur da bir olasılık deneyinden çıkar?"),
             ("Why does the result improve when we throw more toothpicks?", "Daha çok kürdan attığımızda sonuç neden iyileşir?"),
             ("This is a nice introduction to the **law of large numbers**.", "Bu, **büyük sayılar yasasına** güzel bir giriş."),
             ("Advanced: try to prove with an integral that the probability is 2/π.", "İleri seviye: Olasılığın 2/π olduğunu integralle kanıtlamaya çalışın.")),
        TERIMLER(("measurement error", "ölçüm hatası"), ("average / mean", "ortalama"),
                 ("parallel lines", "paralel doğrular"), ("law of large numbers", "büyük sayılar yasası")),
    ),

    BOLUM("gundem", "campaign", "#C0392B", "Education in Türkiye", "Eğitim Gündemi",
        H("YKS registration is closing", "YKS başvuruları sona eriyor"),
        LISTE(("Regular registration ends on **2 March 2026**.", "Normal başvuru **2 Mart 2026**'da bitiyor."),
              ("**Late registration** is on 10–12 March 2026.", "**Geç başvuru** 10-12 Mart 2026 tarihlerinde."),
              ("TYT is on 20 June, and AYT and YDT are on 21 June.", "TYT 20 Haziran'da, AYT ve YDT 21 Haziran'da.")),
        P(("A reminder for grade 12 teachers: late registration is the last chance for students who forgot to apply.", "12. sınıf öğretmenleri için bir hatırlatma: Başvurusunu unutan öğrenciler için geç başvuru son şans.")),
        H("March: the month of practice tests", "Mart: Deneme sınavlarının ayı"),
        P(("There are about three months left until LGS on 13 June.", "13 Haziran'daki LGS'ye yaklaşık üç ay kaldı."),
          ("In this period, **practice tests** become more frequent.", "Bu dönemde **deneme sınavları** sıklaşıyor."),
          ("Students usually lose the most time on long, **multi-step problems**.", "Öğrenciler en çok zamanı genelde uzun, **çok adımlı sorularda** kaybediyor."),
          ("So this month it helps to show the \"Start from the end\" strategy on LGS-style questions.", "Bu yüzden bu ay \"Sondan başla\" stratejisini LGS tipi sorularda göstermek işe yarar."),
          ("Ask: What does the question want, and what do I need to know one step before that?", "Şunu sor: Soru ne istiyor ve o sonuca ulaşmak için bir önceki adımda neyi bilmem gerek?")),
        H("Ideas for the International Day of Mathematics", "Uluslararası Matematik Günü için fikirler"),
        LISTE(("A \"π chain\" in the corridor: each student writes one digit of π on a sheet of paper and joins the line.", "Koridorda bir \"π zinciri\": Her öğrenci π'nin bir basamağını bir kâğıda yazıp sıraya giriyor."),
              ("A π memory contest: who can say the most digits?", "Bir π ezberleme yarışması: Kim en çok basamağı sayabilir?"),
              ("The two classroom activities in this issue: measuring circles and Buffon's needle.", "Bu sayıdaki iki sınıf etkinliği: Çember ölçümü ve Buffon'un iğnesi.")),
        TERIMLER(("registration", "başvuru, kayıt"), ("late registration", "geç başvuru"), ("practice test", "deneme sınavı"), ("multi-step problem", "çok adımlı problem")),
    ),

    BOLUM("oku", "menu_book", "#34495E", "Read Like a Mathematician", "Matematikçi Gibi Oku",
        P(("This month we look at phrases for **conditions** and some common **abbreviations** in mathematical texts.", "Bu ay matematik metinlerinde sık karşılaşılan **koşul** kalıplarına ve bazı yaygın **kısaltmalara** bakıyoruz.")),
        TABLO(["English", "Türkçe"],
              ["necessary condition", "gerek koşul (p olmadan q olmaz)"],
              ["sufficient condition", "yeter koşul (p varsa q kesin olur)"],
              ["i.e. (Latin: id est)", "yani"],
              ["e.g. (Latin: exempli gratia)", "örneğin"],
              ["trivial / nontrivial", "basit, apaçık / basit olmayan"],
              ["well-defined", "iyi tanımlı"],
              ["by induction", "tümevarımla"],
              ["base case / inductive step", "başlangıç adımı / tümevarım adımı"]),
        KUTU("soru", "Mini reading: a classic induction proof", "Mini okuma: Klasik bir tümevarım ispatı",
             ("Claim: For every positive integer n, 1 + 2 + … + n = n(n + 1)/2.", "İddia: Her n pozitif tam sayısı için 1 + 2 + … + n = n(n + 1)/2."),
             ("Proof: We proceed by induction on n.", "İspat: n üzerinde tümevarımla ilerleyelim."),
             ("Base case: For n = 1, the left side is 1 and the right side is 1 · 2/2 = 1.", "Başlangıç adımı: n = 1 için sol taraf 1, sağ taraf 1 · 2/2 = 1."),
             ("Inductive step: Suppose that the claim holds for some n ≥ 1.", "Tümevarım adımı: İddianın bir n ≥ 1 için doğru olduğunu varsayalım."),
             ("Then 1 + 2 + … + n + (n + 1) = n(n + 1)/2 + (n + 1) = (n + 1)(n + 2)/2, which is the claim for n + 1.", "O zaman 1 + 2 + … + n + (n + 1) = n(n + 1)/2 + (n + 1) = (n + 1)(n + 2)/2 olur ve bu, n + 1 için iddiadır."),
             ("Hence, by induction, the claim holds for all positive integers. ∎", "Dolayısıyla tümevarımla iddia tüm pozitif tam sayılar için doğrudur. ∎")),
        KUTU("ipucu", "A small note", "Küçük bir not",
             ("In mathematical texts, the word \"trivial\" is not an insult, and it simply means \"easy to see\".", "Matematiksel metinlerde \"trivial\" kelimesi küçümseme değil, sadece \"hemen görülüyor\" anlamına gelir."),
             ("But if a paper says \"this is trivial\" and you cannot see it, don't worry.", "Ama bir makalede \"this is trivial\" yazıyorsa ve sen göremiyorsan endişelenme."),
             ("These may be the two words that have cost the most hours in the history of mathematics.", "Bu iki kelime, matematik tarihinde en çok saat harcatan iki kelime olabilir.")),
        TERIMLER(("necessary condition", "gerek koşul"), ("sufficient condition", "yeter koşul"),
                 ("trivial", "basit, apaçık"), ("well-defined", "iyi tanımlı"), ("by induction", "tümevarımla")),
    ),
]

quiz = [
    SORU("Who received the 2026 Abel Prize?", "2026 Abel Ödülü'nü kim aldı?",
         ["Andrew Wiles", "Gerd Faltings", "Masaki Kashiwara", "Louis Mordell"], 1,
         "Gerd Faltings won it for his work in arithmetic geometry and for proving the Mordell conjecture.", "Gerd Faltings ödülü aritmetik geometrideki çalışmaları ve Mordell sanısını kanıtlaması için aldı."),
    SORU("How much information does one toss of a fair coin carry?", "Hilesiz bir paranın bir atışı ne kadar bilgi taşır?",
         ["0.47 bits", "1 bit", "2 bits", "2.58 bits"], 1,
         "p = 1/2, so the information is log₂(2) = 1 bit.", "p = 1/2, yani bilgi log₂(2) = 1 bit."),
    SORU("According to Noether's theorem, if the laws of physics do not change with time, what is conserved?", "Noether teoremine göre fizik yasaları zamanla değişmiyorsa ne korunur?",
         ["Momentum", "Angular momentum", "Energy", "Mass"], 2,
         "Symmetry in time corresponds to the conservation of energy.", "Zamandaki simetri enerjinin korunumuna karşılık gelir."),
    SORU("In the game of 21, which number should you say first to win?", "21 oyununda kazanmak için ilk olarak hangi sayıyı söylemelisin?",
         ["1", "3", "4", "5"], 0,
         "Working backwards gives 21, 17, 13, 9, 5 and 1.", "Geriye doğru çalışınca 21, 17, 13, 9, 5 ve 1 çıkar."),
    SORU("How many sides did Archimedes' final polygons have?", "Arşimet'in son çokgenlerinin kaç kenarı vardı?",
         ["6", "48", "96", "355"], 2,
         "He doubled from 6 to 12, 24, 48 and finally 96 sides.", "Kenar sayısını 6'dan 12, 24, 48 ve sonunda 96'ya katladı."),
    SORU("How many different codons can be made from four DNA bases?", "Dört DNA bazından kaç farklı kodon yapılabilir?",
         ["12", "20", "64", "81"], 2,
         "A codon has three positions with four choices each, so 4³ = 64.", "Bir kodonun her biri dört seçenekli üç konumu vardır, yani 4³ = 64."),
]

bulmacalar = [
    ANAGRAM("PROTYNE", "ENTROPY", "Shannon's measure of information.", "Shannon'ın bilgi ölçüsü."),
    ANAGRAM("TRYMEMSY", "SYMMETRY", "According to Noether, the source of conservation laws.", "Noether'e göre korunum yasalarının kaynağı."),
    ANAGRAM("TRAMEDIE", "DIAMETER", "The longest chord of a circle.", "Bir çemberin en uzun kirişi."),
    ANAGRAM("TINYFINI", "INFINITY", "Something that never ends.", "Hiç bitmeyen şey."),
    ESLESTIR("Match the terms", "Terimleri eşleştir",
             ("entropy", "entropi"), ("conservation law", "korunum yasası"), ("genus", "cins"),
             ("squeeze theorem", "sıkıştırma teoremi"), ("codon", "kodon")),
    MANTIK("A rope around the Earth", "Dünyayı saran ip",
           "A rope fits exactly around the Earth's equator, which is about 40,000 km long. We make the rope just 1 metre longer and lift it so that it is the same height above the ground everywhere. Can a cat walk under it?",
           "Dünyanın yaklaşık 40.000 km olan ekvatorunu tam saran bir ip var. İpi sadece 1 metre uzatıyoruz ve her yerde yerden aynı yükseklikte duracak şekilde kaldırıyoruz. İpin altından bir kedi geçebilir mi?",
           "Yes. Circumference = 2πr, so 1 extra metre raises the radius by 1/(2π) ≈ 0.16 m, about 16 cm. Surprisingly, the answer does not depend on the size of the Earth at all, and it is the same for a football.",
           "Evet. Çevre = 2πr, yani fazladan 1 metre yarıçapı 1/(2π) ≈ 0,16 m, yaklaşık 16 cm artırır. Şaşırtıcı şekilde cevap Dünya'nın büyüklüğüne hiç bağlı değil ve bir futbol topu için de aynı."),
    MANTIK("Water lilies", "Nilüferler",
           "The water lilies on a lake double every day. On day 30 the whole lake is covered. On which day was the lake half covered?",
           "Bir göldeki nilüferler her gün iki katına çıkıyor. 30. günde gölün tamamı kaplanıyor. Göl hangi gün yarı yarıya kaplıydı?",
           "Start from the end: the lilies double every day, so the day before the lake was full it was half full. The answer is day 29, not day 15.",
           "Sondan başla: Nilüferler her gün ikiye katlanıyor, yani göl dolmadan bir gün önce yarı doluydu. Cevap 29. gün, 15. gün değil."),
]

SAYI_VERI = SAYI(
    3, "Mart 2026", "March 2026", "Sonsuzu ölçmek", "Measuring the infinite",
    {"renkler": ["#1E7F7A", "#125653"], "desen": 3},
    bolumler, quiz, bulmacalar,
    ad="Chasing π", ad_tr="π'nin Peşinde",
)
