from dergi import *

bolumler = [
    BOLUM("editor", "edit_note", "#6C63FF", "Editor's Note", "Editörden",
        P(("Welcome back, and welcome to our ninth issue.", "Tekrar hoş geldin, dokuzuncu sayımıza hoş geldin."),
          ("Issue 9 in month 9: we could not have planned a better coincidence.", "Dokuzuncu ayda dokuzuncu sayı: Bundan daha güzel bir tesadüf planlayamazdık."),
          ("On Monday, 14 September 2026, the first bell rang again in schools all over Türkiye.", "14 Eylül 2026 pazartesi günü Türkiye'nin dört bir yanındaki okullarda ilk zil yeniden çaldı."),
          ("New notebooks, new names on the class list and new questions are waiting for us.", "Yeni defterler, sınıf listesinde yeni isimler ve yeni sorular bizi bekliyor.")),
        P(("The theme of this month is **order and symmetry**.", "Bu ayın teması **düzen ve simetri**."),
          ("A new school year is a little like a crystal: small, repeated habits slowly build a strong structure.", "Yeni bir okul yılı biraz bir kristale benzer: Küçük ve tekrarlanan alışkanlıklar yavaş yavaş sağlam bir yapı kurar."),
          ("You will see how X-rays revealed the hidden order inside crystals, and why a crystal can never have five-fold symmetry.", "X ışınlarının kristallerin içindeki gizli düzeni nasıl ortaya çıkardığını ve bir kristalin neden asla beşli simetriye sahip olamayacağını göreceksin."),
          ("Our mathematician of the month taught geometry and astronomy in Alexandria sixteen centuries ago: **Hypatia**.", "Ayın matematikçimiz on altı yüzyıl önce İskenderiye'de geometri ve astronomi öğretti: **Hypatia**.")),
        P(("In the news, a computer checked every single step of the proof of Fermat's Last Theorem for the first time.", "Haberlerde, bir bilgisayar Fermat'nın Son Teoremi'nin ispatındaki her bir adımı ilk kez kontrol etti."),
          ("We wish you a calm and productive new school year.", "Sana sakin ve verimli bir yeni eğitim yılı diliyoruz."),
          ("Enjoy your break!", "İyi molalar!")),
    ),

    BOLUM("haber", "newspaper", "#2E86DE", "News from the World of Maths", "Matematik Dünyasından Haberler",
        H("Fermat's Last Theorem, checked line by line by a computer", "Fermat'nın Son Teoremi, bir bilgisayar tarafından satır satır kontrol edildi"),
        P(("In 1637, Pierre de Fermat wrote in the margin of a book that xⁿ + yⁿ = zⁿ has no solutions in positive integers when n > 2.", "1637'de Pierre de Fermat bir kitabın kenarına, n > 2 iken xⁿ + yⁿ = zⁿ denkleminin pozitif tam sayılarda çözümü olmadığını yazdı."),
          ("He added that the margin was too small for his proof.", "İspatı için kenar boşluğunun çok küçük olduğunu da ekledi."),
          ("The first accepted proof came from Andrew Wiles in 1994, and it is more than a hundred pages of very deep mathematics.", "Kabul gören ilk ispat 1994'te Andrew Wiles'tan geldi ve yüz sayfayı aşan, çok derin bir matematik içeriyor.")),
        P(("On 4 September 2026, Anthropic announced that its AI model Claude had **formalized** the whole proof in the **Lean** language.", "4 Eylül 2026'da Anthropic, yapay zekâ modeli Claude'un ispatın tamamını **Lean** dilinde **biçimselleştirdiğini** duyurdu."),
          ("Formalizing means writing every step so precisely that a computer program can check it.", "Biçimselleştirmek, her adımı bir bilgisayar programının kontrol edebileceği kadar kesin biçimde yazmak demek."),
          ("According to the company, dozens of Claude agents worked mostly on their own for 11 days.", "Şirkete göre onlarca Claude ajanı 11 gün boyunca büyük ölçüde kendi başına çalıştı."),
          ("The result is about 13 million lines of Lean code, and it follows a simplified version of Wiles's proof.", "Sonuç yaklaşık 13 milyon satırlık Lean kodu ve Wiles'ın ispatının sadeleştirilmiş bir versiyonunu izliyor.")),
        P(("The work also used parts of a community project that **Kevin Buzzard** started at Imperial College London in 2024.", "Çalışma, **Kevin Buzzard**'ın 2024'te Imperial College London'da başlattığı bir topluluk projesinin parçalarını da kullandı."),
          ("Buzzard reviewed the proof and said that it proves the theorem with no assumptions other than the axioms of mathematics.", "Buzzard ispatı inceledi ve teoremi matematiğin aksiyomları dışında hiçbir varsayım olmadan kanıtladığını söyledi.")),
        KUTU("bilgi", "What is new, and what is not?", "Yeni olan ne, olmayan ne?",
             ("The mathematics itself is not new, because Wiles proved the theorem more than thirty years ago.", "Matematiğin kendisi yeni değil, çünkü Wiles teoremi otuz yılı aşkın süre önce kanıtladı."),
             ("The new thing is the **machine verification** of such a huge proof.", "Yeni olan, bu kadar büyük bir ispatın **makineyle doğrulanması**."),
             ("Anthropic itself says that the proof is probably much longer than necessary and that a formal proof should not replace a human-readable explanation.", "Anthropic de ispatın muhtemelen gerekenden çok daha uzun olduğunu ve biçimsel bir ispatın insanın okuyabileceği bir açıklamanın yerini almaması gerektiğini söylüyor.")),
        H("A new OpenAI model and a debate about credit", "Yeni bir OpenAI modeli ve emek tartışması"),
        P(("In the same week, OpenAI released a new model called **GPT-6 Astra**.", "Aynı hafta OpenAI, **GPT-6 Astra** adlı yeni bir model yayımladı."),
          ("The company says that an internal version of the model had helped to make progress on ten long-standing problems in mathematics and theoretical computer science.", "Şirket, modelin şirket içi bir versiyonunun matematik ve teorik bilgisayar biliminde uzun süredir açık on problemde ilerleme sağlamaya yardım ettiğini söylüyor."),
          ("The proofs were shared together with Lean versions, so anyone can check them.", "İspatlar Lean versiyonlarıyla birlikte paylaşıldı, yani herkes onları kontrol edebilir."),
          ("However, some mathematicians said that earlier human work had played an important role and asked for clearer **credit**.", "Ancak bazı matematikçiler önceki insan çalışmalarının önemli bir rol oynadığını söyleyip emeğin daha açık biçimde **teslim edilmesini** istedi."),
          ("At the time of writing, none of the ten results had completed **peer review**.", "Bu satırlar yazılırken on sonucun hiçbiri **hakem değerlendirmesini** tamamlamamıştı.")),
        KUTU("sinif", "For the classroom", "Sınıf için",
             ("A proof that a computer has checked is correct, but is it also understandable?", "Bilgisayarın kontrol ettiği bir ispat doğrudur, peki aynı zamanda anlaşılır mıdır?"),
             ("Ask your students: what is the difference between knowing that something is true and knowing why it is true?", "Öğrencilerine sor: Bir şeyin doğru olduğunu bilmekle neden doğru olduğunu bilmek arasındaki fark nedir?")),
        TERIMLER(("to formalize", "biçimselleştirmek"), ("machine verification", "makineyle doğrulama"), ("axiom", "aksiyom, belit"),
                 ("credit", "emeğin teslim edilmesi, pay"), ("peer review", "hakem değerlendirmesi")),
    ),

    BOLUM("makale", "article", "#8E44AD", "Paper of the Month: How X-rays See Inside a Crystal", "Ayın Makalesi: X Işınları Bir Kristalin İçini Nasıl Görür?",
        KUTU("bilgi", "Source", "Kaynak",
             ("W. L. Bragg, The Diffraction of Short Electromagnetic Waves by a Crystal, Proceedings of the Cambridge Philosophical Society, 1913.", "W. L. Bragg, Kısa Elektromanyetik Dalgaların Bir Kristal Tarafından Kırınımı, Proceedings of the Cambridge Philosophical Society, 1913.")),
        H("The problem", "Problem"),
        P(("In 1912, Max von Laue showed that X-rays passing through a crystal produce a pattern of bright spots on a photographic plate.", "1912'de Max von Laue, bir kristalden geçen X ışınlarının fotoğraf plakası üzerinde parlak noktalardan oluşan bir desen oluşturduğunu gösterdi."),
          ("This proved that X-rays are waves and that crystals are regular arrangements of atoms.", "Bu, X ışınlarının dalga olduğunu ve kristallerin atomların düzenli dizilişleri olduğunu kanıtladı."),
          ("But the pattern was complicated, and nobody knew how to read it.", "Ama desen karmaşıktı ve kimse onu nasıl okuyacağını bilmiyordu.")),
        P(("A 22-year-old student in Cambridge, **William Lawrence Bragg**, found a beautifully simple way to think about it.", "Cambridge'de 22 yaşında bir öğrenci olan **William Lawrence Bragg**, bunu düşünmenin çok güzel ve basit bir yolunu buldu."),
          ("Imagine the atoms of a crystal lying on parallel **planes**, like the floors of a building.", "Bir kristalin atomlarını, bir binanın katları gibi paralel **düzlemler** üzerinde dizilmiş olarak düşün."),
          ("Each plane reflects a small part of the X-ray beam, like a very weak mirror.", "Her düzlem, çok zayıf bir ayna gibi X ışını demetinin küçük bir kısmını yansıtır.")),
        H("A little geometry", "Biraz geometri"),
        P(("Let the distance between two neighbouring planes be d, and let the beam hit the planes at an angle θ.", "İki komşu düzlem arasındaki uzaklık d olsun ve ışın düzlemlere θ açısıyla çarpsın."),
          ("The ray that reflects from the lower plane travels a little further than the ray that reflects from the upper plane.", "Alttaki düzlemden yansıyan ışın, üstteki düzlemden yansıyan ışından biraz daha fazla yol alır."),
          ("Drawing two right triangles shows that this extra distance, the **path difference**, is d sin θ on the way in and d sin θ on the way out.", "İki dik üçgen çizince bu fazladan yolun, yani **yol farkının**, girişte d sin θ ve çıkışta d sin θ olduğu görülür.")),
        FORMUL("path difference = 2d · sin θ"),
        P(("The two reflected waves add up and make a bright spot only when they are \"in step\".", "Yansıyan iki dalga ancak \"aynı adımda\" olduklarında toplanıp parlak bir nokta oluşturur."),
          ("This happens when the path difference is a whole number of **wavelengths**.", "Bu, yol farkı **dalga boyunun** tam katı olduğunda gerçekleşir."),
          ("This is **Bragg's law**:", "İşte **Bragg yasası**:")),
        FORMUL("n · λ = 2d · sin θ    (n = 1, 2, 3, …)"),
        H("An example", "Bir örnek"),
        P(("In table salt, one family of planes is d ≈ 0.282 nm apart.", "Sofra tuzunda düzlem ailelerinden birinde düzlemler arası uzaklık d ≈ 0,282 nm."),
          ("A common laboratory X-ray source has a wavelength of λ ≈ 0.154 nm.", "Yaygın bir laboratuvar X ışını kaynağının dalga boyu λ ≈ 0,154 nm."),
          ("For n = 1, we get sin θ = 0.154 / 0.564 ≈ 0.273, so θ ≈ 15.8°.", "n = 1 için sin θ = 0,154 / 0,564 ≈ 0,273 buluruz, yani θ ≈ 15,8°."),
          ("If you measure the angle, you can work backwards and find the distance between the planes.", "Açıyı ölçersen geriye doğru giderek düzlemler arasındaki uzaklığı bulabilirsin."),
          ("That is exactly how scientists measure distances that are a billion times smaller than a metre.", "Bilim insanları metrenin milyarda biri kadar küçük uzaklıkları tam olarak böyle ölçüyor.")),
        H("What came next", "Sonrası"),
        P(("Bragg and his father, William Henry Bragg, used this law to find the structure of table salt and diamond in 1913.", "Bragg ve babası William Henry Bragg bu yasayı kullanarak 1913'te sofra tuzunun ve elmasın yapısını buldu."),
          ("Salt surprised chemists: there are no separate NaCl molecules, and each sodium ion simply sits between six chloride ions.", "Tuz kimyacıları şaşırttı: Ayrı NaCl molekülleri yok, her sodyum iyonu basitçe altı klorür iyonunun arasında duruyor."),
          ("Father and son shared the Nobel Prize in Physics in 1915, and the son is still the youngest physics laureate ever.", "Baba ve oğul 1915 Nobel Fizik Ödülü'nü paylaştı ve oğul hâlâ bu ödülü alan en genç fizikçi."),
          ("Later, the same method revealed the structures of proteins and the famous \"Photo 51\" of DNA.", "Daha sonra aynı yöntem proteinlerin yapısını ve DNA'nın ünlü \"51 numaralı fotoğrafını\" ortaya çıkardı.")),
        KUTU("bilgi", "Graduate corner", "Yüksek lisans köşesi",
             ("Mathematically, a diffraction pattern is close to the **Fourier transform** of the electron density in the crystal.", "Matematiksel olarak bir kırınım deseni, kristaldeki elektron yoğunluğunun **Fourier dönüşümüne** yakındır."),
             ("The bright spots form the **reciprocal lattice**, and Bragg's law is a geometric way of saying when a spot appears.", "Parlak noktalar **ters örgüyü** oluşturur ve Bragg yasası bir noktanın ne zaman ortaya çıktığını söylemenin geometrik bir yoludur."),
             ("The detectors only measure the size of each wave and lose its phase, which is the famous **phase problem**.", "Dedektörler her dalganın yalnızca büyüklüğünü ölçer ve fazını kaybeder, ünlü **faz problemi** de budur."),
             ("Solving it is a good example of an **inverse problem**, a topic that connects analysis, algebra and computation.", "Bunu çözmek, analiz, cebir ve hesaplamayı birbirine bağlayan bir konu olan **ters problemlere** güzel bir örnektir.")),
        TERIMLER(("diffraction", "kırınım"), ("wavelength", "dalga boyu"), ("path difference", "yol farkı"),
                 ("Fourier transform", "Fourier dönüşümü"), ("reciprocal lattice", "ters örgü"), ("inverse problem", "ters problem")),
    ),

    BOLUM("bilim", "science", "#0E7490", "Science Corner: Crystals and Symmetry", "Bilim Köşesi: Kristaller ve Simetri",
        P(("Look at a grain of salt under a magnifying glass, and you will see a tiny cube.", "Bir tuz tanesine büyüteçle bak, minicik bir küp göreceksin."),
          ("This is not an accident.", "Bu bir tesadüf değil."),
          ("A **crystal** is a solid whose atoms, ions or molecules repeat in a regular pattern in all three directions.", "**Kristal**, atomlarının, iyonlarının ya da moleküllerinin üç yönde de düzenli bir desenle tekrarlandığı katıdır.")),
        H("The unit cell", "Birim hücre"),
        P(("The smallest box that repeats to build the whole crystal is called the **unit cell**.", "Tekrarlanarak bütün kristali oluşturan en küçük kutuya **birim hücre** denir."),
          ("If you stack copies of it side by side, like bricks in a wall, you get the crystal.", "Onun kopyalarını duvardaki tuğlalar gibi yan yana dizersen kristali elde edersin."),
          ("The points where the boxes meet form a **lattice**.", "Kutuların birleştiği noktalar bir **örgü** (kafes) oluşturur."),
          ("In table salt, the unit cell is a cube, and that is why salt grains look like cubes.", "Sofra tuzunda birim hücre bir küptür ve tuz taneleri bu yüzden küp gibi görünür.")),
        P(("Chemists sort all crystals into **seven crystal systems**, such as cubic, tetragonal and hexagonal.", "Kimyacılar bütün kristalleri kübik, tetragonal ve hekzagonal gibi **yedi kristal sistemine** ayırır."),
          ("In 1848, Auguste Bravais showed that there are exactly 14 different types of lattice in three dimensions.", "1848'de Auguste Bravais, üç boyutta tam olarak 14 farklı örgü türü olduğunu gösterdi."),
          ("When all symmetries are included, there are exactly 230 **space groups**, a result found independently by Fedorov and Schoenflies in 1891.", "Bütün simetriler hesaba katılınca tam olarak 230 **uzay grubu** vardır ve bu sonucu 1891'de Fedorov ile Schoenflies birbirinden bağımsız olarak buldu.")),
        H("Same atoms, different order", "Aynı atomlar, farklı düzen"),
        P(("Diamond and graphite are both made only of carbon atoms.", "Elmas da grafit de yalnızca karbon atomlarından oluşur."),
          ("In diamond, each carbon atom is bonded to four others in a strong three-dimensional network, so diamond is extremely hard.", "Elmasta her karbon atomu güçlü bir üç boyutlu ağ içinde dört başka atoma bağlıdır, bu yüzden elmas son derece serttir."),
          ("In graphite, the atoms form flat hexagonal layers that slide over each other, so graphite is soft enough for pencils.", "Grafitte ise atomlar birbirinin üzerinden kayan düz altıgen katmanlar oluşturur, bu yüzden grafit kurşun kalemlere yetecek kadar yumuşaktır."),
          ("The arrangement of the atoms, not only their type, decides the properties of a material.", "Bir malzemenin özelliklerini yalnızca atomların türü değil, dizilişleri de belirler.")),
        H("Why no five-fold symmetry?", "Neden beşli simetri yok?"),
        P(("Snowflakes have six-fold symmetry because water molecules in ice join in hexagonal rings.", "Kar tanelerinin altılı simetrisi vardır, çünkü buzdaki su molekülleri altıgen halkalar hâlinde birleşir."),
          ("But you will never find a crystal with five-fold rotational symmetry.", "Ama beşli dönme simetrisine sahip bir kristale asla rastlamazsın."),
          ("Try to cover a floor with regular pentagons, and gaps will always appear.", "Bir zemini düzgün beşgenlerle kaplamayı dene, her zaman boşluklar oluşacak."),
          ("This is the **crystallographic restriction**: a periodic lattice can only have 2-, 3-, 4- or 6-fold rotations.", "Bu, **kristalografik kısıtlamadır**: Periyodik bir örgü yalnızca 2'li, 3'lü, 4'lü ya da 6'lı dönmelere sahip olabilir.")),
        KUTU("bilgi", "The proof in two lines", "İki satırda ispat",
             ("Write a rotation by angle θ as a matrix in a basis of the lattice, so all its entries are integers.", "θ açılı bir dönmeyi örgünün bir tabanında matris olarak yaz, böylece bütün elemanları tam sayı olur."),
             ("The **trace** of the matrix does not depend on the basis, and in the usual basis it equals 2 cos θ.", "Matrisin **izi** tabana bağlı değildir ve alışılmış tabanda 2 cos θ'ya eşittir."),
             ("So 2 cos θ must be an integer, and this leaves only θ = 60°, 90°, 120°, 180° or 360°.", "Yani 2 cos θ bir tam sayı olmalı ve bu da yalnızca θ = 60°, 90°, 120°, 180° ya da 360° seçeneklerini bırakır."),
             ("For five-fold symmetry, 2 cos 72° ≈ 0.618, which is not an integer.", "Beşli simetri için 2 cos 72° ≈ 0,618 ve bu bir tam sayı değil.")),
        P(("In 1982, however, Dan Shechtman saw a ten-fold diffraction pattern in an aluminium alloy.", "Ancak 1982'de Dan Shechtman bir alüminyum alaşımında onlu bir kırınım deseni gördü."),
          ("Many scientists did not believe him at first.", "Birçok bilim insanı başta ona inanmadı."),
          ("These **quasicrystals** are ordered but not periodic, much like the Penrose tilings that mathematicians had already drawn.", "Bu **yarı kristaller** düzenlidir ama periyodik değildir, tıpkı matematikçilerin daha önce çizmiş olduğu Penrose döşemeleri gibi."),
          ("Shechtman received the Nobel Prize in Chemistry in 2011, and the definition of a crystal was changed.", "Shechtman 2011'de Nobel Kimya Ödülü'nü aldı ve kristalin tanımı değiştirildi.")),
        TERIMLER(("crystal", "kristal"), ("unit cell", "birim hücre"), ("lattice", "örgü, kafes"),
                 ("crystallographic restriction", "kristalografik kısıtlama"), ("quasicrystal", "yarı kristal"), ("trace (of a matrix)", "(matrisin) izi")),
    ),

    BOLUM("matematikci", "person", "#E67E22", "Mathematician of the Month: Hypatia of Alexandria", "Ayın Matematikçisi: İskenderiyeli Hypatia",
        P(("Hypatia is one of the most famous names in the history of mathematics.", "Hypatia, matematik tarihinin en ünlü isimlerinden biri."),
          ("Yet we do not know what she looked like.", "Yine de neye benzediğini bilmiyoruz."),
          ("No **authentic** portrait of her survives, so every painting you see is an artist's imagination.", "Ona ait **gerçek** bir portre günümüze ulaşmadı, yani gördüğün her resim bir sanatçının hayal gücünün ürünü."),
          ("That is why there is no picture on this page.", "Bu sayfada resim olmamasının nedeni bu.")),
        H("Her life", "Hayatı"),
        LISTE(("She was born in Alexandria, Egypt, probably between 350 and 370, and her exact birth year is unknown.", "Mısır'ın İskenderiye şehrinde, muhtemelen 350 ile 370 yılları arasında doğdu ve tam doğum yılı bilinmiyor."),
              ("Her father, **Theon of Alexandria**, was a mathematician and astronomer who prepared a well-known edition of Euclid's Elements.", "Babası **İskenderiyeli Theon**, Öklid'in Elemanlar'ının tanınmış bir baskısını hazırlayan bir matematikçi ve astronomdu."),
              ("She studied mathematics and astronomy with him, and ancient writers say that she became an even greater scholar than her father.", "Onunla matematik ve astronomi çalıştı ve antik yazarlara göre babasından da büyük bir bilgin oldu."),
              ("She became the head of a school of **Neoplatonist** philosophy and taught in public.", "**Yeni Platoncu** bir felsefe okulunun başına geçti ve halka açık dersler verdi."),
              ("Students came from far away to hear her, and one of them, Synesius of Cyrene, later wrote her several letters that still survive.", "Öğrenciler onu dinlemek için uzaklardan geldi ve içlerinden biri, Kireneli Synesius, daha sonra ona hâlâ günümüze ulaşan birkaç mektup yazdı."),
              ("In one letter he asks her to help him get a **hydrometer**, a tool for measuring the density of liquids.", "Bir mektubunda, sıvıların yoğunluğunu ölçen bir araç olan **hidrometreyi** edinmek için ondan yardım istiyor."),
              ("A historian of her time, Socrates Scholasticus, wrote that she was more learned than all the philosophers of her day.", "Çağdaşı olan tarihçi Socrates Scholasticus, onun zamanının bütün filozoflarından daha bilgili olduğunu yazdı."),
              ("In March 415, during a bitter political conflict in the city, she was killed by a mob.", "Mart 415'te, şehirdeki sert bir siyasi çatışma sırasında bir kalabalık tarafından öldürüldü.")),
        H("Her contributions", "Katkıları"),
        P(("None of her works survives with her name on it, but ancient sources tell us what she worked on.", "Eserlerinin hiçbiri onun adını taşıyarak günümüze ulaşmadı, ama antik kaynaklar neler üzerinde çalıştığını anlatıyor."),
          ("She wrote **commentaries**, which were the textbooks of her time, to explain difficult works to students.", "Zor eserleri öğrencilere açıklamak için, zamanının ders kitapları sayılan **şerhler** yazdı.")),
        P(("**Conic sections**: she wrote about the Conics of Apollonius.", "**Konik kesitler**: Apollonius'un Konikler'i üzerine yazdı."),
          ("If you cut a cone with a plane, you get a circle, an **ellipse**, a parabola or a hyperbola.", "Bir koniyi bir düzlemle kesersen bir çember, bir **elips**, bir parabol ya da bir hiperbol elde edersin."),
          ("Twelve centuries later, Kepler showed that the planets move on ellipses.", "On iki yüzyıl sonra Kepler gezegenlerin elipsler üzerinde hareket ettiğini gösterdi.")),
        P(("**Diophantus**: she wrote a commentary on the Arithmetica of Diophantus, a book about equations with whole-number solutions.", "**Diophantus**: Tam sayı çözümlü denklemler hakkında bir kitap olan Diophantus'un Arithmetica'sı üzerine bir şerh yazdı."),
          ("Some historians think that the books of the Arithmetica that survive in Greek may come from her edition, but this cannot be proved.", "Bazı tarihçiler Arithmetica'nın Yunanca olarak günümüze ulaşan kitaplarının onun baskısından geliyor olabileceğini düşünüyor, ama bu kanıtlanamıyor."),
          ("Today, equations like x² + y² = z² that we solve in integers are called **Diophantine equations**.", "Bugün x² + y² = z² gibi tam sayılarda çözdüğümüz denklemlere **Diophantus denklemleri** deniyor.")),
        P(("**Astronomy**: her father's commentary on Book III of Ptolemy's Almagest says that the text was revised by \"my daughter Hypatia, the philosopher\".", "**Astronomi**: Babasının Batlamyus'un Almagest'inin III. kitabı üzerine yazdığı şerhte, metnin \"kızım filozof Hypatia\" tarafından gözden geçirildiği yazıyor."),
          ("She is also said to have worked on astronomical tables.", "Astronomi tabloları üzerinde de çalıştığı söylenir.")),
        KUTU("ipucu", "Myth or fact?", "Efsane mi, gerçek mi?",
             ("You may read that Hypatia invented the astrolabe, but this is not true, because astrolabes existed before her.", "Hypatia'nın usturlabı icat ettiğini okuyabilirsin, ama bu doğru değil, çünkü usturlaplar ondan önce de vardı."),
             ("Synesius only wrote that he designed one with the help of what she had taught him.", "Synesius yalnızca ondan öğrendikleri sayesinde bir usturlap tasarladığını yazdı."),
             ("Checking the source is a good habit in history as well as in mathematics.", "Kaynağı kontrol etmek matematikte olduğu kadar tarihte de iyi bir alışkanlıktır.")),
        KUTU("sinif", "For the classroom", "Sınıf için",
             ("Shine a torch on a wall at different angles and watch the edge of the light.", "Bir el fenerini duvara farklı açılarla tut ve ışığın kenarını izle."),
             ("Students will see a circle, then an ellipse, then a parabola-like curve: the conic sections of Apollonius and Hypatia.", "Öğrenciler önce bir çember, sonra bir elips, sonra parabole benzeyen bir eğri görecek: Apollonius'un ve Hypatia'nın konik kesitleri.")),
        TERIMLER(("conic section", "konik kesit"), ("ellipse", "elips"), ("commentary", "şerh, yorum"),
                 ("Diophantine equation", "Diophantus denklemi"), ("authentic", "gerçek, asıl"), ("hydrometer", "hidrometre")),
    ),

    BOLUM("odul", "emoji_events", "#D4A017", "Prize Corner", "Ödüller Köşesi",
        H("SASTRA Ramanujan Prize 2026: Sarah Peluse", "SASTRA Ramanujan Ödülü 2026: Sarah Peluse"),
        P(("On 25 September 2026, the SASTRA Ramanujan Prize was announced for **Sarah Peluse**, an associate professor at Stanford University.", "25 Eylül 2026'da SASTRA Ramanujan Ödülü'nün Stanford Üniversitesi'nde doçent olan **Sarah Peluse**'a verildiği açıklandı."),
          ("The prize is for mathematicians aged 32 or younger, because Ramanujan died at the age of 32.", "Ödül 32 yaş ve altındaki matematikçilere veriliyor, çünkü Ramanujan 32 yaşında hayatını kaybetti."),
          ("It comes with 10,000 US dollars and will be presented on 22 December 2026, Ramanujan's birthday, in Kumbakonam, India.", "Ödül 10.000 ABD doları değerinde ve Ramanujan'ın doğum günü olan 22 Aralık 2026'da Hindistan'ın Kumbakonam şehrinde verilecek.")),
        P(("The prize recognises her work in **analytic number theory**, **additive combinatorics**, combinatorial geometry and group theory.", "Ödül, onun **analitik sayılar teorisi**, **toplamsal kombinatorik**, kombinatoryal geometri ve grup teorisindeki çalışmalarını onurlandırıyor."),
          ("Among her best-known results are bounds on how large a set of integers can be without containing certain polynomial patterns.", "En bilinen sonuçları arasında, bir tam sayı kümesinin belirli polinom örüntülerini içermeden ne kadar büyük olabileceğine dair sınırlar var."),
          ("A nice detail: her doctoral advisor, Kannan Soundararajan, was one of the first winners of the same prize in 2005.", "Güzel bir ayrıntı: Doktora danışmanı Kannan Soundararajan, 2005'te aynı ödülün ilk sahiplerinden biriydi."),
          ("Seven of the 21 earlier winners later received the Fields Medal.", "Önceki 21 ödül sahibinden yedisi daha sonra Fields Madalyası aldı.")),
        KUTU("sinif", "A pattern to try", "Denenecek bir örüntü",
             ("Additive combinatorics asks questions like this: can you choose many numbers from 1 to 20 with no three in an **arithmetic progression**?", "Toplamsal kombinatorik şöyle sorular sorar: 1'den 20'ye kadar, hiçbir üçü **aritmetik dizi** oluşturmayan çok sayıda sayı seçebilir misin?"),
             ("For example, 1, 2, 4, 5, 10, 11, 13, 14 works.", "Örneğin 1, 2, 4, 5, 10, 11, 13, 14 işe yarıyor."),
             ("Ask students to find a longer list, and then to explain why it is so hard.", "Öğrencilerden daha uzun bir liste bulmalarını, sonra bunun neden bu kadar zor olduğunu açıklamalarını iste.")),
        H("Heidelberg Laureate Forum: prize winners meet young researchers", "Heidelberg Laureate Forum: Ödüllüler genç araştırmacılarla buluştu"),
        P(("From 13 to 18 September 2026, the 13th Heidelberg Laureate Forum took place in Germany.", "13-18 Eylül 2026 tarihleri arasında 13. Heidelberg Laureate Forum Almanya'da yapıldı."),
          ("Every year it brings winners of the biggest prizes in mathematics and computer science together with 200 young researchers.", "Forum her yıl matematik ve bilgisayar bilimindeki en büyük ödüllerin sahiplerini 200 genç araştırmacıyla bir araya getiriyor."),
          ("This year, the new Fields medallists **Yu Deng** and **Jacob Tsimerman** gave talks, together with the 2026 Abacus Medal winner Shayan Oveis Gharan.", "Bu yıl yeni Fields madalyası sahipleri **Yu Deng** ve **Jacob Tsimerman**, 2026 Abacus Madalyası sahibi Shayan Oveis Gharan ile birlikte konuşma yaptı."),
          ("One of the panels was called \"AI in Mathematical Research\", which shows how hot this topic has become.", "Panellerden birinin adı \"Matematik Araştırmalarında Yapay Zekâ\"ydı ve bu da konunun ne kadar gündemde olduğunu gösteriyor."),
          ("The talks are free to watch online, so they are a great way to practise academic English.", "Konuşmalar internette ücretsiz izlenebiliyor, yani akademik İngilizce çalışmak için harika bir yol.")),
        TERIMLER(("analytic number theory", "analitik sayılar teorisi"), ("additive combinatorics", "toplamsal kombinatorik"),
                 ("arithmetic progression", "aritmetik dizi"), ("doctoral advisor", "doktora danışmanı"), ("laureate", "ödül sahibi")),
    ),

    BOLUM("dusun", "psychology", "#16A085", "Think Like a Mathematician: Use Symmetry", "Matematikçi Gibi Düşünmek: Simetriyi Kullan",
        P(("Crystals taught us that symmetry creates order.", "Kristaller bize simetrinin düzen yarattığını öğretti."),
          ("In problem solving, symmetry can also save you a lot of work.", "Problem çözerken de simetri seni büyük bir zahmetten kurtarabilir."),
          ("The idea is simple: if a situation looks the same from two sides, use one side to answer for the other.", "Fikir basit: Bir durum iki taraftan aynı görünüyorsa, bir tarafı kullanarak diğerinin cevabını ver.")),
        KUTU("soru", "The problem: coins on a round table", "Problem: Yuvarlak masadaki paralar",
             ("Two players take turns to place identical coins flat on a round table.", "İki oyuncu sırayla aynı büyüklükteki paraları yuvarlak bir masanın üzerine düz olarak koyuyor."),
             ("Coins must not overlap and must not hang over the edge.", "Paralar üst üste binmemeli ve masanın kenarından taşmamalı."),
             ("The player who cannot place a coin loses.", "Para koyamayan oyuncu kaybediyor."),
             ("Does the first player or the second player have a **winning strategy**?", "**Kazanma stratejisi** birinci oyuncuda mı, ikinci oyuncuda mı?")),
        P(("The table can be of any size, so it seems impossible to plan every move.", "Masa herhangi bir büyüklükte olabilir, bu yüzden her hamleyi planlamak imkânsız görünüyor."),
          ("But we do not need to plan, we only need to copy.", "Ama plan yapmamıza gerek yok, sadece kopyalamamız gerekiyor.")),
        H("The solution", "Çözüm"),
        LISTE(("The first player puts the first coin exactly at the **centre** of the table.", "Birinci oyuncu ilk parayı masanın tam **merkezine** koyar."),
              ("After that, whenever the second player places a coin, the first player places a coin at the **mirror point** through the centre.", "Bundan sonra ikinci oyuncu ne zaman bir para koysa, birinci oyuncu merkeze göre **simetrik noktaya** bir para koyar."),
              ("Because the table is symmetric, the mirror place is always free whenever the second player's place was free.", "Masa simetrik olduğu için, ikinci oyuncunun koyduğu yer boşsa simetrik yer de her zaman boştur."),
              ("So the first player can always answer, and the second player is the one who runs out of moves.", "Yani birinci oyuncu her zaman cevap verebilir ve hamlesi tükenen ikinci oyuncu olur.")),
        P(("The first player wins, and we never needed to know the size of the table.", "Birinci oyuncu kazanır ve masanın büyüklüğünü bilmemize hiç gerek kalmadı."),),
        KUTU("ipucu", "The lesson", "Ders",
             ("When a problem has a centre or a mirror line, ask yourself: what stays the same if I reflect or rotate it?", "Bir problemin bir merkezi ya da bir ayna doğrusu varsa kendine sor: Onu yansıtırsam ya da döndürürsem ne aynı kalır?"),
             ("**Symmetry arguments** turn long calculations into short and elegant answers.", "**Simetri argümanları** uzun hesapları kısa ve zarif cevaplara dönüştürür."),
             ("In games, the strategy of copying your opponent is often called the **mirror strategy**.", "Oyunlarda rakibini kopyalama stratejisine genellikle **ayna stratejisi** denir.")),
        KUTU("soru", "Your turn", "Senin sıran",
             ("Ten coins are placed in a circle.", "On para bir çember üzerine diziliyor."),
             ("On each turn, a player takes either one coin or two coins that are next to each other.", "Her turda bir oyuncu ya bir para ya da yan yana duran iki para alıyor."),
             ("The player who takes the last coin wins.", "Son parayı alan oyuncu kazanıyor."),
             ("Who has the winning strategy?", "Kazanma stratejisi kimde?")),
        KUTU("ipucu", "Answer", "Cevap",
             ("The second player wins.", "İkinci oyuncu kazanır."),
             ("After the first move, the remaining coins form a line of 9 or 8 coins.", "İlk hamleden sonra kalan paralar 9 ya da 8 paralık bir sıra oluşturur."),
             ("The second player takes the one or two coins in the exact middle of this line, leaving two equal rows of 4 or 3 coins.", "İkinci oyuncu bu sıranın tam ortasındaki bir ya da iki parayı alır ve geriye 4'er ya da 3'er paralık iki eşit sıra bırakır."),
             ("From then on, the second player copies every move in the other row, so the second player always takes the last coin.", "Bundan sonra ikinci oyuncu her hamleyi diğer sırada kopyalar, böylece son parayı hep ikinci oyuncu alır.")),
        TERIMLER(("winning strategy", "kazanma stratejisi"), ("mirror point", "simetrik nokta"), ("symmetry argument", "simetri argümanı"),
                 ("centre", "merkez"), ("opponent", "rakip")),
    ),

    BOLUM("eglence", "lightbulb", "#E84393", "Fun Facts: The Magic of 9", "Eğlenceli Bilgiler: 9'un Sihri",
        LISTE(("**A seventh month that is ninth**: September comes from the Latin word septem, which means seven.", "**Dokuzuncu olan yedinci ay**: September, yedi anlamına gelen Latince septem kelimesinden geliyor."),
              ("In the oldest Roman calendar, the year started in March, so September really was the seventh month.", "En eski Roma takviminde yıl martta başlıyordu, yani eylül gerçekten yedinci aydı."),
              ("**The divisibility rule for 9**: a number is divisible by 9 exactly when the sum of its **digits** is divisible by 9.", "**9 ile bölünebilme kuralı**: Bir sayı, ancak ve ancak **rakamlarının** toplamı 9'a bölünüyorsa 9'a bölünür."),
              ("The reason is that 10, 100, 1000 and every power of 10 leave a **remainder** of 1 when divided by 9.", "Bunun nedeni 10, 100, 1000 ve 10'un bütün kuvvetlerinin 9'a bölündüğünde 1 **kalanını** vermesi."),
              ("Last year was special: 2025 has digit sum 9, and 2025 = 45².", "Geçen yıl özeldi: 2025'in rakamları toplamı 9 ve 2025 = 45²."),
              ("**A row of ones**: 12345679 × 9 = 111111111, with the digit 8 missing on purpose.", "**Birlerden bir sıra**: 12345679 × 9 = 111111111, burada 8 rakamı bilerek atlanmış."),
              ("Try 12345679 × 18 and 12345679 × 27 as well.", "12345679 × 18 ve 12345679 × 27 işlemlerini de dene."),
              ("**The 1089 trick**: take a three-digit number whose first and last digits differ by at least 2, such as 732.", "**1089 hilesi**: İlk ve son rakamı arasında en az 2 fark olan üç basamaklı bir sayı al, örneğin 732."),
              ("Reverse it and subtract the smaller from the larger: 732 − 237 = 495.", "Sayıyı ters çevir ve küçüğü büyükten çıkar: 732 − 237 = 495."),
              ("Now add this result to its reverse: 495 + 594 = 1089, and you always get 1089.", "Şimdi bu sonucu tersiyle topla: 495 + 594 = 1089 ve sonuç her zaman 1089."),
              ("**Nine on your fingers**: to find 9 × 4, hold up ten fingers and fold down the fourth one.", "**Parmaklarında dokuz**: 9 × 4'ü bulmak için on parmağını aç ve dördüncüyü kapat."),
              ("There are 3 fingers on the left and 6 on the right, so the answer is 36.", "Solda 3, sağda 6 parmak kalır, yani cevap 36."),
              ("**A surprising equality**: 0.999… with nines forever is exactly equal to 1, because 1/9 = 0.111… and 9 × 1/9 = 1.", "**Şaşırtıcı bir eşitlik**: Sonsuza kadar dokuzlarla devam eden 0,999… tam olarak 1'e eşittir, çünkü 1/9 = 0,111… ve 9 × 1/9 = 1.")),
        TERIMLER(("digit", "rakam, basamak"), ("divisibility rule", "bölünebilme kuralı"),
                 ("remainder", "kalan"), ("digit sum", "rakamlar toplamı"), ("repeating decimal", "devirli ondalık sayı")),
    ),

    BOLUM("sinif", "school", "#27AE60", "In the Classroom", "Sınıfta Matematik",
        H("Grades 6–8: Symmetric names", "6-8. sınıflar: Simetrik isimler"),
        P(("Goal: a calm first-week activity to learn names and revise **line symmetry**.", "Hedef: İsimleri öğrenmek ve **eksen simetrisini** tekrar etmek için sakin bir ilk hafta etkinliği."),
          ("You need squared paper, coloured pencils and small mirrors if you have them.", "Kareli kâğıt, renkli kalemler ve varsa küçük aynalar gerekiyor.")),
        LISTE(("Each student writes their first name in capital letters on squared paper.", "Her öğrenci adını büyük harflerle kareli kâğıda yazar."),
              ("They draw every **line of symmetry** of each letter: A and M have a vertical one, B and E a horizontal one, and H has both.", "Her harfin bütün **simetri eksenlerini** çizerler: A ve M'nin dikey, B ve E'nin yatay bir ekseni var, H'nin ise ikisi de var."),
              ("They score 1 point for every line of symmetry, so H gets 2 points and O gets 2 points if written as a perfect oval.", "Her simetri ekseni için 1 puan alırlar, yani H 2 puan, mükemmel bir oval olarak yazılırsa O da 2 puan alır."),
              ("Students introduce themselves with their score: \"I am Elif, and my name scores 3.\"", "Öğrenciler kendilerini puanlarıyla tanıtır: \"Ben Elif, adımın puanı 3.\""),
              ("Finally, the class looks for words that stay the same in a mirror, such as OTTO or AHA.", "Son olarak sınıf aynada aynı kalan kelimeler arar, örneğin OTTO ya da AHA.")),
        KUTU("sinif", "Note for teachers", "Öğretmenlere not",
             ("Turkish letters make the game richer: Ç loses the symmetry of C because of the small mark below, and İ keeps only one of the two lines of I, but Ü and Ö keep the symmetry of U and O.", "Türkçe harfler oyunu zenginleştiriyor: Ç alttaki küçük işaret yüzünden C'nin simetrisini kaybediyor, İ ise I'nın iki ekseninden yalnızca birini koruyor, ama Ü ve Ö, U ile O'nun simetrisini koruyor."),
             ("The activity also gives you a quick picture of who likes to explain, who checks carefully and who needs encouragement.", "Etkinlik ayrıca kimin açıklamayı sevdiğine, kimin dikkatle kontrol ettiğine ve kimin cesaretlendirilmeye ihtiyacı olduğuna dair hızlı bir fikir veriyor.")),
        H("High school: Paper snowflakes and their symmetry group", "Lise: Kâğıt kar taneleri ve simetri grupları"),
        P(("Each student folds a paper circle in half, then into three equal parts, then in half again, and cuts a design along the edges.", "Her öğrenci kâğıttan bir daireyi önce ikiye, sonra üç eşit parçaya, sonra yine ikiye katlar ve kenarlarından bir desen keser."),
          ("When they open it, they get a snowflake with six-fold symmetry, just like real ice crystals.", "Açtıklarında, tıpkı gerçek buz kristalleri gibi altılı simetriye sahip bir kar tanesi elde ederler.")),
        LISTE(("Count the rotations that leave the snowflake looking the same: 0°, 60°, 120°, 180°, 240° and 300°.", "Kar tanesini aynı gösteren dönmeleri say: 0°, 60°, 120°, 180°, 240° ve 300°."),
              ("Count the mirror lines: there are 6 of them.", "Ayna doğrularını say: 6 tane var."),
              ("Together these 12 moves form the **dihedral group** D₆.", "Bu 12 hareket birlikte **dihedral grubu** D₆'yı oluşturur."),
              ("Check together that doing two moves one after the other always gives another move in the list.", "İki hareketi art arda yapmanın her zaman listedeki başka bir hareketi verdiğini birlikte kontrol edin.")),
        KUTU("soru", "Discussion questions", "Tartışma soruları",
             ("What happens if you fold the paper into five parts instead?", "Kâğıdı beş parçaya katlarsanız ne olur?"),
             ("Is a five-fold snowflake possible on paper, and why is it impossible in a real ice crystal?", "Beşli bir kar tanesi kâğıt üzerinde mümkün mü ve gerçek bir buz kristalinde neden imkânsız?"),
             ("Does a rotation by 60° followed by a reflection give the same result as the reflection followed by the rotation?", "60° dönme ardından yansıma, yansıma ardından dönmeyle aynı sonucu verir mi?")),
        P(("This activity connects transformations in the plane with a first taste of **group theory**, and it ends with a beautiful window decoration.", "Bu etkinlik düzlemdeki dönüşümleri **grup teorisine** ilk bir bakışla birleştiriyor ve sonunda güzel bir pencere süsü ortaya çıkıyor."),),
        TERIMLER(("line of symmetry", "simetri ekseni"), ("rotational symmetry", "dönme simetrisi"), ("reflection", "yansıma"),
                 ("dihedral group", "dihedral grup"), ("group theory", "grup teorisi")),
    ),

    BOLUM("gundem", "campaign", "#C0392B", "Education in Türkiye", "Eğitim Gündemi",
        H("The 2026–2027 school year has started", "2026-2027 eğitim öğretim yılı başladı"),
        P(("The new school year started on Monday, 14 September 2026.", "Yeni eğitim öğretim yılı 14 Eylül 2026 pazartesi günü başladı."),
          ("According to news reports, about 17 million students and 1.2 million teachers returned to school.", "Haberlere göre yaklaşık 17 milyon öğrenci ve 1,2 milyon öğretmen okula döndü."),
          ("Before that, **orientation** activities for preschool and first-grade pupils and their families were held from 7 to 11 September.", "Bundan önce, 7-11 Eylül tarihleri arasında okul öncesi ve birinci sınıf öğrencileri ile aileleri için **uyum** etkinlikleri yapıldı."),
          ("Students still may not use mobile phones in class.", "Öğrenciler derslerde hâlâ cep telefonu kullanamıyor.")),
        H("Where is the Maarif model this year?", "Maarif modeli bu yıl hangi sınıflarda?"),
        P(("This year, the Türkiye Yüzyılı Maarif Modeli is used in grades 1, 2, 3, 5, 6, 7, 9, 10 and 11, as well as in preschool.", "Bu yıl Türkiye Yüzyılı Maarif Modeli okul öncesinin yanı sıra 1, 2, 3, 5, 6, 7, 9, 10 ve 11. sınıflarda uygulanıyor."),
          ("Grades 4, 8 and 12 still follow their existing programmes this year.", "4, 8 ve 12. sınıflar bu yıl hâlâ mevcut programlarıyla devam ediyor."),
          ("For maths teachers, this means that the classes preparing for LGS and YKS still follow the old **curriculum**.", "Matematik öğretmenleri için bu, LGS'ye ve YKS'ye hazırlanan sınıfların hâlâ eski **öğretim programını** izlediği anlamına geliyor.")),
        KUTU("sinif", "For grade 7 and grade 11 teachers", "7. ve 11. sınıf öğretmenlerine",
             ("This is the first year of the new programme for grade 7 and grade 11, so the **yearly plan** deserves a careful first reading.", "7. ve 11. sınıflar için bu yeni programın ilk yılı, bu yüzden **yıllık plan** dikkatli bir ilk okumayı hak ediyor."),
             ("Marking the units where students will need old topics again can save time later in the year.", "Öğrencilerin eski konulara yeniden ihtiyaç duyacağı üniteleri işaretlemek, yılın ilerleyen bölümünde zaman kazandırabilir.")),
        H("The calendar at a glance", "Bir bakışta takvim"),
        LISTE(("First mid-term break: 16–20 November 2026.", "Birinci ara tatil: 16-20 Kasım 2026."),
              ("Semester break: 25 January – 5 February 2027.", "Yarıyıl tatili: 25 Ocak – 5 Şubat 2027."),
              ("The second term starts on 8 February 2027.", "İkinci dönem 8 Şubat 2027'de başlıyor."),
              ("Second mid-term break: 8–12 March 2027.", "İkinci ara tatil: 8-12 Mart 2027."),
              ("The school year ends on 25 June 2027.", "Ders yılı 25 Haziran 2027'de sona eriyor.")),
        TERIMLER(("orientation", "uyum, oryantasyon"), ("curriculum", "öğretim programı, müfredat"), ("yearly plan", "yıllık plan"),
                 ("mid-term break", "ara tatil"), ("semester break", "yarıyıl tatili")),
    ),

    BOLUM("oku", "menu_book", "#34495E", "Read Like a Mathematician", "Matematikçi Gibi Oku",
        P(("Hypatia's students read Euclid, so this month we look at phrases that geometry proofs have used for centuries.", "Hypatia'nın öğrencileri Öklid okuyordu, bu yüzden bu ay geometri ispatlarının yüzyıllardır kullandığı kalıplara bakıyoruz."),
          ("Many of them also help you to use **symmetry** in a proof.", "Bunların çoğu bir ispatta **simetriyi** kullanmana da yardım eder.")),
        TABLO(["English", "Türkçe", "Note / Not"],
              ["Given …", "… verilsin, verilen …", "lists what we know / bildiklerimizi sıralar"],
              ["Consider …", "… ele alalım", "introduces a useful object / işe yarar bir nesneyi tanıtır"],
              ["Without loss of generality (WLOG)", "genelliği bozmadan", "we may choose one case / bir durumu seçebiliriz"],
              ["By symmetry", "simetriden", "the other case is the same / diğer durum aynıdır"],
              ["is said to be …", "… olduğu söylenir, … denir", "used in definitions / tanımlarda kullanılır"],
              ["up to rotation", "dönme farkı dışında", "rotated copies count as one / döndürülmüş kopyalar tek sayılır"],
              ["as required / Q.E.D.", "istendiği gibi / ispat biter", "the end of a proof / ispatın sonu"]),
        KUTU("soru", "Mini reading: the base angles of an isosceles triangle", "Mini okuma: İkizkenar üçgenin taban açıları",
             ("Theorem (Euclid I.5). In an isosceles triangle, the base angles are equal.", "Teorem (Öklid I.5). Bir ikizkenar üçgende taban açıları eşittir."),
             ("Proof. Given a triangle ABC with AB = AC, we show that ∠B = ∠C.", "İspat. AB = AC olan bir ABC üçgeni verilsin, ∠B = ∠C olduğunu gösteriyoruz."),
             ("Consider the triangle ABC and its mirror copy ACB.", "ABC üçgenini ve onun ayna kopyası ACB'yi ele alalım."),
             ("We have AB = AC, AC = AB, and the angle at A is common to both.", "AB = AC, AC = AB ve A'daki açı ikisinde de ortak."),
             ("Hence, by the side-angle-side rule, triangle ABC is **congruent** to triangle ACB.", "Dolayısıyla kenar-açı-kenar kuralına göre ABC üçgeni ACB üçgenine **eştir**."),
             ("Therefore the angle at B equals the angle at C, as required. ∎", "Bu yüzden B'deki açı C'deki açıya eşittir, istendiği gibi. ∎")),
        KUTU("ipucu", "A small note", "Küçük not",
             ("This short proof is usually credited to Pappus of Alexandria, who lived in the same city before Hypatia.", "Bu kısa ispat genellikle Hypatia'dan önce aynı şehirde yaşamış İskenderiyeli Pappus'a atfedilir."),
             ("Euclid's own proof is much longer, and medieval students called it the \"bridge of asses\" because many of them got stuck there.", "Öklid'in kendi ispatı çok daha uzun ve Orta Çağ öğrencileri birçoğu orada takıldığı için ona \"eşek köprüsü\" adını verdi."),
             ("The trick is pure symmetry: compare the triangle with its own reflection.", "Hile tamamen simetri: Üçgeni kendi yansımasıyla karşılaştır.")),
        TERIMLER(("given", "verilen, verilsin"), ("without loss of generality", "genelliği bozmadan"), ("by symmetry", "simetriden"),
                 ("congruent", "eş"), ("isosceles triangle", "ikizkenar üçgen"), ("as required", "istendiği gibi")),
    ),
]

quiz = [
    SORU("What did Claude formalize in the Lean language in September 2026?", "Claude Eylül 2026'da Lean dilinde neyi biçimselleştirdi?",
         ["The Riemann hypothesis", "The proof of Fermat's Last Theorem", "The four colour theorem", "Euclid's Elements"], 1,
         "Anthropic announced on 4 September 2026 that Claude had produced a complete computer-checked proof of Fermat's Last Theorem.", "Anthropic 4 Eylül 2026'da Claude'un Fermat'nın Son Teoremi'nin bilgisayarla kontrol edilmiş eksiksiz bir ispatını ürettiğini duyurdu."),
    SORU("Which formula is Bragg's law?", "Bragg yasası hangi formüldür?",
         ["n · λ = 2d · sin θ", "E = m · c²", "a² + b² = c²", "R₀ = β / γ"], 0,
         "The path difference 2d · sin θ must be a whole number of wavelengths.", "Yol farkı 2d · sin θ, dalga boyunun tam katı olmalıdır."),
    SORU("Which rotational symmetry is impossible in a periodic crystal?", "Periyodik bir kristalde hangi dönme simetrisi imkânsızdır?",
         ["2-fold", "3-fold", "5-fold", "6-fold"], 2,
         "2 cos 72° is not an integer, so a lattice cannot have five-fold rotations.", "2 cos 72° bir tam sayı değildir, bu yüzden bir örgü beşli dönmelere sahip olamaz."),
    SORU("Who was Hypatia's father?", "Hypatia'nın babası kimdi?",
         ["Euclid", "Apollonius", "Theon of Alexandria", "Diophantus"], 2,
         "Theon of Alexandria was a mathematician and astronomer who taught his daughter.", "İskenderiyeli Theon, kızını yetiştiren bir matematikçi ve astronomdu."),
    SORU("Which of these numbers is divisible by 9?", "Bu sayılardan hangisi 9'a bölünür?",
         ["2026", "2025", "2027", "2029"], 1,
         "The digit sum of 2025 is 2 + 0 + 2 + 5 = 9.", "2025'in rakamları toplamı 2 + 0 + 2 + 5 = 9."),
    SORU("In the round table coin game, where should the first player put the first coin?", "Yuvarlak masa para oyununda birinci oyuncu ilk parayı nereye koymalı?",
         ["At the edge", "Exactly at the centre", "Anywhere at random", "As far as possible from the centre"], 1,
         "After a coin at the centre, the first player can always copy the opponent's move through the centre.", "Merkeze konan bir paradan sonra birinci oyuncu rakibinin hamlesini her zaman merkeze göre kopyalayabilir."),
]

bulmacalar = [
    ANAGRAM("TYRSCAL", "CRYSTAL", "A solid whose atoms repeat in a regular pattern.", "Atomları düzenli bir desenle tekrarlanan katı."),
    ANAGRAM("TICELAT", "LATTICE", "A regular grid of points that repeats in space.", "Uzayda tekrarlanan düzenli bir nokta ızgarası."),
    ANAGRAM("RANTTEP", "PATTERN", "Something that repeats in a regular way, like the atoms in a crystal.", "Kristaldeki atomlar gibi düzenli biçimde tekrarlanan şey."),
    ANAGRAM("RORMIR", "MIRROR", "It shows you your reflection.", "Sana yansımanı gösterir."),
    ESLESTIR("Match the terms", "Terimleri eşleştir",
             ("unit cell", "birim hücre"), ("wavelength", "dalga boyu"), ("conic section", "konik kesit"),
             ("digit sum", "rakamlar toplamı"), ("winning strategy", "kazanma stratejisi")),
    MANTIK("The riddle of Diophantus", "Diophantus bilmecesi",
           "An old puzzle says: Diophantus was a boy for 1/6 of his life, his beard grew after another 1/12, and he married after another 1/7. His son was born 5 years later and lived half as long as his father. Diophantus died 4 years after his son. How old was Diophantus when he died?",
           "Eski bir bilmece şöyle der: Diophantus ömrünün 1/6'sında çocuktu, 1/12'si daha geçince sakalı çıktı, 1/7'si daha geçince evlendi. Oğlu 5 yıl sonra doğdu ve babasının ömrünün yarısı kadar yaşadı. Diophantus oğlundan 4 yıl sonra öldü. Diophantus kaç yaşında öldü?",
           "Let x be his age. Then x = x/6 + x/12 + x/7 + 5 + x/2 + 4. With the common denominator 84, this gives 84x = 14x + 7x + 12x + 42x + 756, so 9x = 756 and x = 84. Diophantus died at the age of 84.",
           "Yaşı x olsun. O zaman x = x/6 + x/12 + x/7 + 5 + x/2 + 4. Ortak payda 84 ile 84x = 14x + 7x + 12x + 42x + 756 olur, yani 9x = 756 ve x = 84. Diophantus 84 yaşında öldü."),
    MANTIK("A giant number", "Dev bir sayı",
           "Write the numbers from 1 to 2026 one after another to make one giant number: 123456789101112…2026. What is the remainder when this number is divided by 9?",
           "1'den 2026'ya kadar olan sayıları yan yana yazarak dev bir sayı oluştur: 123456789101112…2026. Bu sayı 9'a bölündüğünde kalan kaçtır?",
           "A number leaves the same remainder as its digit sum, and the digit sum of each small number leaves the same remainder as the number itself. So we only need 1 + 2 + … + 2026 = 2026 × 2027 / 2 = 2,053,351. Its digit sum is 19, and 19 leaves remainder 1 when divided by 9. The answer is 1.",
           "Bir sayı, rakamları toplamıyla aynı kalanı verir ve her küçük sayının rakamları toplamı da o sayının kendisiyle aynı kalanı verir. Yani yalnızca 1 + 2 + … + 2026 = 2026 × 2027 / 2 = 2.053.351 toplamına bakmamız yeterli. Rakamları toplamı 19 ve 19'un 9'a bölümünden kalan 1. Cevap 1."),
]

SAYI_VERI = SAYI(
    9, "Eylül 2026", "September 2026", "Düzen ve Simetri", "Order and Symmetry",
    {"renkler": ["#8C6A1C", "#5E4710"], "desen": 4},
    bolumler, quiz, bulmacalar,
    ad="Hidden Order", ad_tr="Gizli Düzen",
)
